package toolmeta

import (
	"slices"
	"testing"
)

// builtinInventory is every fixed model-facing tool this build registers, with
// the file that defines its name. "Fixed" excludes the two families whose names
// are only known at runtime — MCP servers and plugins — which HandWritten
// covers by prefix instead.
//
// The guard it powers is one sentence: a builtin is either generated by
// toolgen, or an accepted exception. A tool that is neither means someone
// hand-wrote a schema that toolgen could have owned, and this test is where
// that shows up.
var builtinInventory = []struct {
	name      string
	generated bool
	source    string
}{
	{"bash", false, "internal/agent/sandbox/bash.go"},
	{"view_image", false, "internal/agent/sandbox/view_image.go"},
	{"notify", false, "internal/notify/tool.go"},
	{"goal_control", false, "internal/goal/executor.go"},
	{"code", false, "pkg/agent/code_strategy.go"},
	{"library_search", false, "internal/library/tool.go"},
	{"memory", false, "internal/memory/tool.go"},                // pending split
	{"skills", false, "internal/skills/tool.go"},                // pending split
	{"session", false, "internal/agent/session/access/tool.go"}, // pending split

	{"goal", true, "internal/goal/tool_gen.go"},
	{"scheduler", true, "internal/scheduler/tool_gen.go"},
	{"workflow", true, "internal/workflow/tool_gen.go"},
	{"oauth", true, "internal/connections/tool_gen.go"},
	{"email", true, "internal/email/tool_gen.go"},
	{"share", true, "internal/share/tool_gen.go"},
	{"vault", true, "internal/vault/tool_gen.go"},
	{"recally_digest", true, "internal/recally/tool_gen.go"},
	{"recally_digest_save", true, "internal/recally/tool_gen.go"},
	{"recally_entry_add", true, "internal/recally/tool_gen.go"},
	{"recally_entry_list", true, "internal/recally/tool_gen.go"},
	{"recally_entry_update", true, "internal/recally/tool_gen.go"},
	{"recally_feed_add", true, "internal/recally/tool_gen.go"},
	{"recally_feed_list", true, "internal/recally/tool_gen.go"},
	{"recally_feed_poll", true, "internal/recally/tool_gen.go"},
	{"recally_feed_remove", true, "internal/recally/tool_gen.go"},
	{"recally_get_article", true, "internal/recally/tool_gen.go"},
	{"recally_list_articles", true, "internal/recally/tool_gen.go"},
	{"recally_save_article", true, "internal/recally/tool_gen.go"},
}

func TestEveryBuiltinIsGeneratedOrAnAcceptedException(t *testing.T) {
	for _, tool := range builtinInventory {
		if got := HandWritten(tool.name); got == tool.generated {
			if tool.generated {
				t.Errorf("HandWritten(%q) = true, but %s generates it", tool.name, tool.source)
				continue
			}
			t.Errorf("HandWritten(%q) = false, but %s hand-writes it: generate it, or add it to handWritten with a reason", tool.name, tool.source)
		}
	}
}

// The exception lists are closed, and the closure is the point: HandWritten
// must not quietly grow a third mechanism. Update these literals in the same
// commit that changes the maps, so the diff shows what was accepted.
func TestExceptionListsAreExactlyWhatTheRuleDocuments(t *testing.T) {
	assertKeys(t, "handWritten", handWritten, []string{"bash", "code", "goal_control", "notify", "view_image", "webfetch"})
	assertKeys(t, "pendingSplit", pendingSplit, []string{"memory", "session", "skills"})
	if want := []string{"mcp__", "library_"}; !slices.Equal(handWrittenPrefixes, want) {
		t.Errorf("handWrittenPrefixes=%v, want exactly %v", handWrittenPrefixes, want)
	}
}

func assertKeys(t *testing.T, label string, set map[string]bool, want []string) {
	t.Helper()
	got := make([]string, 0, len(set))
	for name := range set {
		got = append(got, name)
	}
	slices.Sort(got)
	if !slices.Equal(got, want) {
		t.Errorf("%s=%v, want exactly %v (see rules/agent-tools.md §2)", label, got, want)
	}
}
