CREATE TABLE agent (
    id            TEXT PRIMARY KEY,
    name          TEXT NOT NULL,
    model         TEXT NOT NULL DEFAULT '',
    model_thinking TEXT NOT NULL DEFAULT '',
    model_strong  TEXT NOT NULL DEFAULT '',
    model_strong_thinking TEXT NOT NULL DEFAULT '',
    model_fast    TEXT NOT NULL DEFAULT '',
    model_fast_thinking TEXT NOT NULL DEFAULT '',
    system_prompt TEXT NOT NULL DEFAULT '',
    soul          TEXT NOT NULL DEFAULT '',
    workspace     TEXT NOT NULL,
    sandbox       JSONB NOT NULL DEFAULT '{}',
    enabled_builtin_skills JSONB NOT NULL DEFAULT '[]',
    scope         TEXT NOT NULL DEFAULT 'system',
    creator_id    TEXT NOT NULL DEFAULT '',
    enabled       BOOLEAN NOT NULL DEFAULT true,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);
