// Code generated by go run ./internal/cmd/toolgen; DO NOT EDIT.

package controlplane

import (
	"context"
	"fmt"

	"github.com/CherryHQ/stella/internal/agent/toolmeta"
	"github.com/CherryHQ/stella/pkg/tools"
)

// ProviderToolPrefix is the family every generated provider tool name starts with.
const ProviderToolPrefix = "provider"

// ProviderActionTool describes one generated tool: an exact schema bound to one action.
type ProviderActionTool = toolmeta.ActionTool

// ProviderActionTools lists every generated tool in a stable order.
func ProviderActionTools() []ProviderActionTool {
	return []ProviderActionTool{
		{Name: "provider_create", Family: "provider", Action: "create", InputSchemaJSON: `{
  "additionalProperties": false,
  "properties": {
    "base_url": {
      "type": "string"
    },
    "enabled": {
      "type": "boolean"
    },
    "id": {
      "type": "string"
    },
    "models": {
      "additionalProperties": {
        "properties": {
          "contextWindow": {
            "type": "integer"
          },
          "cost": {
            "properties": {
              "cacheRead": {
                "format": "double",
                "type": "number"
              },
              "cacheWrite": {
                "format": "double",
                "type": "number"
              },
              "input": {
                "format": "double",
                "type": "number"
              },
              "output": {
                "format": "double",
                "type": "number"
              }
            },
            "type": "object"
          },
          "enabled": {
            "type": "boolean"
          },
          "id": {
            "type": "string"
          },
          "input": {
            "items": {
              "type": "string"
            },
            "type": "array"
          },
          "maxTokens": {
            "type": "integer"
          },
          "name": {
            "type": "string"
          },
          "output": {
            "items": {
              "type": "string"
            },
            "type": "array"
          },
          "reasoning": {
            "type": "boolean"
          }
        },
        "required": [
          "enabled"
        ],
        "type": "object"
      },
      "type": "object"
    },
    "name": {
      "type": "string"
    },
    "type": {
      "type": "string"
    }
  },
  "required": [
    "base_url",
    "enabled",
    "id",
    "name",
    "type"
  ],
  "type": "object"
}`},
		{Name: "provider_delete", Family: "provider", Action: "delete", InputSchemaJSON: `{
  "additionalProperties": false,
  "properties": {
    "expected_version": {
      "description": "Opaque version returned by provider_get.",
      "type": "string"
    },
    "id": {
      "type": "string"
    }
  },
  "required": [
    "expected_version",
    "id"
  ],
  "type": "object"
}`},
		{Name: "provider_get", Family: "provider", Action: "get", InputSchemaJSON: `{
  "additionalProperties": false,
  "properties": {
    "id": {
      "type": "string"
    }
  },
  "required": [
    "id"
  ],
  "type": "object"
}`},
		{Name: "provider_list", Family: "provider", Action: "list", InputSchemaJSON: `{
  "additionalProperties": false,
  "properties": {},
  "type": "object"
}`},
		{Name: "provider_update", Family: "provider", Action: "update", InputSchemaJSON: `{
  "additionalProperties": false,
  "properties": {
    "base_url": {
      "type": "string"
    },
    "enabled": {
      "type": "boolean"
    },
    "expected_version": {
      "description": "Opaque version returned by provider_get.",
      "type": "string"
    },
    "id": {
      "type": "string"
    },
    "models": {
      "additionalProperties": {
        "properties": {
          "contextWindow": {
            "type": "integer"
          },
          "cost": {
            "properties": {
              "cacheRead": {
                "format": "double",
                "type": "number"
              },
              "cacheWrite": {
                "format": "double",
                "type": "number"
              },
              "input": {
                "format": "double",
                "type": "number"
              },
              "output": {
                "format": "double",
                "type": "number"
              }
            },
            "type": "object"
          },
          "enabled": {
            "type": "boolean"
          },
          "id": {
            "type": "string"
          },
          "input": {
            "items": {
              "type": "string"
            },
            "type": "array"
          },
          "maxTokens": {
            "type": "integer"
          },
          "name": {
            "type": "string"
          },
          "output": {
            "items": {
              "type": "string"
            },
            "type": "array"
          },
          "reasoning": {
            "type": "boolean"
          }
        },
        "required": [
          "enabled"
        ],
        "type": "object"
      },
      "type": "object"
    },
    "name": {
      "type": "string"
    },
    "type": {
      "type": "string"
    }
  },
  "required": [
    "base_url",
    "enabled",
    "expected_version",
    "id",
    "name",
    "type"
  ],
  "type": "object"
}`},
	}
}

// ProviderToolNames lists every generated tool name, for callers that gate on names.
func ProviderToolNames() []string {
	names := make([]string, 0, len(ProviderActionTools()))
	for _, spec := range ProviderActionTools() {
		names = append(names, spec.Name)
	}
	return names
}

type ProviderHandler interface {
	Create(context.Context, ProviderCreateInput) (any, error)
	Delete(context.Context, ProviderDeleteInput) (any, error)
	Get(context.Context, ProviderGetInput) (any, error)
	List(context.Context, ProviderListInput) (any, error)
	Update(context.Context, ProviderUpdateInput) (any, error)
}

type ProviderCreateInput struct {
	BaseUrl string         `json:"base_url,omitempty"`
	Enabled bool           `json:"enabled,omitempty"`
	Id      string         `json:"id,omitempty"`
	Models  map[string]any `json:"models,omitempty"`
	Name    string         `json:"name,omitempty"`
	Type    string         `json:"type,omitempty"`
}

type ProviderDeleteInput struct {
	ExpectedVersion string `json:"expected_version,omitempty"`
	Id              string `json:"id,omitempty"`
}

type ProviderGetInput struct {
	Id string `json:"id,omitempty"`
}

type ProviderListInput struct {
}

type ProviderUpdateInput struct {
	BaseUrl         string         `json:"base_url,omitempty"`
	Enabled         bool           `json:"enabled,omitempty"`
	ExpectedVersion string         `json:"expected_version,omitempty"`
	Id              string         `json:"id,omitempty"`
	Models          map[string]any `json:"models,omitempty"`
	Name            string         `json:"name,omitempty"`
	Type            string         `json:"type,omitempty"`
}

func ProviderDispatch(ctx context.Context, h ProviderHandler, action string, args map[string]any) (any, error) {
	switch action {
	case "create":
		var in ProviderCreateInput
		if err := tools.DecodeInputStrict(args, &in, []string{"base_url", "enabled", "id", "name", "type"}); err != nil {
			return nil, err
		}
		return h.Create(ctx, in)
	case "delete":
		var in ProviderDeleteInput
		if err := tools.DecodeInputStrict(args, &in, []string{"expected_version", "id"}); err != nil {
			return nil, err
		}
		return h.Delete(ctx, in)
	case "get":
		var in ProviderGetInput
		if err := tools.DecodeInputStrict(args, &in, []string{"id"}); err != nil {
			return nil, err
		}
		return h.Get(ctx, in)
	case "list":
		var in ProviderListInput
		if err := tools.DecodeInputStrict(args, &in, []string(nil)); err != nil {
			return nil, err
		}
		return h.List(ctx, in)
	case "update":
		var in ProviderUpdateInput
		if err := tools.DecodeInputStrict(args, &in, []string{"base_url", "enabled", "expected_version", "id", "name", "type"}); err != nil {
			return nil, err
		}
		return h.Update(ctx, in)
	default:
		return nil, fmt.Errorf("unknown provider action %q", action)
	}
}
