// Code generated by go run ./internal/cmd/toolgen; DO NOT EDIT.

package controlplane

import (
	"context"
	"fmt"

	"github.com/CherryHQ/stella/internal/agent/toolmeta"
	"github.com/CherryHQ/stella/pkg/tools"
)

// SettingsProviderToolPrefix is the family every generated settings_provider tool name starts with.
const SettingsProviderToolPrefix = "settings_provider"

// SettingsProviderActionTool describes one generated tool: an exact schema bound to one action.
type SettingsProviderActionTool = toolmeta.ActionTool

// SettingsProviderActionTools lists every generated tool in a stable order.
func SettingsProviderActionTools() []SettingsProviderActionTool {
	return []SettingsProviderActionTool{
		{Name: "settings_provider_create", Family: "settings_provider", Action: "create", InputSchemaJSON: `{
  "additionalProperties": false,
  "properties": {
    "base_url": {
      "type": "string"
    },
    "enabled": {
      "type": "boolean"
    },
    "id": {
      "type": "string"
    },
    "models": {
      "additionalProperties": {
        "additionalProperties": false,
        "properties": {
          "catalogModel": {
            "description": "Canonical lab model ID used as the inherited metadata source. Empty disables automatic matching.",
            "type": "string"
          },
          "contextWindow": {
            "type": "integer"
          },
          "cost": {
            "additionalProperties": false,
            "properties": {
              "cacheRead": {
                "format": "double",
                "type": "number"
              },
              "cacheWrite": {
                "format": "double",
                "type": "number"
              },
              "input": {
                "format": "double",
                "type": "number"
              },
              "inputAudio": {
                "format": "double",
                "type": "number"
              },
              "output": {
                "format": "double",
                "type": "number"
              },
              "outputAudio": {
                "format": "double",
                "type": "number"
              },
              "reasoning": {
                "format": "double",
                "type": "number"
              },
              "tiers": {
                "items": {
                  "additionalProperties": false,
                  "properties": {
                    "cacheRead": {
                      "format": "double",
                      "type": "number"
                    },
                    "cacheWrite": {
                      "format": "double",
                      "type": "number"
                    },
                    "input": {
                      "format": "double",
                      "type": "number"
                    },
                    "inputAudio": {
                      "format": "double",
                      "type": "number"
                    },
                    "minContext": {
                      "type": "integer"
                    },
                    "output": {
                      "format": "double",
                      "type": "number"
                    },
                    "outputAudio": {
                      "format": "double",
                      "type": "number"
                    },
                    "reasoning": {
                      "format": "double",
                      "type": "number"
                    }
                  },
                  "required": [
                    "minContext"
                  ],
                  "type": "object"
                },
                "type": "array"
              }
            },
            "type": "object"
          },
          "enabled": {
            "type": "boolean"
          },
          "id": {
            "type": "string"
          },
          "input": {
            "items": {
              "type": "string"
            },
            "type": "array"
          },
          "maxTokens": {
            "type": "integer"
          },
          "name": {
            "type": "string"
          },
          "output": {
            "items": {
              "type": "string"
            },
            "type": "array"
          },
          "reasoning": {
            "type": "boolean"
          }
        },
        "required": [
          "enabled"
        ],
        "type": "object"
      },
      "type": "object"
    },
    "name": {
      "type": "string"
    },
    "type": {
      "type": "string"
    }
  },
  "required": [
    "base_url",
    "enabled",
    "id",
    "name",
    "type"
  ],
  "type": "object"
}`},
		{Name: "settings_provider_delete", Family: "settings_provider", Action: "delete", InputSchemaJSON: `{
  "additionalProperties": false,
  "properties": {
    "expected_version": {
      "description": "Opaque version returned by settings_provider_get.",
      "type": "string"
    },
    "id": {
      "type": "string"
    }
  },
  "required": [
    "expected_version",
    "id"
  ],
  "type": "object"
}`},
		{Name: "settings_provider_get", Family: "settings_provider", Action: "get", InputSchemaJSON: `{
  "additionalProperties": false,
  "properties": {
    "id": {
      "type": "string"
    }
  },
  "required": [
    "id"
  ],
  "type": "object"
}`},
		{Name: "settings_provider_list", Family: "settings_provider", Action: "list", InputSchemaJSON: `{
  "additionalProperties": false,
  "properties": {},
  "type": "object"
}`},
		{Name: "settings_provider_update", Family: "settings_provider", Action: "update", InputSchemaJSON: `{
  "additionalProperties": false,
  "properties": {
    "base_url": {
      "type": "string"
    },
    "enabled": {
      "type": "boolean"
    },
    "expected_version": {
      "description": "Opaque version returned by settings_provider_get.",
      "type": "string"
    },
    "id": {
      "type": "string"
    },
    "models": {
      "additionalProperties": {
        "additionalProperties": false,
        "properties": {
          "catalogModel": {
            "description": "Canonical lab model ID used as the inherited metadata source. Empty disables automatic matching.",
            "type": "string"
          },
          "contextWindow": {
            "type": "integer"
          },
          "cost": {
            "additionalProperties": false,
            "properties": {
              "cacheRead": {
                "format": "double",
                "type": "number"
              },
              "cacheWrite": {
                "format": "double",
                "type": "number"
              },
              "input": {
                "format": "double",
                "type": "number"
              },
              "inputAudio": {
                "format": "double",
                "type": "number"
              },
              "output": {
                "format": "double",
                "type": "number"
              },
              "outputAudio": {
                "format": "double",
                "type": "number"
              },
              "reasoning": {
                "format": "double",
                "type": "number"
              },
              "tiers": {
                "items": {
                  "additionalProperties": false,
                  "properties": {
                    "cacheRead": {
                      "format": "double",
                      "type": "number"
                    },
                    "cacheWrite": {
                      "format": "double",
                      "type": "number"
                    },
                    "input": {
                      "format": "double",
                      "type": "number"
                    },
                    "inputAudio": {
                      "format": "double",
                      "type": "number"
                    },
                    "minContext": {
                      "type": "integer"
                    },
                    "output": {
                      "format": "double",
                      "type": "number"
                    },
                    "outputAudio": {
                      "format": "double",
                      "type": "number"
                    },
                    "reasoning": {
                      "format": "double",
                      "type": "number"
                    }
                  },
                  "required": [
                    "minContext"
                  ],
                  "type": "object"
                },
                "type": "array"
              }
            },
            "type": "object"
          },
          "enabled": {
            "type": "boolean"
          },
          "id": {
            "type": "string"
          },
          "input": {
            "items": {
              "type": "string"
            },
            "type": "array"
          },
          "maxTokens": {
            "type": "integer"
          },
          "name": {
            "type": "string"
          },
          "output": {
            "items": {
              "type": "string"
            },
            "type": "array"
          },
          "reasoning": {
            "type": "boolean"
          }
        },
        "required": [
          "enabled"
        ],
        "type": "object"
      },
      "type": "object"
    },
    "name": {
      "type": "string"
    },
    "type": {
      "type": "string"
    }
  },
  "required": [
    "base_url",
    "enabled",
    "expected_version",
    "id",
    "name",
    "type"
  ],
  "type": "object"
}`},
	}
}

// SettingsProviderToolNames lists every generated tool name, for callers that gate on names.
func SettingsProviderToolNames() []string {
	names := make([]string, 0, len(SettingsProviderActionTools()))
	for _, spec := range SettingsProviderActionTools() {
		names = append(names, spec.Name)
	}
	return names
}

type SettingsProviderHandler interface {
	Create(context.Context, SettingsProviderCreateInput) (any, error)
	Delete(context.Context, SettingsProviderDeleteInput) (any, error)
	Get(context.Context, SettingsProviderGetInput) (any, error)
	List(context.Context, SettingsProviderListInput) (any, error)
	Update(context.Context, SettingsProviderUpdateInput) (any, error)
}

type SettingsProviderCreateInput struct {
	BaseUrl string `json:"base_url,omitempty"`
	Enabled bool   `json:"enabled,omitempty"`
	Id      string `json:"id,omitempty"`
	Models  map[string]struct {
		CatalogModel  string `json:"catalogModel,omitempty"`
		ContextWindow int    `json:"contextWindow,omitempty"`
		Cost          struct {
			CacheRead   float64 `json:"cacheRead,omitempty"`
			CacheWrite  float64 `json:"cacheWrite,omitempty"`
			Input       float64 `json:"input,omitempty"`
			InputAudio  float64 `json:"inputAudio,omitempty"`
			Output      float64 `json:"output,omitempty"`
			OutputAudio float64 `json:"outputAudio,omitempty"`
			Reasoning   float64 `json:"reasoning,omitempty"`
			Tiers       []struct {
				CacheRead   float64 `json:"cacheRead,omitempty"`
				CacheWrite  float64 `json:"cacheWrite,omitempty"`
				Input       float64 `json:"input,omitempty"`
				InputAudio  float64 `json:"inputAudio,omitempty"`
				MinContext  int     `json:"minContext,omitempty"`
				Output      float64 `json:"output,omitempty"`
				OutputAudio float64 `json:"outputAudio,omitempty"`
				Reasoning   float64 `json:"reasoning,omitempty"`
			} `json:"tiers,omitempty"`
		} `json:"cost,omitempty"`
		Enabled   bool     `json:"enabled,omitempty"`
		Id        string   `json:"id,omitempty"`
		Input     []string `json:"input,omitempty"`
		MaxTokens int      `json:"maxTokens,omitempty"`
		Name      string   `json:"name,omitempty"`
		Output    []string `json:"output,omitempty"`
		Reasoning *bool    `json:"reasoning,omitempty"`
	} `json:"models,omitempty"`
	Name string `json:"name,omitempty"`
	Type string `json:"type,omitempty"`
}

type SettingsProviderDeleteInput struct {
	ExpectedVersion string `json:"expected_version,omitempty"`
	Id              string `json:"id,omitempty"`
}

type SettingsProviderGetInput struct {
	Id string `json:"id,omitempty"`
}

type SettingsProviderListInput struct {
}

type SettingsProviderUpdateInput struct {
	BaseUrl         string `json:"base_url,omitempty"`
	Enabled         bool   `json:"enabled,omitempty"`
	ExpectedVersion string `json:"expected_version,omitempty"`
	Id              string `json:"id,omitempty"`
	Models          map[string]struct {
		CatalogModel  string `json:"catalogModel,omitempty"`
		ContextWindow int    `json:"contextWindow,omitempty"`
		Cost          struct {
			CacheRead   float64 `json:"cacheRead,omitempty"`
			CacheWrite  float64 `json:"cacheWrite,omitempty"`
			Input       float64 `json:"input,omitempty"`
			InputAudio  float64 `json:"inputAudio,omitempty"`
			Output      float64 `json:"output,omitempty"`
			OutputAudio float64 `json:"outputAudio,omitempty"`
			Reasoning   float64 `json:"reasoning,omitempty"`
			Tiers       []struct {
				CacheRead   float64 `json:"cacheRead,omitempty"`
				CacheWrite  float64 `json:"cacheWrite,omitempty"`
				Input       float64 `json:"input,omitempty"`
				InputAudio  float64 `json:"inputAudio,omitempty"`
				MinContext  int     `json:"minContext,omitempty"`
				Output      float64 `json:"output,omitempty"`
				OutputAudio float64 `json:"outputAudio,omitempty"`
				Reasoning   float64 `json:"reasoning,omitempty"`
			} `json:"tiers,omitempty"`
		} `json:"cost,omitempty"`
		Enabled   bool     `json:"enabled,omitempty"`
		Id        string   `json:"id,omitempty"`
		Input     []string `json:"input,omitempty"`
		MaxTokens int      `json:"maxTokens,omitempty"`
		Name      string   `json:"name,omitempty"`
		Output    []string `json:"output,omitempty"`
		Reasoning *bool    `json:"reasoning,omitempty"`
	} `json:"models,omitempty"`
	Name string `json:"name,omitempty"`
	Type string `json:"type,omitempty"`
}

func SettingsProviderDispatch(ctx context.Context, h SettingsProviderHandler, action string, args map[string]any) (any, error) {
	switch action {
	case "create":
		var in SettingsProviderCreateInput
		if err := tools.DecodeInputStrict(args, &in, []string{"base_url", "enabled", "id", "name", "type"}); err != nil {
			return nil, err
		}
		return h.Create(ctx, in)
	case "delete":
		var in SettingsProviderDeleteInput
		if err := tools.DecodeInputStrict(args, &in, []string{"expected_version", "id"}); err != nil {
			return nil, err
		}
		return h.Delete(ctx, in)
	case "get":
		var in SettingsProviderGetInput
		if err := tools.DecodeInputStrict(args, &in, []string{"id"}); err != nil {
			return nil, err
		}
		return h.Get(ctx, in)
	case "list":
		var in SettingsProviderListInput
		if err := tools.DecodeInputStrict(args, &in, []string(nil)); err != nil {
			return nil, err
		}
		return h.List(ctx, in)
	case "update":
		var in SettingsProviderUpdateInput
		if err := tools.DecodeInputStrict(args, &in, []string{"base_url", "enabled", "expected_version", "id", "name", "type"}); err != nil {
			return nil, err
		}
		return h.Update(ctx, in)
	default:
		return nil, fmt.Errorf("unknown settings_provider action %q", action)
	}
}
