// Code generated by go run ./internal/cmd/toolgen; DO NOT EDIT.

package workflow

import (
	"context"
	"fmt"

	"github.com/CherryHQ/stella/pkg/tools"
)

const ToolName = "workflow"

func InputSchema() map[string]any {
	return tools.MustInputSchema(InputSchemaJSON)
}

const InputSchemaJSON = `{
  "oneOf": [
    {
      "properties": {
        "action": {
          "const": "get",
          "type": "string"
        },
        "id": {
          "type": "string"
        }
      },
      "required": [
        "action",
        "id"
      ],
      "type": "object"
    },
    {
      "properties": {
        "action": {
          "const": "list",
          "type": "string"
        }
      },
      "required": [
        "action"
      ],
      "type": "object"
    },
    {
      "properties": {
        "action": {
          "const": "run",
          "type": "string"
        },
        "id": {
          "type": "string"
        },
        "idempotency_key": {
          "description": "Optional idempotency key. When omitted, the server generates a UUID, so retries must provide their own key to be idempotent.",
          "type": "string"
        },
        "inputs": {
          "additionalProperties": {
            "type": "string"
          },
          "type": "object"
        }
      },
      "required": [
        "action",
        "id"
      ],
      "type": "object"
    },
    {
      "properties": {
        "action": {
          "const": "save",
          "type": "string"
        },
        "id": {
          "type": "string"
        },
        "inputs": {
          "items": {
            "properties": {
              "default": {
                "description": "Default value used when the caller omits this input.",
                "type": "string"
              },
              "description": {
                "type": "string"
              },
              "name": {
                "description": "Input placeholder name used as {{inputs.name}}.",
                "type": "string"
              },
              "required": {
                "default": false,
                "type": "boolean"
              }
            },
            "required": [
              "name"
            ],
            "type": "object"
          },
          "type": "array"
        },
        "name": {
          "type": "string"
        }
      },
      "required": [
        "action",
        "id",
        "name"
      ],
      "type": "object"
    }
  ],
  "properties": {
    "action": {
      "enum": [
        "get",
        "list",
        "run",
        "save"
      ],
      "type": "string"
    }
  },
  "required": [
    "action"
  ],
  "type": "object"
}`

type Handler interface {
	Get(context.Context, GetInput) (any, error)
	List(context.Context, ListInput) (any, error)
	Run(context.Context, RunInput) (any, error)
	Save(context.Context, ToolSaveInput) (any, error)
}

type GetInput struct {
	Id string `json:"id,omitempty"`
}

type ListInput struct {
}

type RunInput struct {
	Id             string         `json:"id,omitempty"`
	IdempotencyKey string         `json:"idempotency_key,omitempty"`
	Inputs         map[string]any `json:"inputs,omitempty"`
}

type ToolSaveInput struct {
	Id     string `json:"id,omitempty"`
	Inputs []any  `json:"inputs,omitempty"`
	Name   string `json:"name,omitempty"`
}

func Dispatch(ctx context.Context, h Handler, action string, args map[string]any) (any, error) {
	switch action {
	case "get":
		var in GetInput
		if err := tools.DecodeInput(args, &in, []string{"id"}); err != nil {
			return nil, err
		}
		return h.Get(ctx, in)
	case "list":
		var in ListInput
		if err := tools.DecodeInput(args, &in, []string(nil)); err != nil {
			return nil, err
		}
		return h.List(ctx, in)
	case "run":
		var in RunInput
		if err := tools.DecodeInput(args, &in, []string{"id"}); err != nil {
			return nil, err
		}
		return h.Run(ctx, in)
	case "save":
		var in ToolSaveInput
		if err := tools.DecodeInput(args, &in, []string{"id", "name"}); err != nil {
			return nil, err
		}
		return h.Save(ctx, in)
	default:
		return nil, fmt.Errorf("unknown workflow action %q", action)
	}
}
