// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: feishu_tokens.sql

package sqlc

import (
	"context"
)

const deleteFeishuToken = `-- name: DeleteFeishuToken :exec
DELETE FROM feishu_tokens WHERE open_id = ?
`

func (q *Queries) DeleteFeishuToken(ctx context.Context, openID string) error {
	_, err := q.db.ExecContext(ctx, deleteFeishuToken, openID)
	return err
}

const getFeishuToken = `-- name: GetFeishuToken :one
SELECT open_id, access_token, refresh_token, expires_at, refresh_expires_at, created_at, updated_at FROM feishu_tokens WHERE open_id = ?
`

func (q *Queries) GetFeishuToken(ctx context.Context, openID string) (FeishuToken, error) {
	row := q.db.QueryRowContext(ctx, getFeishuToken, openID)
	var i FeishuToken
	err := row.Scan(
		&i.OpenID,
		&i.AccessToken,
		&i.RefreshToken,
		&i.ExpiresAt,
		&i.RefreshExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertFeishuToken = `-- name: UpsertFeishuToken :exec
INSERT INTO feishu_tokens (open_id, access_token, refresh_token, expires_at, refresh_expires_at)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT(open_id) DO UPDATE SET
    access_token = excluded.access_token,
    refresh_token = excluded.refresh_token,
    expires_at = excluded.expires_at,
    refresh_expires_at = excluded.refresh_expires_at,
    updated_at = datetime('now')
`

type UpsertFeishuTokenParams struct {
	OpenID           string `json:"open_id"`
	AccessToken      string `json:"access_token"`
	RefreshToken     string `json:"refresh_token"`
	ExpiresAt        string `json:"expires_at"`
	RefreshExpiresAt string `json:"refresh_expires_at"`
}

func (q *Queries) UpsertFeishuToken(ctx context.Context, arg UpsertFeishuTokenParams) error {
	_, err := q.db.ExecContext(ctx, upsertFeishuToken,
		arg.OpenID,
		arg.AccessToken,
		arg.RefreshToken,
		arg.ExpiresAt,
		arg.RefreshExpiresAt,
	)
	return err
}
