// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: agent_goal.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createAgentGoal = `-- name: CreateAgentGoal :one

INSERT INTO agent_goal (
    id, org_id, user_id, agent_id, title, description, status, priority,
    review_policy, context, output, created_at, updated_at
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, org_id, user_id, agent_id, title, description, status, priority, review_policy, active_review_id, context, output, created_at, updated_at, completed_at, cancelled_at
`

type CreateAgentGoalParams struct {
	ID           string         `json:"id"`
	OrgID        string         `json:"org_id"`
	UserID       string         `json:"user_id"`
	AgentID      sql.NullString `json:"agent_id"`
	Title        string         `json:"title"`
	Description  string         `json:"description"`
	Status       string         `json:"status"`
	Priority     string         `json:"priority"`
	ReviewPolicy string         `json:"review_policy"`
	Context      string         `json:"context"`
	Output       string         `json:"output"`
	CreatedAt    string         `json:"created_at"`
	UpdatedAt    string         `json:"updated_at"`
}

// Slice 3: goal queries.
func (q *Queries) CreateAgentGoal(ctx context.Context, arg CreateAgentGoalParams) (AgentGoal, error) {
	row := q.db.QueryRowContext(ctx, createAgentGoal,
		arg.ID,
		arg.OrgID,
		arg.UserID,
		arg.AgentID,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.Priority,
		arg.ReviewPolicy,
		arg.Context,
		arg.Output,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i AgentGoal
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.UserID,
		&i.AgentID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.ReviewPolicy,
		&i.ActiveReviewID,
		&i.Context,
		&i.Output,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.CancelledAt,
	)
	return i, err
}

const getAgentGoal = `-- name: GetAgentGoal :one
SELECT id, org_id, user_id, agent_id, title, description, status, priority, review_policy, active_review_id, context, output, created_at, updated_at, completed_at, cancelled_at FROM agent_goal WHERE id = ?
`

func (q *Queries) GetAgentGoal(ctx context.Context, id string) (AgentGoal, error) {
	row := q.db.QueryRowContext(ctx, getAgentGoal, id)
	var i AgentGoal
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.UserID,
		&i.AgentID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.ReviewPolicy,
		&i.ActiveReviewID,
		&i.Context,
		&i.Output,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.CancelledAt,
	)
	return i, err
}

const goalChildCounts = `-- name: GoalChildCounts :one
SELECT
    COUNT(*)                                                    AS total,
    SUM(CASE WHEN required = 1 AND status = 'done'      THEN 1 ELSE 0 END) AS required_done,
    SUM(CASE WHEN required = 1 AND status = 'failed'    THEN 1 ELSE 0 END) AS required_failed,
    SUM(CASE WHEN required = 1 AND status = 'cancelled' THEN 1 ELSE 0 END) AS required_cancelled,
    SUM(CASE WHEN required = 1 AND status = 'blocked'   THEN 1 ELSE 0 END) AS required_blocked,
    SUM(CASE WHEN required = 1 AND status IN ('done','failed','cancelled') THEN 0 ELSE 1 END) AS required_pending
FROM agent_task
WHERE goal_id = ?
`

type GoalChildCountsRow struct {
	Total             int64           `json:"total"`
	RequiredDone      sql.NullFloat64 `json:"required_done"`
	RequiredFailed    sql.NullFloat64 `json:"required_failed"`
	RequiredCancelled sql.NullFloat64 `json:"required_cancelled"`
	RequiredBlocked   sql.NullFloat64 `json:"required_blocked"`
	RequiredPending   sql.NullFloat64 `json:"required_pending"`
}

// Aggregate counts of children by required_flag + status for rollup logic.
func (q *Queries) GoalChildCounts(ctx context.Context, goalID sql.NullString) (GoalChildCountsRow, error) {
	row := q.db.QueryRowContext(ctx, goalChildCounts, goalID)
	var i GoalChildCountsRow
	err := row.Scan(
		&i.Total,
		&i.RequiredDone,
		&i.RequiredFailed,
		&i.RequiredCancelled,
		&i.RequiredBlocked,
		&i.RequiredPending,
	)
	return i, err
}

const listAgentGoalsByOrg = `-- name: ListAgentGoalsByOrg :many
SELECT id, org_id, user_id, agent_id, title, description, status, priority, review_policy, active_review_id, context, output, created_at, updated_at, completed_at, cancelled_at FROM agent_goal WHERE org_id = ? ORDER BY created_at DESC LIMIT ? OFFSET ?
`

type ListAgentGoalsByOrgParams struct {
	OrgID  string `json:"org_id"`
	Limit  int64  `json:"limit"`
	Offset int64  `json:"offset"`
}

func (q *Queries) ListAgentGoalsByOrg(ctx context.Context, arg ListAgentGoalsByOrgParams) ([]AgentGoal, error) {
	rows, err := q.db.QueryContext(ctx, listAgentGoalsByOrg, arg.OrgID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentGoal{}
	for rows.Next() {
		var i AgentGoal
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.UserID,
			&i.AgentID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.ReviewPolicy,
			&i.ActiveReviewID,
			&i.Context,
			&i.Output,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
			&i.CancelledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChildrenByGoal = `-- name: ListChildrenByGoal :many
SELECT id, org_id, user_id, agent_id, goal_id, title, description, status, priority, review_policy, active_review_id, required, retry_count, max_retries, not_before, deadline_at, session_id, active_run_id, active_blocker_id, context, output, created_at, updated_at, completed_at, cancelled_at FROM agent_task WHERE goal_id = ? ORDER BY created_at ASC
`

func (q *Queries) ListChildrenByGoal(ctx context.Context, goalID sql.NullString) ([]AgentTask, error) {
	rows, err := q.db.QueryContext(ctx, listChildrenByGoal, goalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentTask{}
	for rows.Next() {
		var i AgentTask
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.UserID,
			&i.AgentID,
			&i.GoalID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.ReviewPolicy,
			&i.ActiveReviewID,
			&i.Required,
			&i.RetryCount,
			&i.MaxRetries,
			&i.NotBefore,
			&i.DeadlineAt,
			&i.SessionID,
			&i.ActiveRunID,
			&i.ActiveBlockerID,
			&i.Context,
			&i.Output,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
			&i.CancelledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGoalPlanningCandidates = `-- name: ListGoalPlanningCandidates :many
SELECT id, org_id, user_id, agent_id, title, description, status, priority, review_policy, active_review_id, context, output, created_at, updated_at, completed_at, cancelled_at FROM agent_goal
WHERE status = 'draft'
ORDER BY priority DESC, created_at ASC
LIMIT ?
`

func (q *Queries) ListGoalPlanningCandidates(ctx context.Context, limit int64) ([]AgentGoal, error) {
	rows, err := q.db.QueryContext(ctx, listGoalPlanningCandidates, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentGoal{}
	for rows.Next() {
		var i AgentGoal
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.UserID,
			&i.AgentID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.ReviewPolicy,
			&i.ActiveReviewID,
			&i.Context,
			&i.Output,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
			&i.CancelledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGoalSynthesisCandidates = `-- name: ListGoalSynthesisCandidates :many
SELECT id, org_id, user_id, agent_id, title, description, status, priority, review_policy, active_review_id, context, output, created_at, updated_at, completed_at, cancelled_at FROM agent_goal
WHERE status = 'running' AND review_policy != 'none'
ORDER BY priority DESC, updated_at ASC
LIMIT ?
`

func (q *Queries) ListGoalSynthesisCandidates(ctx context.Context, limit int64) ([]AgentGoal, error) {
	rows, err := q.db.QueryContext(ctx, listGoalSynthesisCandidates, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentGoal{}
	for rows.Next() {
		var i AgentGoal
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.UserID,
			&i.AgentID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.ReviewPolicy,
			&i.ActiveReviewID,
			&i.Context,
			&i.Output,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
			&i.CancelledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setAgentGoalActiveReview = `-- name: SetAgentGoalActiveReview :exec
UPDATE agent_goal SET active_review_id = ?, updated_at = ? WHERE id = ?
`

type SetAgentGoalActiveReviewParams struct {
	ActiveReviewID sql.NullString `json:"active_review_id"`
	UpdatedAt      string         `json:"updated_at"`
	ID             string         `json:"id"`
}

func (q *Queries) SetAgentGoalActiveReview(ctx context.Context, arg SetAgentGoalActiveReviewParams) error {
	_, err := q.db.ExecContext(ctx, setAgentGoalActiveReview, arg.ActiveReviewID, arg.UpdatedAt, arg.ID)
	return err
}

const setAgentGoalOutput = `-- name: SetAgentGoalOutput :exec
UPDATE agent_goal SET output = ?, completed_at = ?, updated_at = ? WHERE id = ?
`

type SetAgentGoalOutputParams struct {
	Output      string         `json:"output"`
	CompletedAt sql.NullString `json:"completed_at"`
	UpdatedAt   string         `json:"updated_at"`
	ID          string         `json:"id"`
}

func (q *Queries) SetAgentGoalOutput(ctx context.Context, arg SetAgentGoalOutputParams) error {
	_, err := q.db.ExecContext(ctx, setAgentGoalOutput,
		arg.Output,
		arg.CompletedAt,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const transitionAgentGoalStatus = `-- name: TransitionAgentGoalStatus :execrows
UPDATE agent_goal
SET status = ?, updated_at = ?
WHERE id = ? AND status = ?
`

type TransitionAgentGoalStatusParams struct {
	Status    string `json:"status"`
	UpdatedAt string `json:"updated_at"`
	ID        string `json:"id"`
	Status_2  string `json:"status_2"`
}

func (q *Queries) TransitionAgentGoalStatus(ctx context.Context, arg TransitionAgentGoalStatusParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, transitionAgentGoalStatus,
		arg.Status,
		arg.UpdatedAt,
		arg.ID,
		arg.Status_2,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
