// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: agent_dlv_attempt.sql

package sqlc

import (
	"context"
	"database/sql"
)

const countInflightAttemptsByRoot = `-- name: CountInflightAttemptsByRoot :one
SELECT CAST(COUNT(*) AS INTEGER)
FROM agent_dlv_attempt a
JOIN agent_dlv_deliverable d ON d.id = a.deliverable_id
WHERE d.root_id = ?1
  AND a.status IN ('queued', 'running')
`

func (q *Queries) CountInflightAttemptsByRoot(ctx context.Context, rootID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countInflightAttemptsByRoot, rootID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countInflightAttemptsByUser = `-- name: CountInflightAttemptsByUser :one
SELECT CAST(COUNT(*) AS INTEGER)
FROM agent_dlv_attempt a
WHERE a.user_id = ?1
  AND a.status IN ('queued', 'running')
`

func (q *Queries) CountInflightAttemptsByUser(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countInflightAttemptsByUser, userID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createAttempt = `-- name: CreateAttempt :one
INSERT INTO agent_dlv_attempt (
    id, deliverable_id, user_id, agent_id, executor_agent_id, session_id,
    purpose, attempt_no, status, input_context, lease_expires_at
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, deliverable_id, user_id, agent_id, executor_agent_id, session_id, purpose, attempt_no, status, input_context, evidence, output, revision_id, gaps, error, heartbeat_at, lease_expires_at, worker_id, started_at, finished_at, created_at, updated_at
`

type CreateAttemptParams struct {
	ID              string         `json:"id"`
	DeliverableID   string         `json:"deliverable_id"`
	UserID          string         `json:"user_id"`
	AgentID         sql.NullString `json:"agent_id"`
	ExecutorAgentID sql.NullString `json:"executor_agent_id"`
	SessionID       string         `json:"session_id"`
	Purpose         string         `json:"purpose"`
	AttemptNo       int64          `json:"attempt_no"`
	Status          string         `json:"status"`
	InputContext    string         `json:"input_context"`
	LeaseExpiresAt  sql.NullString `json:"lease_expires_at"`
}

func (q *Queries) CreateAttempt(ctx context.Context, arg CreateAttemptParams) (AgentDlvAttempt, error) {
	row := q.db.QueryRowContext(ctx, createAttempt,
		arg.ID,
		arg.DeliverableID,
		arg.UserID,
		arg.AgentID,
		arg.ExecutorAgentID,
		arg.SessionID,
		arg.Purpose,
		arg.AttemptNo,
		arg.Status,
		arg.InputContext,
		arg.LeaseExpiresAt,
	)
	var i AgentDlvAttempt
	err := row.Scan(
		&i.ID,
		&i.DeliverableID,
		&i.UserID,
		&i.AgentID,
		&i.ExecutorAgentID,
		&i.SessionID,
		&i.Purpose,
		&i.AttemptNo,
		&i.Status,
		&i.InputContext,
		&i.Evidence,
		&i.Output,
		&i.RevisionID,
		&i.Gaps,
		&i.Error,
		&i.HeartbeatAt,
		&i.LeaseExpiresAt,
		&i.WorkerID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const finalizeAttempt = `-- name: FinalizeAttempt :execrows
UPDATE agent_dlv_attempt
SET status = ?1,
    error = ?2,
    finished_at = datetime('now'),
    updated_at = datetime('now')
WHERE id = ?3 AND status IN ('queued', 'running')
`

type FinalizeAttemptParams struct {
	ToStatus string `json:"to_status"`
	Error    string `json:"error"`
	ID       string `json:"id"`
}

func (q *Queries) FinalizeAttempt(ctx context.Context, arg FinalizeAttemptParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, finalizeAttempt, arg.ToStatus, arg.Error, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getActiveAttempt = `-- name: GetActiveAttempt :one
SELECT id, deliverable_id, user_id, agent_id, executor_agent_id, session_id, purpose, attempt_no, status, input_context, evidence, output, revision_id, gaps, error, heartbeat_at, lease_expires_at, worker_id, started_at, finished_at, created_at, updated_at FROM agent_dlv_attempt
WHERE deliverable_id = ?1
  AND purpose = ?2
  AND status IN ('queued', 'running')
`

type GetActiveAttemptParams struct {
	DeliverableID string `json:"deliverable_id"`
	Purpose       string `json:"purpose"`
}

func (q *Queries) GetActiveAttempt(ctx context.Context, arg GetActiveAttemptParams) (AgentDlvAttempt, error) {
	row := q.db.QueryRowContext(ctx, getActiveAttempt, arg.DeliverableID, arg.Purpose)
	var i AgentDlvAttempt
	err := row.Scan(
		&i.ID,
		&i.DeliverableID,
		&i.UserID,
		&i.AgentID,
		&i.ExecutorAgentID,
		&i.SessionID,
		&i.Purpose,
		&i.AttemptNo,
		&i.Status,
		&i.InputContext,
		&i.Evidence,
		&i.Output,
		&i.RevisionID,
		&i.Gaps,
		&i.Error,
		&i.HeartbeatAt,
		&i.LeaseExpiresAt,
		&i.WorkerID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAttempt = `-- name: GetAttempt :one
SELECT id, deliverable_id, user_id, agent_id, executor_agent_id, session_id, purpose, attempt_no, status, input_context, evidence, output, revision_id, gaps, error, heartbeat_at, lease_expires_at, worker_id, started_at, finished_at, created_at, updated_at FROM agent_dlv_attempt WHERE id = ?
`

func (q *Queries) GetAttempt(ctx context.Context, id string) (AgentDlvAttempt, error) {
	row := q.db.QueryRowContext(ctx, getAttempt, id)
	var i AgentDlvAttempt
	err := row.Scan(
		&i.ID,
		&i.DeliverableID,
		&i.UserID,
		&i.AgentID,
		&i.ExecutorAgentID,
		&i.SessionID,
		&i.Purpose,
		&i.AttemptNo,
		&i.Status,
		&i.InputContext,
		&i.Evidence,
		&i.Output,
		&i.RevisionID,
		&i.Gaps,
		&i.Error,
		&i.HeartbeatAt,
		&i.LeaseExpiresAt,
		&i.WorkerID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const heartbeatAttempt = `-- name: HeartbeatAttempt :execrows
UPDATE agent_dlv_attempt
SET heartbeat_at = datetime('now'),
    lease_expires_at = ?1,
    updated_at = datetime('now')
WHERE id = ?2 AND status = 'running'
`

type HeartbeatAttemptParams struct {
	LeaseExpiresAt sql.NullString `json:"lease_expires_at"`
	ID             string         `json:"id"`
}

func (q *Queries) HeartbeatAttempt(ctx context.Context, arg HeartbeatAttemptParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, heartbeatAttempt, arg.LeaseExpiresAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listAttemptByDeliverable = `-- name: ListAttemptByDeliverable :many
SELECT id, deliverable_id, user_id, agent_id, executor_agent_id, session_id, purpose, attempt_no, status, input_context, evidence, output, revision_id, gaps, error, heartbeat_at, lease_expires_at, worker_id, started_at, finished_at, created_at, updated_at FROM agent_dlv_attempt
WHERE deliverable_id = ?1
  AND (?2 IS NULL OR purpose = ?2)
ORDER BY attempt_no DESC
`

type ListAttemptByDeliverableParams struct {
	DeliverableID string      `json:"deliverable_id"`
	Purpose       interface{} `json:"purpose"`
}

func (q *Queries) ListAttemptByDeliverable(ctx context.Context, arg ListAttemptByDeliverableParams) ([]AgentDlvAttempt, error) {
	rows, err := q.db.QueryContext(ctx, listAttemptByDeliverable, arg.DeliverableID, arg.Purpose)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentDlvAttempt{}
	for rows.Next() {
		var i AgentDlvAttempt
		if err := rows.Scan(
			&i.ID,
			&i.DeliverableID,
			&i.UserID,
			&i.AgentID,
			&i.ExecutorAgentID,
			&i.SessionID,
			&i.Purpose,
			&i.AttemptNo,
			&i.Status,
			&i.InputContext,
			&i.Evidence,
			&i.Output,
			&i.RevisionID,
			&i.Gaps,
			&i.Error,
			&i.HeartbeatAt,
			&i.LeaseExpiresAt,
			&i.WorkerID,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaleAttempts = `-- name: ListStaleAttempts :many
SELECT id, deliverable_id, user_id, agent_id, executor_agent_id, session_id, purpose, attempt_no, status, input_context, evidence, output, revision_id, gaps, error, heartbeat_at, lease_expires_at, worker_id, started_at, finished_at, created_at, updated_at FROM agent_dlv_attempt
WHERE status IN ('queued', 'running')
  AND lease_expires_at IS NOT NULL
  AND lease_expires_at < ?1
ORDER BY lease_expires_at ASC
LIMIT ?2
`

type ListStaleAttemptsParams struct {
	Now   sql.NullString `json:"now"`
	Limit int64          `json:"limit"`
}

func (q *Queries) ListStaleAttempts(ctx context.Context, arg ListStaleAttemptsParams) ([]AgentDlvAttempt, error) {
	rows, err := q.db.QueryContext(ctx, listStaleAttempts, arg.Now, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentDlvAttempt{}
	for rows.Next() {
		var i AgentDlvAttempt
		if err := rows.Scan(
			&i.ID,
			&i.DeliverableID,
			&i.UserID,
			&i.AgentID,
			&i.ExecutorAgentID,
			&i.SessionID,
			&i.Purpose,
			&i.AttemptNo,
			&i.Status,
			&i.InputContext,
			&i.Evidence,
			&i.Output,
			&i.RevisionID,
			&i.Gaps,
			&i.Error,
			&i.HeartbeatAt,
			&i.LeaseExpiresAt,
			&i.WorkerID,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const promoteAttempt = `-- name: PromoteAttempt :execrows
UPDATE agent_dlv_attempt
SET status = 'running',
    started_at = datetime('now'),
    heartbeat_at = datetime('now'),
    lease_expires_at = ?1,
    updated_at = datetime('now')
WHERE id = ?2 AND status = 'queued'
`

type PromoteAttemptParams struct {
	LeaseExpiresAt sql.NullString `json:"lease_expires_at"`
	ID             string         `json:"id"`
}

func (q *Queries) PromoteAttempt(ctx context.Context, arg PromoteAttemptParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, promoteAttempt, arg.LeaseExpiresAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setAttemptExecutor = `-- name: SetAttemptExecutor :exec
UPDATE agent_dlv_attempt
SET executor_agent_id = ?1, updated_at = datetime('now')
WHERE id = ?2
`

type SetAttemptExecutorParams struct {
	ExecutorAgentID sql.NullString `json:"executor_agent_id"`
	ID              string         `json:"id"`
}

func (q *Queries) SetAttemptExecutor(ctx context.Context, arg SetAttemptExecutorParams) error {
	_, err := q.db.ExecContext(ctx, setAttemptExecutor, arg.ExecutorAgentID, arg.ID)
	return err
}

const setAttemptGaps = `-- name: SetAttemptGaps :exec
UPDATE agent_dlv_attempt
SET gaps = ?1, updated_at = datetime('now')
WHERE id = ?2
`

type SetAttemptGapsParams struct {
	Gaps string `json:"gaps"`
	ID   string `json:"id"`
}

func (q *Queries) SetAttemptGaps(ctx context.Context, arg SetAttemptGapsParams) error {
	_, err := q.db.ExecContext(ctx, setAttemptGaps, arg.Gaps, arg.ID)
	return err
}

const submitAttempt = `-- name: SubmitAttempt :execrows
UPDATE agent_dlv_attempt
SET status = 'submitted',
    evidence = ?1,
    output = ?2,
    revision_id = ?3,
    finished_at = datetime('now'),
    updated_at = datetime('now')
WHERE id = ?4 AND status = 'running'
`

type SubmitAttemptParams struct {
	Evidence   string         `json:"evidence"`
	Output     string         `json:"output"`
	RevisionID sql.NullString `json:"revision_id"`
	ID         string         `json:"id"`
}

func (q *Queries) SubmitAttempt(ctx context.Context, arg SubmitAttemptParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, submitAttempt,
		arg.Evidence,
		arg.Output,
		arg.RevisionID,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
