// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: agent_goal.sql

package sqlc

import (
	"context"
	"database/sql"
)

const archiveAgentGoal = `-- name: ArchiveAgentGoal :execrows
UPDATE agent_goal SET archived_at = ?, updated_at = ? WHERE id = ? AND archived_at IS NULL
`

type ArchiveAgentGoalParams struct {
	ArchivedAt sql.NullString `json:"archived_at"`
	UpdatedAt  string         `json:"updated_at"`
	ID         string         `json:"id"`
}

func (q *Queries) ArchiveAgentGoal(ctx context.Context, arg ArchiveAgentGoalParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, archiveAgentGoal, arg.ArchivedAt, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const countAgentGoalsByUser = `-- name: CountAgentGoalsByUser :one
SELECT COUNT(*) FROM agent_goal
WHERE user_id = ?1
  AND (
    (?2 = 1 AND archived_at IS NOT NULL)
    OR (?2 IS NULL AND archived_at IS NULL)
    OR (?2 = 0 AND archived_at IS NULL)
  )
  AND (?3 IS NULL OR agent_id = ?3)
  AND (?4 IS NULL OR status = ?4)
  AND (?5 IS NULL OR project_id = ?5)
  AND (
    ?6 IS NULL
    OR (?6 = 1 AND status IN ('done', 'failed', 'cancelled'))
    OR (?6 = 0 AND status NOT IN ('done', 'failed', 'cancelled'))
  )
  AND (
    ?7 IS NULL
    OR instr(lower(title), lower(?7)) > 0
    OR instr(lower(description), lower(?7)) > 0
  )
`

type CountAgentGoalsByUserParams struct {
	UserID    string      `json:"user_id"`
	Archived  interface{} `json:"archived"`
	AgentID   interface{} `json:"agent_id"`
	Status    interface{} `json:"status"`
	ProjectID interface{} `json:"project_id"`
	Terminal  interface{} `json:"terminal"`
	Search    interface{} `json:"search"`
}

// CountAgentGoalsByUser returns the total rows matching the same filters as
// ListAgentGoalsByUser (ignoring pagination), so the UI can render numbered
// pages and per-mode count badges from server-side state.
func (q *Queries) CountAgentGoalsByUser(ctx context.Context, arg CountAgentGoalsByUserParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAgentGoalsByUser,
		arg.UserID,
		arg.Archived,
		arg.AgentID,
		arg.Status,
		arg.ProjectID,
		arg.Terminal,
		arg.Search,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAgentGoal = `-- name: CreateAgentGoal :one

INSERT INTO agent_goal (
    id, user_id, agent_id, project_id, title, description, status, priority,
    review_policy, context, output, created_at, updated_at
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, user_id, agent_id, project_id, title, description, status, priority, review_policy, active_review_id, context, output, created_at, updated_at, completed_at, cancelled_at, archived_at
`

type CreateAgentGoalParams struct {
	ID           string         `json:"id"`
	UserID       string         `json:"user_id"`
	AgentID      string         `json:"agent_id"`
	ProjectID    sql.NullString `json:"project_id"`
	Title        string         `json:"title"`
	Description  string         `json:"description"`
	Status       string         `json:"status"`
	Priority     string         `json:"priority"`
	ReviewPolicy string         `json:"review_policy"`
	Context      string         `json:"context"`
	Output       string         `json:"output"`
	CreatedAt    string         `json:"created_at"`
	UpdatedAt    string         `json:"updated_at"`
}

// Slice 3: goal queries.
func (q *Queries) CreateAgentGoal(ctx context.Context, arg CreateAgentGoalParams) (AgentGoal, error) {
	row := q.db.QueryRowContext(ctx, createAgentGoal,
		arg.ID,
		arg.UserID,
		arg.AgentID,
		arg.ProjectID,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.Priority,
		arg.ReviewPolicy,
		arg.Context,
		arg.Output,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i AgentGoal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AgentID,
		&i.ProjectID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.ReviewPolicy,
		&i.ActiveReviewID,
		&i.Context,
		&i.Output,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.CancelledAt,
		&i.ArchivedAt,
	)
	return i, err
}

const getAgentGoal = `-- name: GetAgentGoal :one
SELECT id, user_id, agent_id, project_id, title, description, status, priority, review_policy, active_review_id, context, output, created_at, updated_at, completed_at, cancelled_at, archived_at FROM agent_goal WHERE id = ?
`

func (q *Queries) GetAgentGoal(ctx context.Context, id string) (AgentGoal, error) {
	row := q.db.QueryRowContext(ctx, getAgentGoal, id)
	var i AgentGoal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AgentID,
		&i.ProjectID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.ReviewPolicy,
		&i.ActiveReviewID,
		&i.Context,
		&i.Output,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.CancelledAt,
		&i.ArchivedAt,
	)
	return i, err
}

const goalChildCounts = `-- name: GoalChildCounts :one
SELECT
    COUNT(*)                                                    AS total,
    SUM(CASE WHEN required = 1 AND status = 'done'      THEN 1 ELSE 0 END) AS required_done,
    SUM(CASE WHEN required = 1 AND status = 'failed'    THEN 1 ELSE 0 END) AS required_failed,
    SUM(CASE WHEN required = 1 AND status = 'cancelled' THEN 1 ELSE 0 END) AS required_cancelled,
    SUM(CASE WHEN required = 1 AND status = 'blocked'   THEN 1 ELSE 0 END) AS required_blocked,
    SUM(CASE WHEN required = 1 AND status NOT IN ('done','failed','cancelled') THEN 1 ELSE 0 END) AS required_pending
FROM agent_task
WHERE goal_id = ?
`

type GoalChildCountsRow struct {
	Total             int64           `json:"total"`
	RequiredDone      sql.NullFloat64 `json:"required_done"`
	RequiredFailed    sql.NullFloat64 `json:"required_failed"`
	RequiredCancelled sql.NullFloat64 `json:"required_cancelled"`
	RequiredBlocked   sql.NullFloat64 `json:"required_blocked"`
	RequiredPending   sql.NullFloat64 `json:"required_pending"`
}

// Aggregate counts of children by required_flag + status for rollup logic.
func (q *Queries) GoalChildCounts(ctx context.Context, goalID sql.NullString) (GoalChildCountsRow, error) {
	row := q.db.QueryRowContext(ctx, goalChildCounts, goalID)
	var i GoalChildCountsRow
	err := row.Scan(
		&i.Total,
		&i.RequiredDone,
		&i.RequiredFailed,
		&i.RequiredCancelled,
		&i.RequiredBlocked,
		&i.RequiredPending,
	)
	return i, err
}

const listAgentGoals = `-- name: ListAgentGoals :many
SELECT id, user_id, agent_id, project_id, title, description, status, priority, review_policy, active_review_id, context, output, created_at, updated_at, completed_at, cancelled_at, archived_at FROM agent_goal
WHERE status NOT IN ('done', 'cancelled')
  AND archived_at IS NULL
ORDER BY created_at DESC, id DESC LIMIT ? OFFSET ?
`

type ListAgentGoalsParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

// Dispatcher rollup scan. Skip quiescent goals (done/cancelled) so the bounded
// window is spent only on goals rollup can still act on (running/blocked/failed
// and pre-run states). failed is intentionally included - it is recoverable.
// Archived goals are inert: excluding them stops rollup from silently recovering
// an archived failed goal back to running while it stays hidden from default lists.
func (q *Queries) ListAgentGoals(ctx context.Context, arg ListAgentGoalsParams) ([]AgentGoal, error) {
	rows, err := q.db.QueryContext(ctx, listAgentGoals, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentGoal{}
	for rows.Next() {
		var i AgentGoal
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AgentID,
			&i.ProjectID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.ReviewPolicy,
			&i.ActiveReviewID,
			&i.Context,
			&i.Output,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
			&i.CancelledAt,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentGoalsByUser = `-- name: ListAgentGoalsByUser :many
SELECT id, user_id, agent_id, project_id, title, description, status, priority, review_policy, active_review_id, context, output, created_at, updated_at, completed_at, cancelled_at, archived_at FROM agent_goal
WHERE user_id = ?1
  AND (
    (?2 = 1 AND archived_at IS NOT NULL)
    OR (?2 IS NULL AND archived_at IS NULL)
    OR (?2 = 0 AND archived_at IS NULL)
  )
  AND (?3 IS NULL OR agent_id = ?3)
  AND (?4 IS NULL OR status = ?4)
  AND (?5 IS NULL OR project_id = ?5)
  AND (
    ?6 IS NULL
    OR (?6 = 1 AND status IN ('done', 'failed', 'cancelled'))
    OR (?6 = 0 AND status NOT IN ('done', 'failed', 'cancelled'))
  )
  AND (
    ?7 IS NULL
    OR instr(lower(title), lower(?7)) > 0
    OR instr(lower(description), lower(?7)) > 0
  )
ORDER BY created_at DESC, id DESC
LIMIT ?9 OFFSET ?8
`

type ListAgentGoalsByUserParams struct {
	UserID    string      `json:"user_id"`
	Archived  interface{} `json:"archived"`
	AgentID   interface{} `json:"agent_id"`
	Status    interface{} `json:"status"`
	ProjectID interface{} `json:"project_id"`
	Terminal  interface{} `json:"terminal"`
	Search    interface{} `json:"search"`
	Offset    int64       `json:"offset"`
	Limit     int64       `json:"limit"`
}

// archived narg: NULL/false yields only active rows (archived_at IS NULL, the
// default); true yields only archived rows (the history/restore view).
// terminal narg: NULL matches any status; 1 keeps only terminal goals
// (done/failed/cancelled, the history view); 0 keeps only non-terminal goals
// (the active view). search narg is a case-insensitive substring matched against
// title and description (NULL matches all).
func (q *Queries) ListAgentGoalsByUser(ctx context.Context, arg ListAgentGoalsByUserParams) ([]AgentGoal, error) {
	rows, err := q.db.QueryContext(ctx, listAgentGoalsByUser,
		arg.UserID,
		arg.Archived,
		arg.AgentID,
		arg.Status,
		arg.ProjectID,
		arg.Terminal,
		arg.Search,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentGoal{}
	for rows.Next() {
		var i AgentGoal
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AgentID,
			&i.ProjectID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.ReviewPolicy,
			&i.ActiveReviewID,
			&i.Context,
			&i.Output,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
			&i.CancelledAt,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChildrenByGoal = `-- name: ListChildrenByGoal :many
SELECT id, user_id, agent_id, session_id, goal_id, project_id, source_plan_id, plan_item_id, detached_at, title, description, status, priority, review_policy, active_review_id, required, retry_count, max_retries, not_before, deadline_at, active_run_id, active_blocker_id, context, output, created_at, updated_at, completed_at, cancelled_at, archived_at FROM agent_task WHERE goal_id = ? ORDER BY created_at ASC
`

func (q *Queries) ListChildrenByGoal(ctx context.Context, goalID sql.NullString) ([]AgentTask, error) {
	rows, err := q.db.QueryContext(ctx, listChildrenByGoal, goalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentTask{}
	for rows.Next() {
		var i AgentTask
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AgentID,
			&i.SessionID,
			&i.GoalID,
			&i.ProjectID,
			&i.SourcePlanID,
			&i.PlanItemID,
			&i.DetachedAt,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.ReviewPolicy,
			&i.ActiveReviewID,
			&i.Required,
			&i.RetryCount,
			&i.MaxRetries,
			&i.NotBefore,
			&i.DeadlineAt,
			&i.ActiveRunID,
			&i.ActiveBlockerID,
			&i.Context,
			&i.Output,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
			&i.CancelledAt,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChildrenByGoalPaged = `-- name: ListChildrenByGoalPaged :many
SELECT id, user_id, agent_id, session_id, goal_id, project_id, source_plan_id, plan_item_id, detached_at, title, description, status, priority, review_policy, active_review_id, required, retry_count, max_retries, not_before, deadline_at, active_run_id, active_blocker_id, context, output, created_at, updated_at, completed_at, cancelled_at, archived_at FROM agent_task WHERE goal_id = ? ORDER BY created_at ASC, id ASC LIMIT ? OFFSET ?
`

type ListChildrenByGoalPagedParams struct {
	GoalID sql.NullString `json:"goal_id"`
	Limit  int64          `json:"limit"`
	Offset int64          `json:"offset"`
}

func (q *Queries) ListChildrenByGoalPaged(ctx context.Context, arg ListChildrenByGoalPagedParams) ([]AgentTask, error) {
	rows, err := q.db.QueryContext(ctx, listChildrenByGoalPaged, arg.GoalID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentTask{}
	for rows.Next() {
		var i AgentTask
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AgentID,
			&i.SessionID,
			&i.GoalID,
			&i.ProjectID,
			&i.SourcePlanID,
			&i.PlanItemID,
			&i.DetachedAt,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.ReviewPolicy,
			&i.ActiveReviewID,
			&i.Required,
			&i.RetryCount,
			&i.MaxRetries,
			&i.NotBefore,
			&i.DeadlineAt,
			&i.ActiveRunID,
			&i.ActiveBlockerID,
			&i.Context,
			&i.Output,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
			&i.CancelledAt,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGoalPlanningCandidates = `-- name: ListGoalPlanningCandidates :many
SELECT id, user_id, agent_id, project_id, title, description, status, priority, review_policy, active_review_id, context, output, created_at, updated_at, completed_at, cancelled_at, archived_at FROM agent_goal
WHERE status = 'draft'
ORDER BY priority DESC, created_at ASC
LIMIT ?
`

func (q *Queries) ListGoalPlanningCandidates(ctx context.Context, limit int64) ([]AgentGoal, error) {
	rows, err := q.db.QueryContext(ctx, listGoalPlanningCandidates, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentGoal{}
	for rows.Next() {
		var i AgentGoal
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AgentID,
			&i.ProjectID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.ReviewPolicy,
			&i.ActiveReviewID,
			&i.Context,
			&i.Output,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
			&i.CancelledAt,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGoalSynthesisCandidates = `-- name: ListGoalSynthesisCandidates :many
SELECT id, user_id, agent_id, project_id, title, description, status, priority, review_policy, active_review_id, context, output, created_at, updated_at, completed_at, cancelled_at, archived_at FROM agent_goal
WHERE status = 'running' AND review_policy != 'none'
ORDER BY priority DESC, updated_at ASC
LIMIT ?
`

func (q *Queries) ListGoalSynthesisCandidates(ctx context.Context, limit int64) ([]AgentGoal, error) {
	rows, err := q.db.QueryContext(ctx, listGoalSynthesisCandidates, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentGoal{}
	for rows.Next() {
		var i AgentGoal
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AgentID,
			&i.ProjectID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.ReviewPolicy,
			&i.ActiveReviewID,
			&i.Context,
			&i.Output,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
			&i.CancelledAt,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const promoteAgentGoalToPlanned = `-- name: PromoteAgentGoalToPlanned :execrows
UPDATE agent_goal
SET status = 'planned', updated_at = ?
WHERE id = ? AND status IN ('draft', 'planning')
`

type PromoteAgentGoalToPlannedParams struct {
	UpdatedAt string `json:"updated_at"`
	ID        string `json:"id"`
}

// PromoteAgentGoalToPlanned promotes a goal to 'planned' only from a pre-run
// state, so a replan re-materialize on a running goal is a no-op (0 rows), not a
// regression to planned (opus B2). #525.
func (q *Queries) PromoteAgentGoalToPlanned(ctx context.Context, arg PromoteAgentGoalToPlannedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, promoteAgentGoalToPlanned, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setAgentGoalActiveReview = `-- name: SetAgentGoalActiveReview :exec
UPDATE agent_goal SET active_review_id = ?, updated_at = ? WHERE id = ?
`

type SetAgentGoalActiveReviewParams struct {
	ActiveReviewID sql.NullString `json:"active_review_id"`
	UpdatedAt      string         `json:"updated_at"`
	ID             string         `json:"id"`
}

func (q *Queries) SetAgentGoalActiveReview(ctx context.Context, arg SetAgentGoalActiveReviewParams) error {
	_, err := q.db.ExecContext(ctx, setAgentGoalActiveReview, arg.ActiveReviewID, arg.UpdatedAt, arg.ID)
	return err
}

const setAgentGoalOutput = `-- name: SetAgentGoalOutput :exec
UPDATE agent_goal SET output = ?, completed_at = ?, updated_at = ? WHERE id = ?
`

type SetAgentGoalOutputParams struct {
	Output      string         `json:"output"`
	CompletedAt sql.NullString `json:"completed_at"`
	UpdatedAt   string         `json:"updated_at"`
	ID          string         `json:"id"`
}

func (q *Queries) SetAgentGoalOutput(ctx context.Context, arg SetAgentGoalOutputParams) error {
	_, err := q.db.ExecContext(ctx, setAgentGoalOutput,
		arg.Output,
		arg.CompletedAt,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const transitionAgentGoalStatus = `-- name: TransitionAgentGoalStatus :execrows
UPDATE agent_goal
SET status = ?, updated_at = ?
WHERE id = ? AND status = ?
`

type TransitionAgentGoalStatusParams struct {
	Status    string `json:"status"`
	UpdatedAt string `json:"updated_at"`
	ID        string `json:"id"`
	Status_2  string `json:"status_2"`
}

func (q *Queries) TransitionAgentGoalStatus(ctx context.Context, arg TransitionAgentGoalStatusParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, transitionAgentGoalStatus,
		arg.Status,
		arg.UpdatedAt,
		arg.ID,
		arg.Status_2,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const unarchiveAgentGoal = `-- name: UnarchiveAgentGoal :execrows
UPDATE agent_goal SET archived_at = NULL, updated_at = ? WHERE id = ? AND archived_at IS NOT NULL
`

type UnarchiveAgentGoalParams struct {
	UpdatedAt string `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) UnarchiveAgentGoal(ctx context.Context, arg UnarchiveAgentGoalParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, unarchiveAgentGoal, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
