// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: agent_goal_attempt.sql

package sqlc

import (
	"context"
	"encoding/json"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const countBillableAttempts = `-- name: CountBillableAttempts :one
SELECT COUNT(*)
FROM agent_goal_attempt
WHERE goal_id = $1
  AND purpose = $2
  AND (
        status IN ('queued', 'running', 'submitted')
        OR (status NOT IN ('queued', 'running', 'submitted') AND failure_class NOT IN ('environment', 'contract', 'flaky'))
      )
`

type CountBillableAttemptsParams struct {
	GoalID  string `json:"goal_id"`
	Purpose string `json:"purpose"`
}

// Budget spent for execution/decomposition convergence. In-flight attempts count
// so a concurrent claim cannot overspend. Finished attempts count unless their
// failure class is one old refund path: environment, contract, or flaky. Queued
// reaps finalize as interrupted/flaky and are therefore not billable.
func (q *Queries) CountBillableAttempts(ctx context.Context, arg CountBillableAttemptsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countBillableAttempts, arg.GoalID, arg.Purpose)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countInflightAttemptsByRoot = `-- name: CountInflightAttemptsByRoot :one
SELECT CAST(COUNT(*) AS BIGINT)
FROM agent_goal_attempt a
JOIN agent_goal d ON d.id = a.goal_id
WHERE d.root_id = $1
  AND a.status IN ('queued', 'running')
`

func (q *Queries) CountInflightAttemptsByRoot(ctx context.Context, rootID string) (int64, error) {
	row := q.db.QueryRow(ctx, countInflightAttemptsByRoot, rootID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countInflightAttemptsByUser = `-- name: CountInflightAttemptsByUser :one
SELECT CAST(COUNT(*) AS BIGINT)
FROM agent_goal_attempt a
WHERE a.user_id = $1
  AND a.status IN ('queued', 'running')
`

func (q *Queries) CountInflightAttemptsByUser(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRow(ctx, countInflightAttemptsByUser, userID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countRanReviewAttemptsForOutput = `-- name: CountRanReviewAttemptsForOutput :one
SELECT COUNT(*)
FROM agent_goal_attempt
WHERE goal_id = $1
  AND purpose = 'review'
  AND started_at IS NOT NULL
  AND created_at > $2
`

type CountRanReviewAttemptsForOutputParams struct {
	GoalID string    `json:"goal_id"`
	Since  time.Time `json:"since"`
}

// Review attempts spent on the CURRENT needs_verdict episode: those created after
// the reviewed execution attempt (a later execution attempt starts a fresh
// episode) that actually ran (started_at set). A queued attempt reaped before it
// was promoted never ran and does not charge the budget, mirroring the billable
// budget predicate below. This is the agent-review budget; attempt_no is still
// assigned globally per purpose via GetMaxAttemptNo.
func (q *Queries) CountRanReviewAttemptsForOutput(ctx context.Context, arg CountRanReviewAttemptsForOutputParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRanReviewAttemptsForOutput, arg.GoalID, arg.Since)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAttempt = `-- name: CreateAttempt :one
INSERT INTO agent_goal_attempt (
    id, goal_id, user_id, agent_id, executor_agent_id, session_id,
    purpose, attempt_no, status, input_context, lease_expires_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, goal_id, user_id, agent_id, executor_agent_id, session_id, purpose, attempt_no, status, input_context, evidence, output, gaps, error, heartbeat_at, lease_expires_at, worker_id, started_at, finished_at, created_at, updated_at, failure_class, repair_rounds, previous_failure_class
`

type CreateAttemptParams struct {
	ID              string             `json:"id"`
	GoalID          string             `json:"goal_id"`
	UserID          string             `json:"user_id"`
	AgentID         pgtype.Text        `json:"agent_id"`
	ExecutorAgentID pgtype.Text        `json:"executor_agent_id"`
	SessionID       string             `json:"session_id"`
	Purpose         string             `json:"purpose"`
	AttemptNo       int64              `json:"attempt_no"`
	Status          string             `json:"status"`
	InputContext    json.RawMessage    `json:"input_context"`
	LeaseExpiresAt  pgtype.Timestamptz `json:"lease_expires_at"`
}

func (q *Queries) CreateAttempt(ctx context.Context, arg CreateAttemptParams) (AgentGoalAttempt, error) {
	row := q.db.QueryRow(ctx, createAttempt,
		arg.ID,
		arg.GoalID,
		arg.UserID,
		arg.AgentID,
		arg.ExecutorAgentID,
		arg.SessionID,
		arg.Purpose,
		arg.AttemptNo,
		arg.Status,
		arg.InputContext,
		arg.LeaseExpiresAt,
	)
	var i AgentGoalAttempt
	err := row.Scan(
		&i.ID,
		&i.GoalID,
		&i.UserID,
		&i.AgentID,
		&i.ExecutorAgentID,
		&i.SessionID,
		&i.Purpose,
		&i.AttemptNo,
		&i.Status,
		&i.InputContext,
		&i.Evidence,
		&i.Output,
		&i.Gaps,
		&i.Error,
		&i.HeartbeatAt,
		&i.LeaseExpiresAt,
		&i.WorkerID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FailureClass,
		&i.RepairRounds,
		&i.PreviousFailureClass,
	)
	return i, err
}

const finalizeAttempt = `-- name: FinalizeAttempt :execrows
UPDATE agent_goal_attempt
SET status = $1,
    error = $2,
    failure_class = $3,
    finished_at = now(),
    updated_at = now()
WHERE id = $4 AND status IN ('queued', 'running')
`

type FinalizeAttemptParams struct {
	ToStatus     string `json:"to_status"`
	Error        string `json:"error"`
	FailureClass string `json:"failure_class"`
	ID           string `json:"id"`
}

func (q *Queries) FinalizeAttempt(ctx context.Context, arg FinalizeAttemptParams) (int64, error) {
	result, err := q.db.Exec(ctx, finalizeAttempt,
		arg.ToStatus,
		arg.Error,
		arg.FailureClass,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getActiveAttempt = `-- name: GetActiveAttempt :one
SELECT id, goal_id, user_id, agent_id, executor_agent_id, session_id, purpose, attempt_no, status, input_context, evidence, output, gaps, error, heartbeat_at, lease_expires_at, worker_id, started_at, finished_at, created_at, updated_at, failure_class, repair_rounds, previous_failure_class FROM agent_goal_attempt
WHERE goal_id = $1
  AND purpose = $2
  AND status IN ('queued', 'running')
`

type GetActiveAttemptParams struct {
	GoalID  string `json:"goal_id"`
	Purpose string `json:"purpose"`
}

func (q *Queries) GetActiveAttempt(ctx context.Context, arg GetActiveAttemptParams) (AgentGoalAttempt, error) {
	row := q.db.QueryRow(ctx, getActiveAttempt, arg.GoalID, arg.Purpose)
	var i AgentGoalAttempt
	err := row.Scan(
		&i.ID,
		&i.GoalID,
		&i.UserID,
		&i.AgentID,
		&i.ExecutorAgentID,
		&i.SessionID,
		&i.Purpose,
		&i.AttemptNo,
		&i.Status,
		&i.InputContext,
		&i.Evidence,
		&i.Output,
		&i.Gaps,
		&i.Error,
		&i.HeartbeatAt,
		&i.LeaseExpiresAt,
		&i.WorkerID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FailureClass,
		&i.RepairRounds,
		&i.PreviousFailureClass,
	)
	return i, err
}

const getAttempt = `-- name: GetAttempt :one
SELECT id, goal_id, user_id, agent_id, executor_agent_id, session_id, purpose, attempt_no, status, input_context, evidence, output, gaps, error, heartbeat_at, lease_expires_at, worker_id, started_at, finished_at, created_at, updated_at, failure_class, repair_rounds, previous_failure_class FROM agent_goal_attempt WHERE id = $1
`

func (q *Queries) GetAttempt(ctx context.Context, id string) (AgentGoalAttempt, error) {
	row := q.db.QueryRow(ctx, getAttempt, id)
	var i AgentGoalAttempt
	err := row.Scan(
		&i.ID,
		&i.GoalID,
		&i.UserID,
		&i.AgentID,
		&i.ExecutorAgentID,
		&i.SessionID,
		&i.Purpose,
		&i.AttemptNo,
		&i.Status,
		&i.InputContext,
		&i.Evidence,
		&i.Output,
		&i.Gaps,
		&i.Error,
		&i.HeartbeatAt,
		&i.LeaseExpiresAt,
		&i.WorkerID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FailureClass,
		&i.RepairRounds,
		&i.PreviousFailureClass,
	)
	return i, err
}

const getMaxAttemptNo = `-- name: GetMaxAttemptNo :one
SELECT CAST(COALESCE(MAX(attempt_no), 0) AS BIGINT)
FROM agent_goal_attempt
WHERE goal_id = $1 AND purpose = $2
`

type GetMaxAttemptNoParams struct {
	GoalID  string `json:"goal_id"`
	Purpose string `json:"purpose"`
}

// Highest attempt_no for a goal within one purpose; 0 when none exist. The next
// attempt_no is this + 1 (decomposition cannot derive it from attempt_count,
// which only tracks execution attempts).
func (q *Queries) GetMaxAttemptNo(ctx context.Context, arg GetMaxAttemptNoParams) (int64, error) {
	row := q.db.QueryRow(ctx, getMaxAttemptNo, arg.GoalID, arg.Purpose)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const heartbeatAttempt = `-- name: HeartbeatAttempt :execrows
UPDATE agent_goal_attempt
SET heartbeat_at = now(),
    lease_expires_at = $1,
    updated_at = now()
WHERE id = $2 AND status = 'running'
`

type HeartbeatAttemptParams struct {
	LeaseExpiresAt pgtype.Timestamptz `json:"lease_expires_at"`
	ID             string             `json:"id"`
}

func (q *Queries) HeartbeatAttempt(ctx context.Context, arg HeartbeatAttemptParams) (int64, error) {
	result, err := q.db.Exec(ctx, heartbeatAttempt, arg.LeaseExpiresAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listAttemptByGoal = `-- name: ListAttemptByGoal :many
SELECT id, goal_id, user_id, agent_id, executor_agent_id, session_id, purpose, attempt_no, status, input_context, evidence, output, gaps, error, heartbeat_at, lease_expires_at, worker_id, started_at, finished_at, created_at, updated_at, failure_class, repair_rounds, previous_failure_class FROM agent_goal_attempt
WHERE goal_id = $1
  AND ($2::text IS NULL OR purpose = $2::text)
ORDER BY attempt_no DESC
`

type ListAttemptByGoalParams struct {
	GoalID  string      `json:"goal_id"`
	Purpose pgtype.Text `json:"purpose"`
}

func (q *Queries) ListAttemptByGoal(ctx context.Context, arg ListAttemptByGoalParams) ([]AgentGoalAttempt, error) {
	rows, err := q.db.Query(ctx, listAttemptByGoal, arg.GoalID, arg.Purpose)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentGoalAttempt{}
	for rows.Next() {
		var i AgentGoalAttempt
		if err := rows.Scan(
			&i.ID,
			&i.GoalID,
			&i.UserID,
			&i.AgentID,
			&i.ExecutorAgentID,
			&i.SessionID,
			&i.Purpose,
			&i.AttemptNo,
			&i.Status,
			&i.InputContext,
			&i.Evidence,
			&i.Output,
			&i.Gaps,
			&i.Error,
			&i.HeartbeatAt,
			&i.LeaseExpiresAt,
			&i.WorkerID,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FailureClass,
			&i.RepairRounds,
			&i.PreviousFailureClass,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInflightAttemptsByGoal = `-- name: ListInflightAttemptsByGoal :many
SELECT id, goal_id, user_id, agent_id, executor_agent_id, session_id, purpose, attempt_no, status, input_context, evidence, output, gaps, error, heartbeat_at, lease_expires_at, worker_id, started_at, finished_at, created_at, updated_at, failure_class, repair_rounds, previous_failure_class FROM agent_goal_attempt
WHERE goal_id = $1
  AND status IN ('queued', 'running')
`

// Every queued/running attempt for a goal regardless of purpose. Cancel uses
// this to finalize ALL in-flight work: only execution attempts are pointed by
// active_attempt_id, so decomposition/review attempts would otherwise outlive
// the cancel and later be reaped against a terminal goal.
func (q *Queries) ListInflightAttemptsByGoal(ctx context.Context, goalID string) ([]AgentGoalAttempt, error) {
	rows, err := q.db.Query(ctx, listInflightAttemptsByGoal, goalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentGoalAttempt{}
	for rows.Next() {
		var i AgentGoalAttempt
		if err := rows.Scan(
			&i.ID,
			&i.GoalID,
			&i.UserID,
			&i.AgentID,
			&i.ExecutorAgentID,
			&i.SessionID,
			&i.Purpose,
			&i.AttemptNo,
			&i.Status,
			&i.InputContext,
			&i.Evidence,
			&i.Output,
			&i.Gaps,
			&i.Error,
			&i.HeartbeatAt,
			&i.LeaseExpiresAt,
			&i.WorkerID,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FailureClass,
			&i.RepairRounds,
			&i.PreviousFailureClass,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaleAttempts = `-- name: ListStaleAttempts :many
SELECT id, goal_id, user_id, agent_id, executor_agent_id, session_id, purpose, attempt_no, status, input_context, evidence, output, gaps, error, heartbeat_at, lease_expires_at, worker_id, started_at, finished_at, created_at, updated_at, failure_class, repair_rounds, previous_failure_class FROM agent_goal_attempt
WHERE status IN ('queued', 'running')
  AND lease_expires_at IS NOT NULL
  AND lease_expires_at < $1
ORDER BY lease_expires_at ASC
LIMIT $2
`

type ListStaleAttemptsParams struct {
	Now   pgtype.Timestamptz `json:"now"`
	Limit int32              `json:"limit"`
}

// Lease-expired attempts whose lease is a liveness signal. An attempt heartbeated
// by a River worker (every execution attempt, and an autonomous decomposition
// attempt) carries a forward-moving lease, so an expired lease means a genuine
// orphan. Interactive decomposition attempts (planned in a session, never
// enqueued/heartbeated) carry a NULL lease and are skipped by the IS NOT NULL
// guard, so the reaper never bounces an active composite back to draft mid-planning.
func (q *Queries) ListStaleAttempts(ctx context.Context, arg ListStaleAttemptsParams) ([]AgentGoalAttempt, error) {
	rows, err := q.db.Query(ctx, listStaleAttempts, arg.Now, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentGoalAttempt{}
	for rows.Next() {
		var i AgentGoalAttempt
		if err := rows.Scan(
			&i.ID,
			&i.GoalID,
			&i.UserID,
			&i.AgentID,
			&i.ExecutorAgentID,
			&i.SessionID,
			&i.Purpose,
			&i.AttemptNo,
			&i.Status,
			&i.InputContext,
			&i.Evidence,
			&i.Output,
			&i.Gaps,
			&i.Error,
			&i.HeartbeatAt,
			&i.LeaseExpiresAt,
			&i.WorkerID,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FailureClass,
			&i.RepairRounds,
			&i.PreviousFailureClass,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const promoteAttempt = `-- name: PromoteAttempt :execrows
UPDATE agent_goal_attempt
SET status = 'running',
    started_at = now(),
    heartbeat_at = now(),
    lease_expires_at = $1,
    updated_at = now()
WHERE id = $2 AND status = 'queued'
`

type PromoteAttemptParams struct {
	LeaseExpiresAt pgtype.Timestamptz `json:"lease_expires_at"`
	ID             string             `json:"id"`
}

func (q *Queries) PromoteAttempt(ctx context.Context, arg PromoteAttemptParams) (int64, error) {
	result, err := q.db.Exec(ctx, promoteAttempt, arg.LeaseExpiresAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setAttemptGaps = `-- name: SetAttemptGaps :exec
UPDATE agent_goal_attempt
SET gaps = $1, updated_at = now()
WHERE id = $2
`

type SetAttemptGapsParams struct {
	Gaps json.RawMessage `json:"gaps"`
	ID   string          `json:"id"`
}

func (q *Queries) SetAttemptGaps(ctx context.Context, arg SetAttemptGapsParams) error {
	_, err := q.db.Exec(ctx, setAttemptGaps, arg.Gaps, arg.ID)
	return err
}

const setAttemptRepairRounds = `-- name: SetAttemptRepairRounds :exec
UPDATE agent_goal_attempt
SET repair_rounds = $1, updated_at = now()
WHERE id = $2
`

type SetAttemptRepairRoundsParams struct {
	RepairRounds int32  `json:"repair_rounds"`
	ID           string `json:"id"`
}

func (q *Queries) SetAttemptRepairRounds(ctx context.Context, arg SetAttemptRepairRoundsParams) error {
	_, err := q.db.Exec(ctx, setAttemptRepairRounds, arg.RepairRounds, arg.ID)
	return err
}

const submitAttempt = `-- name: SubmitAttempt :execrows
UPDATE agent_goal_attempt
SET status = 'submitted',
    evidence = $1,
    output = $2,
    finished_at = now(),
    updated_at = now()
WHERE id = $3 AND status = 'running'
`

type SubmitAttemptParams struct {
	Evidence json.RawMessage `json:"evidence"`
	Output   json.RawMessage `json:"output"`
	ID       string          `json:"id"`
}

func (q *Queries) SubmitAttempt(ctx context.Context, arg SubmitAttemptParams) (int64, error) {
	result, err := q.db.Exec(ctx, submitAttempt, arg.Evidence, arg.Output, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
