// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: agent_goal.sql

package sqlc

import (
	"context"
	"encoding/json"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const acceptGoal = `-- name: AcceptGoal :execrows
UPDATE agent_goal SET
    lifecycle = 'accepted',
    acceptance_state = 'passed',
    accepted_output = $1,
    accepted_at = now(),
    active_attempt_id = NULL,
    updated_at = now()
WHERE id = $2 AND lifecycle = 'active'
`

type AcceptGoalParams struct {
	AcceptedOutput pgtype.Text `json:"accepted_output"`
	ID             string      `json:"id"`
}

func (q *Queries) AcceptGoal(ctx context.Context, arg AcceptGoalParams) (int64, error) {
	result, err := q.db.Exec(ctx, acceptGoal, arg.AcceptedOutput, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const archiveGoal = `-- name: ArchiveGoal :exec
UPDATE agent_goal SET
    archived_at = now(),
    updated_at = now()
WHERE id = $1
`

func (q *Queries) ArchiveGoal(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, archiveGoal, id)
	return err
}

const blockGoal = `-- name: BlockGoal :execrows
UPDATE agent_goal SET
    lifecycle = 'blocked',
    block_reason = $1,
    active_attempt_id = NULL,
    updated_at = now()
WHERE id = $2 AND lifecycle IN ('ready', 'active')
`

type BlockGoalParams struct {
	BlockReason string `json:"block_reason"`
	ID          string `json:"id"`
}

func (q *Queries) BlockGoal(ctx context.Context, arg BlockGoalParams) (int64, error) {
	result, err := q.db.Exec(ctx, blockGoal, arg.BlockReason, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const cancelGoal = `-- name: CancelGoal :exec
UPDATE agent_goal SET
    lifecycle = 'cancelled',
    cancelled_at = now(),
    active_attempt_id = NULL,
    updated_at = now()
WHERE id = $1
`

func (q *Queries) CancelGoal(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, cancelGoal, id)
	return err
}

const claimGoal = `-- name: ClaimGoal :execrows
UPDATE agent_goal SET
    lifecycle = 'active',
    active_attempt_id = $1,
    attempt_count = attempt_count + 1,
    updated_at = now()
WHERE id = $2
  AND lifecycle = 'ready'
  AND active_attempt_id IS NULL
`

type ClaimGoalParams struct {
	ActiveAttemptID pgtype.Text `json:"active_attempt_id"`
	ID              string      `json:"id"`
}

func (q *Queries) ClaimGoal(ctx context.Context, arg ClaimGoalParams) (int64, error) {
	result, err := q.db.Exec(ctx, claimGoal, arg.ActiveAttemptID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const clearGoalActiveAttempt = `-- name: ClearGoalActiveAttempt :exec
UPDATE agent_goal SET
    active_attempt_id = NULL,
    updated_at = now()
WHERE id = $1
`

func (q *Queries) ClearGoalActiveAttempt(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, clearGoalActiveAttempt, id)
	return err
}

const consumeDispatchHint = `-- name: ConsumeDispatchHint :exec
UPDATE agent_goal SET
    dispatch_hint = $1,
    updated_at = now()
WHERE id = $2
`

type ConsumeDispatchHintParams struct {
	DispatchHint json.RawMessage `json:"dispatch_hint"`
	ID           string          `json:"id"`
}

func (q *Queries) ConsumeDispatchHint(ctx context.Context, arg ConsumeDispatchHintParams) error {
	_, err := q.db.Exec(ctx, consumeDispatchHint, arg.DispatchHint, arg.ID)
	return err
}

const countRootGoal = `-- name: CountRootGoal :one
SELECT CAST(COUNT(*) AS BIGINT) FROM agent_goal
WHERE parent_id IS NULL
  AND user_id = $1
  AND ($2::text IS NULL OR agent_id = $2::text)
  AND ($3::uuid IS NULL OR project_id = $3::uuid)
  AND ($4::text IS NULL OR lifecycle = $4::text)
  AND ($5::boolean IS NULL
       OR (lifecycle IN ('accepted', 'rejected_final', 'abandoned', 'cancelled')) = $5::boolean)
  AND ($6::text IS NULL OR title ILIKE '%' || $6 || '%' OR intent ILIKE '%' || $6 || '%')
  AND ($7::boolean OR archived_at IS NULL)
`

type CountRootGoalParams struct {
	UserID          string      `json:"user_id"`
	AgentID         pgtype.Text `json:"agent_id"`
	ProjectID       pgtype.Text `json:"project_id"`
	Lifecycle       pgtype.Text `json:"lifecycle"`
	Terminal        pgtype.Bool `json:"terminal"`
	Q               pgtype.Text `json:"q"`
	IncludeArchived bool        `json:"include_archived"`
}

// CountRootGoal mirrors ListRootGoal's filter so a list's reported
// total is exact, and the active/history/archived header badges are three cheap
// counts that vary only their terminal/include_archived args.
func (q *Queries) CountRootGoal(ctx context.Context, arg CountRootGoalParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRootGoal,
		arg.UserID,
		arg.AgentID,
		arg.ProjectID,
		arg.Lifecycle,
		arg.Terminal,
		arg.Q,
		arg.IncludeArchived,
	)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createGoal = `-- name: CreateGoal :one
INSERT INTO agent_goal (
    id, user_id, agent_id, project_id, parent_id, root_id, depth, position,
    session_id, title, intent, kind, priority, required,
    acceptance_contract, convergence_policy, review_policy,
    lifecycle, context, dispatch_hint
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20)
RETURNING id, user_id, agent_id, project_id, parent_id, root_id, depth, position, session_id, title, intent, kind, priority, required, acceptance_contract, convergence_policy, review_policy, lifecycle, block_reason, acceptance_state, accepted_output, acceptance_seq, active_attempt_id, attempt_count, required_total, required_accepted, required_failed, required_blocked, context, dispatch_hint, created_at, updated_at, accepted_at, cancelled_at, archived_at, plan, planned_at, flaky_count, budget_bonus
`

type CreateGoalParams struct {
	ID                 string          `json:"id"`
	UserID             string          `json:"user_id"`
	AgentID            string          `json:"agent_id"`
	ProjectID          pgtype.Text     `json:"project_id"`
	ParentID           pgtype.Text     `json:"parent_id"`
	RootID             string          `json:"root_id"`
	Depth              int64           `json:"depth"`
	Position           int64           `json:"position"`
	SessionID          string          `json:"session_id"`
	Title              string          `json:"title"`
	Intent             string          `json:"intent"`
	Kind               string          `json:"kind"`
	Priority           string          `json:"priority"`
	Required           bool            `json:"required"`
	AcceptanceContract json.RawMessage `json:"acceptance_contract"`
	ConvergencePolicy  json.RawMessage `json:"convergence_policy"`
	ReviewPolicy       string          `json:"review_policy"`
	Lifecycle          string          `json:"lifecycle"`
	Context            json.RawMessage `json:"context"`
	DispatchHint       json.RawMessage `json:"dispatch_hint"`
}

func (q *Queries) CreateGoal(ctx context.Context, arg CreateGoalParams) (AgentGoal, error) {
	row := q.db.QueryRow(ctx, createGoal,
		arg.ID,
		arg.UserID,
		arg.AgentID,
		arg.ProjectID,
		arg.ParentID,
		arg.RootID,
		arg.Depth,
		arg.Position,
		arg.SessionID,
		arg.Title,
		arg.Intent,
		arg.Kind,
		arg.Priority,
		arg.Required,
		arg.AcceptanceContract,
		arg.ConvergencePolicy,
		arg.ReviewPolicy,
		arg.Lifecycle,
		arg.Context,
		arg.DispatchHint,
	)
	var i AgentGoal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AgentID,
		&i.ProjectID,
		&i.ParentID,
		&i.RootID,
		&i.Depth,
		&i.Position,
		&i.SessionID,
		&i.Title,
		&i.Intent,
		&i.Kind,
		&i.Priority,
		&i.Required,
		&i.AcceptanceContract,
		&i.ConvergencePolicy,
		&i.ReviewPolicy,
		&i.Lifecycle,
		&i.BlockReason,
		&i.AcceptanceState,
		&i.AcceptedOutput,
		&i.AcceptanceSeq,
		&i.ActiveAttemptID,
		&i.AttemptCount,
		&i.RequiredTotal,
		&i.RequiredAccepted,
		&i.RequiredFailed,
		&i.RequiredBlocked,
		&i.Context,
		&i.DispatchHint,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AcceptedAt,
		&i.CancelledAt,
		&i.ArchivedAt,
		&i.Plan,
		&i.PlannedAt,
		&i.FlakyCount,
		&i.BudgetBonus,
	)
	return i, err
}

const decrGoalRequiredBlocked = `-- name: DecrGoalRequiredBlocked :exec
UPDATE agent_goal SET
    required_blocked = required_blocked - 1,
    updated_at = now()
WHERE id = $1 AND required_blocked > 0
`

func (q *Queries) DecrGoalRequiredBlocked(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, decrGoalRequiredBlocked, id)
	return err
}

const getGoal = `-- name: GetGoal :one
SELECT id, user_id, agent_id, project_id, parent_id, root_id, depth, position, session_id, title, intent, kind, priority, required, acceptance_contract, convergence_policy, review_policy, lifecycle, block_reason, acceptance_state, accepted_output, acceptance_seq, active_attempt_id, attempt_count, required_total, required_accepted, required_failed, required_blocked, context, dispatch_hint, created_at, updated_at, accepted_at, cancelled_at, archived_at, plan, planned_at, flaky_count, budget_bonus FROM agent_goal WHERE id = $1
`

func (q *Queries) GetGoal(ctx context.Context, id string) (AgentGoal, error) {
	row := q.db.QueryRow(ctx, getGoal, id)
	var i AgentGoal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AgentID,
		&i.ProjectID,
		&i.ParentID,
		&i.RootID,
		&i.Depth,
		&i.Position,
		&i.SessionID,
		&i.Title,
		&i.Intent,
		&i.Kind,
		&i.Priority,
		&i.Required,
		&i.AcceptanceContract,
		&i.ConvergencePolicy,
		&i.ReviewPolicy,
		&i.Lifecycle,
		&i.BlockReason,
		&i.AcceptanceState,
		&i.AcceptedOutput,
		&i.AcceptanceSeq,
		&i.ActiveAttemptID,
		&i.AttemptCount,
		&i.RequiredTotal,
		&i.RequiredAccepted,
		&i.RequiredFailed,
		&i.RequiredBlocked,
		&i.Context,
		&i.DispatchHint,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AcceptedAt,
		&i.CancelledAt,
		&i.ArchivedAt,
		&i.Plan,
		&i.PlannedAt,
		&i.FlakyCount,
		&i.BudgetBonus,
	)
	return i, err
}

const incrGoalRequiredAccepted = `-- name: IncrGoalRequiredAccepted :exec
UPDATE agent_goal SET
    required_accepted = required_accepted + 1,
    updated_at = now()
WHERE id = $1
`

func (q *Queries) IncrGoalRequiredAccepted(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, incrGoalRequiredAccepted, id)
	return err
}

const incrGoalRequiredBlocked = `-- name: IncrGoalRequiredBlocked :exec
UPDATE agent_goal SET
    required_blocked = required_blocked + 1,
    updated_at = now()
WHERE id = $1
`

func (q *Queries) IncrGoalRequiredBlocked(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, incrGoalRequiredBlocked, id)
	return err
}

const incrGoalRequiredFailed = `-- name: IncrGoalRequiredFailed :exec
UPDATE agent_goal SET
    required_failed = required_failed + 1,
    updated_at = now()
WHERE id = $1
`

func (q *Queries) IncrGoalRequiredFailed(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, incrGoalRequiredFailed, id)
	return err
}

const incrementGoalBudgetBonus = `-- name: IncrementGoalBudgetBonus :exec
UPDATE agent_goal SET
    budget_bonus = budget_bonus + 1,
    updated_at = now()
WHERE id = $1
`

func (q *Queries) IncrementGoalBudgetBonus(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, incrementGoalBudgetBonus, id)
	return err
}

const incrementGoalFlakyCount = `-- name: IncrementGoalFlakyCount :one
UPDATE agent_goal SET
    flaky_count = flaky_count + 1,
    updated_at = now()
WHERE id = $1
RETURNING flaky_count
`

func (q *Queries) IncrementGoalFlakyCount(ctx context.Context, id string) (int64, error) {
	row := q.db.QueryRow(ctx, incrementGoalFlakyCount, id)
	var flaky_count int64
	err := row.Scan(&flaky_count)
	return flaky_count, err
}

const listBlockedDepComposites = `-- name: ListBlockedDepComposites :many
SELECT id, user_id, agent_id, project_id, parent_id, root_id, depth, position, session_id, title, intent, kind, priority, required, acceptance_contract, convergence_policy, review_policy, lifecycle, block_reason, acceptance_state, accepted_output, acceptance_seq, active_attempt_id, attempt_count, required_total, required_accepted, required_failed, required_blocked, context, dispatch_hint, created_at, updated_at, accepted_at, cancelled_at, archived_at, plan, planned_at, flaky_count, budget_bonus FROM agent_goal
WHERE kind = 'composite'
  AND lifecycle = 'blocked'
  AND block_reason = 'dep'
ORDER BY updated_at ASC
LIMIT $1
`

// Composites parked blocked(dep) by the rollup because a required child was
// blocked. The rollup scans (ListRollupCandidates/ListStalledComposites) only see
// active composites, so a parent driven here never re-enters rollup on its own.
// The dispatcher re-evaluates each: once its blocking children clear, it is woken
// back to active so the rollup resumes (see RecoverBlockedComposite).
func (q *Queries) ListBlockedDepComposites(ctx context.Context, limit int32) ([]AgentGoal, error) {
	rows, err := q.db.Query(ctx, listBlockedDepComposites, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentGoal{}
	for rows.Next() {
		var i AgentGoal
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AgentID,
			&i.ProjectID,
			&i.ParentID,
			&i.RootID,
			&i.Depth,
			&i.Position,
			&i.SessionID,
			&i.Title,
			&i.Intent,
			&i.Kind,
			&i.Priority,
			&i.Required,
			&i.AcceptanceContract,
			&i.ConvergencePolicy,
			&i.ReviewPolicy,
			&i.Lifecycle,
			&i.BlockReason,
			&i.AcceptanceState,
			&i.AcceptedOutput,
			&i.AcceptanceSeq,
			&i.ActiveAttemptID,
			&i.AttemptCount,
			&i.RequiredTotal,
			&i.RequiredAccepted,
			&i.RequiredFailed,
			&i.RequiredBlocked,
			&i.Context,
			&i.DispatchHint,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AcceptedAt,
			&i.CancelledAt,
			&i.ArchivedAt,
			&i.Plan,
			&i.PlannedAt,
			&i.FlakyCount,
			&i.BudgetBonus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDecomposableComposites = `-- name: ListDecomposableComposites :many
SELECT id, user_id, agent_id, project_id, parent_id, root_id, depth, position, session_id, title, intent, kind, priority, required, acceptance_contract, convergence_policy, review_policy, lifecycle, block_reason, acceptance_state, accepted_output, acceptance_seq, active_attempt_id, attempt_count, required_total, required_accepted, required_failed, required_blocked, context, dispatch_hint, created_at, updated_at, accepted_at, cancelled_at, archived_at, plan, planned_at, flaky_count, budget_bonus FROM agent_goal
WHERE kind = 'composite'
  AND lifecycle = 'draft'
  AND planned_at IS NULL
ORDER BY priority DESC, created_at ASC
LIMIT $1
`

// Composites awaiting autonomous decomposition: freshly created (draft) and not
// planned yet. Both review policies are auto-driven: the planner always produces
// the plan; review_policy='human' only adds an approval gate after the plan is
// proposed (the goal parks blocked(needs_plan_approval)), it does not stop the
// planner from running. The dispatcher mints + enqueues a decomposition attempt
// for each, moving it draft->active so it is not re-picked.
func (q *Queries) ListDecomposableComposites(ctx context.Context, limit int32) ([]AgentGoal, error) {
	rows, err := q.db.Query(ctx, listDecomposableComposites, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentGoal{}
	for rows.Next() {
		var i AgentGoal
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AgentID,
			&i.ProjectID,
			&i.ParentID,
			&i.RootID,
			&i.Depth,
			&i.Position,
			&i.SessionID,
			&i.Title,
			&i.Intent,
			&i.Kind,
			&i.Priority,
			&i.Required,
			&i.AcceptanceContract,
			&i.ConvergencePolicy,
			&i.ReviewPolicy,
			&i.Lifecycle,
			&i.BlockReason,
			&i.AcceptanceState,
			&i.AcceptedOutput,
			&i.AcceptanceSeq,
			&i.ActiveAttemptID,
			&i.AttemptCount,
			&i.RequiredTotal,
			&i.RequiredAccepted,
			&i.RequiredFailed,
			&i.RequiredBlocked,
			&i.Context,
			&i.DispatchHint,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AcceptedAt,
			&i.CancelledAt,
			&i.ArchivedAt,
			&i.Plan,
			&i.PlannedAt,
			&i.FlakyCount,
			&i.BudgetBonus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDispatchableLeaves = `-- name: ListDispatchableLeaves :many
SELECT id, user_id, agent_id, project_id, parent_id, root_id, depth, position, session_id, title, intent, kind, priority, required, acceptance_contract, convergence_policy, review_policy, lifecycle, block_reason, acceptance_state, accepted_output, acceptance_seq, active_attempt_id, attempt_count, required_total, required_accepted, required_failed, required_blocked, context, dispatch_hint, created_at, updated_at, accepted_at, cancelled_at, archived_at, plan, planned_at, flaky_count, budget_bonus FROM agent_goal
WHERE lifecycle = 'ready'
  AND active_attempt_id IS NULL
  AND kind = 'leaf'
ORDER BY priority DESC, created_at ASC
LIMIT $1
`

func (q *Queries) ListDispatchableLeaves(ctx context.Context, limit int32) ([]AgentGoal, error) {
	rows, err := q.db.Query(ctx, listDispatchableLeaves, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentGoal{}
	for rows.Next() {
		var i AgentGoal
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AgentID,
			&i.ProjectID,
			&i.ParentID,
			&i.RootID,
			&i.Depth,
			&i.Position,
			&i.SessionID,
			&i.Title,
			&i.Intent,
			&i.Kind,
			&i.Priority,
			&i.Required,
			&i.AcceptanceContract,
			&i.ConvergencePolicy,
			&i.ReviewPolicy,
			&i.Lifecycle,
			&i.BlockReason,
			&i.AcceptanceState,
			&i.AcceptedOutput,
			&i.AcceptanceSeq,
			&i.ActiveAttemptID,
			&i.AttemptCount,
			&i.RequiredTotal,
			&i.RequiredAccepted,
			&i.RequiredFailed,
			&i.RequiredBlocked,
			&i.Context,
			&i.DispatchHint,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AcceptedAt,
			&i.CancelledAt,
			&i.ArchivedAt,
			&i.Plan,
			&i.PlannedAt,
			&i.FlakyCount,
			&i.BudgetBonus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGoalByRoot = `-- name: ListGoalByRoot :many
SELECT id, user_id, agent_id, project_id, parent_id, root_id, depth, position, session_id, title, intent, kind, priority, required, acceptance_contract, convergence_policy, review_policy, lifecycle, block_reason, acceptance_state, accepted_output, acceptance_seq, active_attempt_id, attempt_count, required_total, required_accepted, required_failed, required_blocked, context, dispatch_hint, created_at, updated_at, accepted_at, cancelled_at, archived_at, plan, planned_at, flaky_count, budget_bonus FROM agent_goal
WHERE root_id = $1
ORDER BY depth ASC, position ASC, id ASC
`

func (q *Queries) ListGoalByRoot(ctx context.Context, rootID string) ([]AgentGoal, error) {
	rows, err := q.db.Query(ctx, listGoalByRoot, rootID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentGoal{}
	for rows.Next() {
		var i AgentGoal
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AgentID,
			&i.ProjectID,
			&i.ParentID,
			&i.RootID,
			&i.Depth,
			&i.Position,
			&i.SessionID,
			&i.Title,
			&i.Intent,
			&i.Kind,
			&i.Priority,
			&i.Required,
			&i.AcceptanceContract,
			&i.ConvergencePolicy,
			&i.ReviewPolicy,
			&i.Lifecycle,
			&i.BlockReason,
			&i.AcceptanceState,
			&i.AcceptedOutput,
			&i.AcceptanceSeq,
			&i.ActiveAttemptID,
			&i.AttemptCount,
			&i.RequiredTotal,
			&i.RequiredAccepted,
			&i.RequiredFailed,
			&i.RequiredBlocked,
			&i.Context,
			&i.DispatchHint,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AcceptedAt,
			&i.CancelledAt,
			&i.ArchivedAt,
			&i.Plan,
			&i.PlannedAt,
			&i.FlakyCount,
			&i.BudgetBonus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGoalChildren = `-- name: ListGoalChildren :many
SELECT id, user_id, agent_id, project_id, parent_id, root_id, depth, position, session_id, title, intent, kind, priority, required, acceptance_contract, convergence_policy, review_policy, lifecycle, block_reason, acceptance_state, accepted_output, acceptance_seq, active_attempt_id, attempt_count, required_total, required_accepted, required_failed, required_blocked, context, dispatch_hint, created_at, updated_at, accepted_at, cancelled_at, archived_at, plan, planned_at, flaky_count, budget_bonus FROM agent_goal
WHERE parent_id = $1
ORDER BY position ASC, id ASC
`

func (q *Queries) ListGoalChildren(ctx context.Context, parentID pgtype.Text) ([]AgentGoal, error) {
	rows, err := q.db.Query(ctx, listGoalChildren, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentGoal{}
	for rows.Next() {
		var i AgentGoal
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AgentID,
			&i.ProjectID,
			&i.ParentID,
			&i.RootID,
			&i.Depth,
			&i.Position,
			&i.SessionID,
			&i.Title,
			&i.Intent,
			&i.Kind,
			&i.Priority,
			&i.Required,
			&i.AcceptanceContract,
			&i.ConvergencePolicy,
			&i.ReviewPolicy,
			&i.Lifecycle,
			&i.BlockReason,
			&i.AcceptanceState,
			&i.AcceptedOutput,
			&i.AcceptanceSeq,
			&i.ActiveAttemptID,
			&i.AttemptCount,
			&i.RequiredTotal,
			&i.RequiredAccepted,
			&i.RequiredFailed,
			&i.RequiredBlocked,
			&i.Context,
			&i.DispatchHint,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AcceptedAt,
			&i.CancelledAt,
			&i.ArchivedAt,
			&i.Plan,
			&i.PlannedAt,
			&i.FlakyCount,
			&i.BudgetBonus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGoalSubtree = `-- name: ListGoalSubtree :many
WITH RECURSIVE subtree(id) AS (
    SELECT d0.id FROM agent_goal d0 WHERE d0.id = $1
    UNION ALL
    SELECT d.id FROM agent_goal d
    JOIN subtree s ON d.parent_id = s.id
)
SELECT d.id, d.user_id, d.agent_id, d.project_id, d.parent_id, d.root_id, d.depth, d.position, d.session_id, d.title, d.intent, d.kind, d.priority, d.required, d.acceptance_contract, d.convergence_policy, d.review_policy, d.lifecycle, d.block_reason, d.acceptance_state, d.accepted_output, d.acceptance_seq, d.active_attempt_id, d.attempt_count, d.required_total, d.required_accepted, d.required_failed, d.required_blocked, d.context, d.dispatch_hint, d.created_at, d.updated_at, d.accepted_at, d.cancelled_at, d.archived_at, d.plan, d.planned_at, d.flaky_count, d.budget_bonus FROM agent_goal d
JOIN subtree s ON d.id = s.id
ORDER BY d.depth ASC, d.position ASC, d.id ASC
`

func (q *Queries) ListGoalSubtree(ctx context.Context, id string) ([]AgentGoal, error) {
	rows, err := q.db.Query(ctx, listGoalSubtree, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentGoal{}
	for rows.Next() {
		var i AgentGoal
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AgentID,
			&i.ProjectID,
			&i.ParentID,
			&i.RootID,
			&i.Depth,
			&i.Position,
			&i.SessionID,
			&i.Title,
			&i.Intent,
			&i.Kind,
			&i.Priority,
			&i.Required,
			&i.AcceptanceContract,
			&i.ConvergencePolicy,
			&i.ReviewPolicy,
			&i.Lifecycle,
			&i.BlockReason,
			&i.AcceptanceState,
			&i.AcceptedOutput,
			&i.AcceptanceSeq,
			&i.ActiveAttemptID,
			&i.AttemptCount,
			&i.RequiredTotal,
			&i.RequiredAccepted,
			&i.RequiredFailed,
			&i.RequiredBlocked,
			&i.Context,
			&i.DispatchHint,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AcceptedAt,
			&i.CancelledAt,
			&i.ArchivedAt,
			&i.Plan,
			&i.PlannedAt,
			&i.FlakyCount,
			&i.BudgetBonus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGoalsBlockedNeedsVerdict = `-- name: ListGoalsBlockedNeedsVerdict :many
SELECT id, user_id, agent_id, project_id, parent_id, root_id, depth, position, session_id, title, intent, kind, priority, required, acceptance_contract, convergence_policy, review_policy, lifecycle, block_reason, acceptance_state, accepted_output, acceptance_seq, active_attempt_id, attempt_count, required_total, required_accepted, required_failed, required_blocked, context, dispatch_hint, created_at, updated_at, accepted_at, cancelled_at, archived_at, plan, planned_at, flaky_count, budget_bonus FROM agent_goal
WHERE lifecycle = 'blocked'
  AND block_reason = 'needs_verdict'
ORDER BY priority DESC, created_at ASC
LIMIT $1
`

// Goals parked blocked(needs_verdict): a required judgment item has no valid
// verdict. The dispatcher (scanAndReview) drives an agent reviewer for any with a
// pending authority=agent item (contract section 10.13); the rest await a human.
// Both leaf and composite goals can carry an authored judgment contract.
func (q *Queries) ListGoalsBlockedNeedsVerdict(ctx context.Context, limit int32) ([]AgentGoal, error) {
	rows, err := q.db.Query(ctx, listGoalsBlockedNeedsVerdict, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentGoal{}
	for rows.Next() {
		var i AgentGoal
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AgentID,
			&i.ProjectID,
			&i.ParentID,
			&i.RootID,
			&i.Depth,
			&i.Position,
			&i.SessionID,
			&i.Title,
			&i.Intent,
			&i.Kind,
			&i.Priority,
			&i.Required,
			&i.AcceptanceContract,
			&i.ConvergencePolicy,
			&i.ReviewPolicy,
			&i.Lifecycle,
			&i.BlockReason,
			&i.AcceptanceState,
			&i.AcceptedOutput,
			&i.AcceptanceSeq,
			&i.ActiveAttemptID,
			&i.AttemptCount,
			&i.RequiredTotal,
			&i.RequiredAccepted,
			&i.RequiredFailed,
			&i.RequiredBlocked,
			&i.Context,
			&i.DispatchHint,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AcceptedAt,
			&i.CancelledAt,
			&i.ArchivedAt,
			&i.Plan,
			&i.PlannedAt,
			&i.FlakyCount,
			&i.BudgetBonus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInboxGoals = `-- name: ListInboxGoals :many
SELECT
    d.id,
    d.agent_id,
    d.project_id,
    d.title,
    d.intent,
    d.lifecycle,
    d.block_reason,
    d.updated_at,
    d.created_at
FROM agent_goal d
JOIN agent_goal r ON r.id = d.root_id
WHERE d.user_id = $1
  AND d.archived_at IS NULL
  AND ($2::text IS NULL OR d.agent_id = $2::text)
  AND (
        (
          d.lifecycle = 'blocked'
          AND (
                d.block_reason IN ('needs_verdict', 'needs_plan_approval', 'budget_exhausted', 'planning_invalid', 'contract_conflict', 'env_unavailable')
              )
          AND r.lifecycle NOT IN ('accepted', 'rejected_final', 'abandoned', 'cancelled')
        )
        OR (d.lifecycle IN ('rejected_final', 'abandoned') AND d.updated_at >= $3 AND d.parent_id IS NULL)
      )
ORDER BY d.updated_at DESC, d.id DESC
LIMIT $4
`

type ListInboxGoalsParams struct {
	UserID     string      `json:"user_id"`
	AgentID    pgtype.Text `json:"agent_id"`
	Since      time.Time   `json:"since"`
	LimitCount int32       `json:"limit_count"`
}

type ListInboxGoalsRow struct {
	ID          string      `json:"id"`
	AgentID     string      `json:"agent_id"`
	ProjectID   pgtype.Text `json:"project_id"`
	Title       string      `json:"title"`
	Intent      string      `json:"intent"`
	Lifecycle   string      `json:"lifecycle"`
	BlockReason string      `json:"block_reason"`
	UpdatedAt   time.Time   `json:"updated_at"`
	CreatedAt   time.Time   `json:"created_at"`
}

// Goals needing user attention, for the inbox. Only human-actionable blocks
// surface (dep-blocked goals resume on their own when upstream clears), at any
// tree depth so a block buried in a subtask is still seen -- but not under a
// terminal root, whose tree is already dead. Open blocks surface at any age
// (they wait on the user); terminal failures are windowed like failed runs and
// limited to roots (a child failure is covered by its root's outcome).
// The handler splits rows into inbox kinds by lifecycle/block_reason.
func (q *Queries) ListInboxGoals(ctx context.Context, arg ListInboxGoalsParams) ([]ListInboxGoalsRow, error) {
	rows, err := q.db.Query(ctx, listInboxGoals,
		arg.UserID,
		arg.AgentID,
		arg.Since,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInboxGoalsRow{}
	for rows.Next() {
		var i ListInboxGoalsRow
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.ProjectID,
			&i.Title,
			&i.Intent,
			&i.Lifecycle,
			&i.BlockReason,
			&i.UpdatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRollupCandidates = `-- name: ListRollupCandidates :many
SELECT id, user_id, agent_id, project_id, parent_id, root_id, depth, position, session_id, title, intent, kind, priority, required, acceptance_contract, convergence_policy, review_policy, lifecycle, block_reason, acceptance_state, accepted_output, acceptance_seq, active_attempt_id, attempt_count, required_total, required_accepted, required_failed, required_blocked, context, dispatch_hint, created_at, updated_at, accepted_at, cancelled_at, archived_at, plan, planned_at, flaky_count, budget_bonus FROM agent_goal
WHERE kind = 'composite'
  AND lifecycle = 'active'
  AND required_total > 0
  AND required_accepted >= required_total
ORDER BY updated_at ASC
LIMIT $1
`

func (q *Queries) ListRollupCandidates(ctx context.Context, limit int32) ([]AgentGoal, error) {
	rows, err := q.db.Query(ctx, listRollupCandidates, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentGoal{}
	for rows.Next() {
		var i AgentGoal
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AgentID,
			&i.ProjectID,
			&i.ParentID,
			&i.RootID,
			&i.Depth,
			&i.Position,
			&i.SessionID,
			&i.Title,
			&i.Intent,
			&i.Kind,
			&i.Priority,
			&i.Required,
			&i.AcceptanceContract,
			&i.ConvergencePolicy,
			&i.ReviewPolicy,
			&i.Lifecycle,
			&i.BlockReason,
			&i.AcceptanceState,
			&i.AcceptedOutput,
			&i.AcceptanceSeq,
			&i.ActiveAttemptID,
			&i.AttemptCount,
			&i.RequiredTotal,
			&i.RequiredAccepted,
			&i.RequiredFailed,
			&i.RequiredBlocked,
			&i.Context,
			&i.DispatchHint,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AcceptedAt,
			&i.CancelledAt,
			&i.ArchivedAt,
			&i.Plan,
			&i.PlannedAt,
			&i.FlakyCount,
			&i.BudgetBonus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRootGoal = `-- name: ListRootGoal :many
SELECT id, user_id, agent_id, project_id, parent_id, root_id, depth, position, session_id, title, intent, kind, priority, required, acceptance_contract, convergence_policy, review_policy, lifecycle, block_reason, acceptance_state, accepted_output, acceptance_seq, active_attempt_id, attempt_count, required_total, required_accepted, required_failed, required_blocked, context, dispatch_hint, created_at, updated_at, accepted_at, cancelled_at, archived_at, plan, planned_at, flaky_count, budget_bonus FROM agent_goal
WHERE parent_id IS NULL
  AND user_id = $1
  AND ($2::text IS NULL OR agent_id = $2::text)
  AND ($3::uuid IS NULL OR project_id = $3::uuid)
  AND ($4::text IS NULL OR lifecycle = $4::text)
  AND ($5::boolean IS NULL
       OR (lifecycle IN ('accepted', 'rejected_final', 'abandoned', 'cancelled')) = $5::boolean)
  AND ($6::text IS NULL OR title ILIKE '%' || $6 || '%' OR intent ILIKE '%' || $6 || '%')
  AND ($7::boolean OR archived_at IS NULL)
ORDER BY created_at DESC, id DESC
LIMIT $9 OFFSET $8
`

type ListRootGoalParams struct {
	UserID          string      `json:"user_id"`
	AgentID         pgtype.Text `json:"agent_id"`
	ProjectID       pgtype.Text `json:"project_id"`
	Lifecycle       pgtype.Text `json:"lifecycle"`
	Terminal        pgtype.Bool `json:"terminal"`
	Q               pgtype.Text `json:"q"`
	IncludeArchived bool        `json:"include_archived"`
	Offset          int32       `json:"offset"`
	Limit           int32       `json:"limit"`
}

// Root goals (goals: parent_id IS NULL) for a user, scoped to an agent
// and narrowed by lifecycle / terminal-ness / project / free-text. Every narg is
// optional: NULL matches all. terminal: false = active (non-terminal) only, true =
// history (terminal) only, NULL = both. The terminal set is the four end states.
func (q *Queries) ListRootGoal(ctx context.Context, arg ListRootGoalParams) ([]AgentGoal, error) {
	rows, err := q.db.Query(ctx, listRootGoal,
		arg.UserID,
		arg.AgentID,
		arg.ProjectID,
		arg.Lifecycle,
		arg.Terminal,
		arg.Q,
		arg.IncludeArchived,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentGoal{}
	for rows.Next() {
		var i AgentGoal
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AgentID,
			&i.ProjectID,
			&i.ParentID,
			&i.RootID,
			&i.Depth,
			&i.Position,
			&i.SessionID,
			&i.Title,
			&i.Intent,
			&i.Kind,
			&i.Priority,
			&i.Required,
			&i.AcceptanceContract,
			&i.ConvergencePolicy,
			&i.ReviewPolicy,
			&i.Lifecycle,
			&i.BlockReason,
			&i.AcceptanceState,
			&i.AcceptedOutput,
			&i.AcceptanceSeq,
			&i.ActiveAttemptID,
			&i.AttemptCount,
			&i.RequiredTotal,
			&i.RequiredAccepted,
			&i.RequiredFailed,
			&i.RequiredBlocked,
			&i.Context,
			&i.DispatchHint,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AcceptedAt,
			&i.CancelledAt,
			&i.ArchivedAt,
			&i.Plan,
			&i.PlannedAt,
			&i.FlakyCount,
			&i.BudgetBonus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStalledComposites = `-- name: ListStalledComposites :many
SELECT id, user_id, agent_id, project_id, parent_id, root_id, depth, position, session_id, title, intent, kind, priority, required, acceptance_contract, convergence_policy, review_policy, lifecycle, block_reason, acceptance_state, accepted_output, acceptance_seq, active_attempt_id, attempt_count, required_total, required_accepted, required_failed, required_blocked, context, dispatch_hint, created_at, updated_at, accepted_at, cancelled_at, archived_at, plan, planned_at, flaky_count, budget_bonus FROM agent_goal
WHERE kind = 'composite'
  AND lifecycle = 'active'
  AND required_accepted < required_total
ORDER BY updated_at ASC
LIMIT $1
`

func (q *Queries) ListStalledComposites(ctx context.Context, limit int32) ([]AgentGoal, error) {
	rows, err := q.db.Query(ctx, listStalledComposites, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentGoal{}
	for rows.Next() {
		var i AgentGoal
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AgentID,
			&i.ProjectID,
			&i.ParentID,
			&i.RootID,
			&i.Depth,
			&i.Position,
			&i.SessionID,
			&i.Title,
			&i.Intent,
			&i.Kind,
			&i.Priority,
			&i.Required,
			&i.AcceptanceContract,
			&i.ConvergencePolicy,
			&i.ReviewPolicy,
			&i.Lifecycle,
			&i.BlockReason,
			&i.AcceptanceState,
			&i.AcceptedOutput,
			&i.AcceptanceSeq,
			&i.ActiveAttemptID,
			&i.AttemptCount,
			&i.RequiredTotal,
			&i.RequiredAccepted,
			&i.RequiredFailed,
			&i.RequiredBlocked,
			&i.Context,
			&i.DispatchHint,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AcceptedAt,
			&i.CancelledAt,
			&i.ArchivedAt,
			&i.Plan,
			&i.PlannedAt,
			&i.FlakyCount,
			&i.BudgetBonus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listZombieGoals = `-- name: ListZombieGoals :many
SELECT id, user_id, agent_id, project_id, parent_id, root_id, depth, position, session_id, title, intent, kind, priority, required, acceptance_contract, convergence_policy, review_policy, lifecycle, block_reason, acceptance_state, accepted_output, acceptance_seq, active_attempt_id, attempt_count, required_total, required_accepted, required_failed, required_blocked, context, dispatch_hint, created_at, updated_at, accepted_at, cancelled_at, archived_at, plan, planned_at, flaky_count, budget_bonus FROM agent_goal
WHERE lifecycle NOT IN ('accepted', 'rejected_final', 'abandoned', 'cancelled')
  AND updated_at < now() - interval '5 minutes'
  AND (
    (kind = 'composite' AND lifecycle = 'ready')
    OR (
      lifecycle = 'active'
      AND active_attempt_id IS NULL
      AND (kind = 'leaf' OR planned_at IS NULL)
      AND NOT EXISTS (
        SELECT 1 FROM agent_goal_attempt a
        WHERE a.goal_id = agent_goal.id AND a.status IN ('queued', 'running')
      )
    )
  )
ORDER BY updated_at ASC
LIMIT $1
`

// Liveness backstop: non-terminal goals parked in a state nothing drives.
// Two classes:
//  1. A ready composite: the dispatcher claims ready LEAVES and decomposes
//     DRAFT composites, so nothing ever picks a composite out of ready. The
//     transition table rejects writing this state; the scan catches legacy
//     rows and out-of-band writes.
//  2. An active goal with no active attempt pointer and no queued/running
//     attempt, where activity cannot come from anywhere else: a leaf is only
//     active while claimed, and an UNPLANNED active composite is only active
//     while its decomposition attempt runs. A planned active composite is
//     excluded -- the rollup drives it off its children.
//
// The updated_at grace keeps a row mid-transition in another tx from reading
// as a zombie.
func (q *Queries) ListZombieGoals(ctx context.Context, limit int32) ([]AgentGoal, error) {
	rows, err := q.db.Query(ctx, listZombieGoals, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentGoal{}
	for rows.Next() {
		var i AgentGoal
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AgentID,
			&i.ProjectID,
			&i.ParentID,
			&i.RootID,
			&i.Depth,
			&i.Position,
			&i.SessionID,
			&i.Title,
			&i.Intent,
			&i.Kind,
			&i.Priority,
			&i.Required,
			&i.AcceptanceContract,
			&i.ConvergencePolicy,
			&i.ReviewPolicy,
			&i.Lifecycle,
			&i.BlockReason,
			&i.AcceptanceState,
			&i.AcceptedOutput,
			&i.AcceptanceSeq,
			&i.ActiveAttemptID,
			&i.AttemptCount,
			&i.RequiredTotal,
			&i.RequiredAccepted,
			&i.RequiredFailed,
			&i.RequiredBlocked,
			&i.Context,
			&i.DispatchHint,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AcceptedAt,
			&i.CancelledAt,
			&i.ArchivedAt,
			&i.Plan,
			&i.PlannedAt,
			&i.FlakyCount,
			&i.BudgetBonus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockGoalForWrite = `-- name: LockGoalForWrite :exec
SELECT pg_advisory_xact_lock(hashtextextended('goal:' || $1::text, 0))
`

// Transaction-scoped advisory lock serializing read-modify-write sequence
// allocation for one goal. The acceptance ledger seq and attempt_no
// are each GetMax->+1->insert under Read Committed, which PostgreSQL runs in
// parallel across writers (and nodes): without this, two writers read the same
// max and compute the same next value, silently duplicating the acceptance seq
// (no unique backstop) or colliding on the attempt_no unique index.
// Held until the enclosing tx ends. The 'goal:' prefix keeps unrelated entities
// out of this goal's slot in the shared 64-bit lock space (matching
// AdvisoryXactLock / LockSchedJobForRun).
func (q *Queries) LockGoalForWrite(ctx context.Context, goalID string) error {
	_, err := q.db.Exec(ctx, lockGoalForWrite, goalID)
	return err
}

const markGoalPlanned = `-- name: MarkGoalPlanned :execrows
UPDATE agent_goal SET
    planned_at = now(),
    updated_at = now()
WHERE id = $1 AND planned_at IS NULL
`

// The materialize fence (CAS): stamp planned_at exactly once. A second concurrent
// materialize gets 0 rows and must treat it as an idempotent no-op, so children
// are never double-created. Replaces the old materialized revision unique index.
func (q *Queries) MarkGoalPlanned(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, markGoalPlanned, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const reconcileGoalCounters = `-- name: ReconcileGoalCounters :exec
UPDATE agent_goal SET
    required_total = (
        SELECT CAST(COUNT(*) AS BIGINT) FROM agent_goal c
        WHERE c.parent_id = agent_goal.id AND c.required
    ),
    required_accepted = (
        SELECT CAST(COUNT(*) AS BIGINT) FROM agent_goal c
        WHERE c.parent_id = agent_goal.id AND c.required
          AND c.lifecycle = 'accepted'
    ),
    required_failed = (
        SELECT CAST(COUNT(*) AS BIGINT) FROM agent_goal c
        WHERE c.parent_id = agent_goal.id AND c.required
          AND c.lifecycle IN ('rejected_final', 'abandoned', 'cancelled')
    ),
    required_blocked = (
        SELECT CAST(COUNT(*) AS BIGINT) FROM agent_goal c
        WHERE c.parent_id = agent_goal.id AND c.required
          AND c.lifecycle = 'blocked'
    ),
    updated_at = now()
WHERE agent_goal.id = $1
`

func (q *Queries) ReconcileGoalCounters(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, reconcileGoalCounters, id)
	return err
}

const setGoalAcceptanceState = `-- name: SetGoalAcceptanceState :execrows
UPDATE agent_goal SET
    acceptance_state = $1,
    acceptance_seq = $2,
    updated_at = now()
WHERE id = $3 AND acceptance_seq < $2
`

type SetGoalAcceptanceStateParams struct {
	AcceptanceState string `json:"acceptance_state"`
	AcceptanceSeq   int64  `json:"acceptance_seq"`
	ID              string `json:"id"`
}

func (q *Queries) SetGoalAcceptanceState(ctx context.Context, arg SetGoalAcceptanceStateParams) (int64, error) {
	result, err := q.db.Exec(ctx, setGoalAcceptanceState, arg.AcceptanceState, arg.AcceptanceSeq, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setGoalPlan = `-- name: SetGoalPlan :exec
UPDATE agent_goal SET
    plan = $1,
    updated_at = now()
WHERE id = $2
`

type SetGoalPlanParams struct {
	Plan json.RawMessage `json:"plan"`
	ID   string          `json:"id"`
}

// Write a composite's decomposition plan (children + edges). Set by a
// decomposition attempt before materialize; for review_policy='human' the plan
// sits here while the goal is blocked(needs_plan_approval) until a human acts.
func (q *Queries) SetGoalPlan(ctx context.Context, arg SetGoalPlanParams) error {
	_, err := q.db.Exec(ctx, setGoalPlan, arg.Plan, arg.ID)
	return err
}

const setGoalRequiredTotal = `-- name: SetGoalRequiredTotal :exec
UPDATE agent_goal SET
    required_total = $1,
    updated_at = now()
WHERE id = $2
`

type SetGoalRequiredTotalParams struct {
	RequiredTotal int64  `json:"required_total"`
	ID            string `json:"id"`
}

func (q *Queries) SetGoalRequiredTotal(ctx context.Context, arg SetGoalRequiredTotalParams) error {
	_, err := q.db.Exec(ctx, setGoalRequiredTotal, arg.RequiredTotal, arg.ID)
	return err
}

const transitionGoalLifecycle = `-- name: TransitionGoalLifecycle :execrows
UPDATE agent_goal SET
    lifecycle = $1,
    block_reason = $2,
    updated_at = now()
WHERE id = $3 AND lifecycle = $4
`

type TransitionGoalLifecycleParams struct {
	ToLifecycle   string `json:"to_lifecycle"`
	BlockReason   string `json:"block_reason"`
	ID            string `json:"id"`
	FromLifecycle string `json:"from_lifecycle"`
}

func (q *Queries) TransitionGoalLifecycle(ctx context.Context, arg TransitionGoalLifecycleParams) (int64, error) {
	result, err := q.db.Exec(ctx, transitionGoalLifecycle,
		arg.ToLifecycle,
		arg.BlockReason,
		arg.ID,
		arg.FromLifecycle,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const unarchiveGoal = `-- name: UnarchiveGoal :exec
UPDATE agent_goal SET
    archived_at = NULL,
    updated_at = now()
WHERE id = $1
`

func (q *Queries) UnarchiveGoal(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, unarchiveGoal, id)
	return err
}

const updateGoalIntent = `-- name: UpdateGoalIntent :exec
UPDATE agent_goal SET
    title = $1,
    intent = $2,
    acceptance_contract = $3,
    convergence_policy = $4,
    review_policy = $5,
    priority = $6,
    updated_at = now()
WHERE id = $7
`

type UpdateGoalIntentParams struct {
	Title              string          `json:"title"`
	Intent             string          `json:"intent"`
	AcceptanceContract json.RawMessage `json:"acceptance_contract"`
	ConvergencePolicy  json.RawMessage `json:"convergence_policy"`
	ReviewPolicy       string          `json:"review_policy"`
	Priority           string          `json:"priority"`
	ID                 string          `json:"id"`
}

func (q *Queries) UpdateGoalIntent(ctx context.Context, arg UpdateGoalIntentParams) error {
	_, err := q.db.Exec(ctx, updateGoalIntent,
		arg.Title,
		arg.Intent,
		arg.AcceptanceContract,
		arg.ConvergencePolicy,
		arg.ReviewPolicy,
		arg.Priority,
		arg.ID,
	)
	return err
}
