// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: agent_task_blocker.sql

package sqlc

import (
	"context"
	"database/sql"
)

const appendAgentTaskBlockerDetail = `-- name: AppendAgentTaskBlockerDetail :exec
UPDATE agent_task_blocker
SET detail = ?
WHERE id = ?
`

type AppendAgentTaskBlockerDetailParams struct {
	Detail string `json:"detail"`
	ID     string `json:"id"`
}

func (q *Queries) AppendAgentTaskBlockerDetail(ctx context.Context, arg AppendAgentTaskBlockerDetailParams) error {
	_, err := q.db.ExecContext(ctx, appendAgentTaskBlockerDetail, arg.Detail, arg.ID)
	return err
}

const cancelAgentTaskBlocker = `-- name: CancelAgentTaskBlocker :execrows
UPDATE agent_task_blocker
SET status = 'cancelled', resolved_at = ?
WHERE id = ? AND status = 'open'
`

type CancelAgentTaskBlockerParams struct {
	ResolvedAt sql.NullString `json:"resolved_at"`
	ID         string         `json:"id"`
}

func (q *Queries) CancelAgentTaskBlocker(ctx context.Context, arg CancelAgentTaskBlockerParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, cancelAgentTaskBlocker, arg.ResolvedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createAgentTaskBlocker = `-- name: CreateAgentTaskBlocker :one

INSERT INTO agent_task_blocker (
    id, task_id, kind, status, question, detail, created_by_run_id, created_at
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, task_id, kind, status, question, detail, resolution, created_by_run_id, created_at, resolved_at
`

type CreateAgentTaskBlockerParams struct {
	ID             string         `json:"id"`
	TaskID         string         `json:"task_id"`
	Kind           string         `json:"kind"`
	Status         string         `json:"status"`
	Question       string         `json:"question"`
	Detail         string         `json:"detail"`
	CreatedByRunID sql.NullString `json:"created_by_run_id"`
	CreatedAt      string         `json:"created_at"`
}

// Blocker queries.
func (q *Queries) CreateAgentTaskBlocker(ctx context.Context, arg CreateAgentTaskBlockerParams) (AgentTaskBlocker, error) {
	row := q.db.QueryRowContext(ctx, createAgentTaskBlocker,
		arg.ID,
		arg.TaskID,
		arg.Kind,
		arg.Status,
		arg.Question,
		arg.Detail,
		arg.CreatedByRunID,
		arg.CreatedAt,
	)
	var i AgentTaskBlocker
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Kind,
		&i.Status,
		&i.Question,
		&i.Detail,
		&i.Resolution,
		&i.CreatedByRunID,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const getAgentTaskBlocker = `-- name: GetAgentTaskBlocker :one
SELECT id, task_id, kind, status, question, detail, resolution, created_by_run_id, created_at, resolved_at FROM agent_task_blocker WHERE id = ?
`

func (q *Queries) GetAgentTaskBlocker(ctx context.Context, id string) (AgentTaskBlocker, error) {
	row := q.db.QueryRowContext(ctx, getAgentTaskBlocker, id)
	var i AgentTaskBlocker
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Kind,
		&i.Status,
		&i.Question,
		&i.Detail,
		&i.Resolution,
		&i.CreatedByRunID,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const getOpenBlockerForTask = `-- name: GetOpenBlockerForTask :one
SELECT id, task_id, kind, status, question, detail, resolution, created_by_run_id, created_at, resolved_at FROM agent_task_blocker
WHERE task_id = ? AND status = 'open'
LIMIT 1
`

func (q *Queries) GetOpenBlockerForTask(ctx context.Context, taskID string) (AgentTaskBlocker, error) {
	row := q.db.QueryRowContext(ctx, getOpenBlockerForTask, taskID)
	var i AgentTaskBlocker
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Kind,
		&i.Status,
		&i.Question,
		&i.Detail,
		&i.Resolution,
		&i.CreatedByRunID,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const listAgentTaskBlockersByTask = `-- name: ListAgentTaskBlockersByTask :many
SELECT id, task_id, kind, status, question, detail, resolution, created_by_run_id, created_at, resolved_at FROM agent_task_blocker WHERE task_id = ? ORDER BY created_at DESC
`

func (q *Queries) ListAgentTaskBlockersByTask(ctx context.Context, taskID string) ([]AgentTaskBlocker, error) {
	rows, err := q.db.QueryContext(ctx, listAgentTaskBlockersByTask, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentTaskBlocker{}
	for rows.Next() {
		var i AgentTaskBlocker
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.Kind,
			&i.Status,
			&i.Question,
			&i.Detail,
			&i.Resolution,
			&i.CreatedByRunID,
			&i.CreatedAt,
			&i.ResolvedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveAgentTaskBlocker = `-- name: ResolveAgentTaskBlocker :execrows
UPDATE agent_task_blocker
SET status = 'resolved', resolution = ?, resolved_at = ?
WHERE id = ? AND status = 'open'
`

type ResolveAgentTaskBlockerParams struct {
	Resolution string         `json:"resolution"`
	ResolvedAt sql.NullString `json:"resolved_at"`
	ID         string         `json:"id"`
}

func (q *Queries) ResolveAgentTaskBlocker(ctx context.Context, arg ResolveAgentTaskBlockerParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, resolveAgentTaskBlocker, arg.Resolution, arg.ResolvedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
