// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: auth_user_token.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuthUserToken = `-- name: CreateAuthUserToken :one
INSERT INTO auth_user_token (
    id,
    user_id,
    name,
    token_hash,
    token_prefix,
    auto_generated,
    expires_at
) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, name, token_hash, token_prefix, auto_generated, last_used_at, expires_at, rotated_at, revoked_at, created_at, updated_at
`

type CreateAuthUserTokenParams struct {
	ID            string             `json:"id"`
	UserID        string             `json:"user_id"`
	Name          string             `json:"name"`
	TokenHash     string             `json:"token_hash"`
	TokenPrefix   string             `json:"token_prefix"`
	AutoGenerated bool               `json:"auto_generated"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateAuthUserToken(ctx context.Context, arg CreateAuthUserTokenParams) (AuthUserToken, error) {
	row := q.db.QueryRow(ctx, createAuthUserToken,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.TokenHash,
		arg.TokenPrefix,
		arg.AutoGenerated,
		arg.ExpiresAt,
	)
	var i AuthUserToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TokenHash,
		&i.TokenPrefix,
		&i.AutoGenerated,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RotatedAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveAuthUserTokenByHash = `-- name: GetActiveAuthUserTokenByHash :one
SELECT id, user_id, name, token_hash, token_prefix, auto_generated, last_used_at, expires_at, rotated_at, revoked_at, created_at, updated_at FROM auth_user_token
WHERE token_hash = $1
  AND revoked_at IS NULL
  AND (expires_at IS NULL OR expires_at > now())
`

func (q *Queries) GetActiveAuthUserTokenByHash(ctx context.Context, tokenHash string) (AuthUserToken, error) {
	row := q.db.QueryRow(ctx, getActiveAuthUserTokenByHash, tokenHash)
	var i AuthUserToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TokenHash,
		&i.TokenPrefix,
		&i.AutoGenerated,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RotatedAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveAutoAuthUserTokenByUser = `-- name: GetActiveAutoAuthUserTokenByUser :one
SELECT id, user_id, name, token_hash, token_prefix, auto_generated, last_used_at, expires_at, rotated_at, revoked_at, created_at, updated_at FROM auth_user_token
WHERE user_id = $1
  AND auto_generated = true
  AND revoked_at IS NULL
ORDER BY created_at DESC, id DESC
LIMIT 1
`

// expires_at is intentionally not filtered here: TokenService rotates at
// autoTokenRotateAfter (60 days), which is always before autoTokenTTL (90 days),
// so an auto token is replaced before it can expire. The Go layer handles
// time-based rotation rather than relying on the DB expiry column.
func (q *Queries) GetActiveAutoAuthUserTokenByUser(ctx context.Context, userID string) (AuthUserToken, error) {
	row := q.db.QueryRow(ctx, getActiveAutoAuthUserTokenByUser, userID)
	var i AuthUserToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TokenHash,
		&i.TokenPrefix,
		&i.AutoGenerated,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RotatedAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAuthUserTokenByHash = `-- name: GetAuthUserTokenByHash :one
SELECT id, user_id, name, token_hash, token_prefix, auto_generated, last_used_at, expires_at, rotated_at, revoked_at, created_at, updated_at FROM auth_user_token
WHERE token_hash = $1
`

func (q *Queries) GetAuthUserTokenByHash(ctx context.Context, tokenHash string) (AuthUserToken, error) {
	row := q.db.QueryRow(ctx, getAuthUserTokenByHash, tokenHash)
	var i AuthUserToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TokenHash,
		&i.TokenPrefix,
		&i.AutoGenerated,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RotatedAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const revokeAuthUserToken = `-- name: RevokeAuthUserToken :execrows
UPDATE auth_user_token
SET revoked_at = now(),
    updated_at = now()
WHERE id = $1
  AND revoked_at IS NULL
`

func (q *Queries) RevokeAuthUserToken(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAuthUserToken, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const rotateAuthUserToken = `-- name: RotateAuthUserToken :execrows
UPDATE auth_user_token
SET revoked_at = now(),
    rotated_at = now(),
    updated_at = now()
WHERE id = $1
  AND revoked_at IS NULL
  AND rotated_at IS NULL
`

func (q *Queries) RotateAuthUserToken(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, rotateAuthUserToken, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateAuthUserTokenLastUsed = `-- name: UpdateAuthUserTokenLastUsed :execrows
UPDATE auth_user_token
SET last_used_at = now(),
    updated_at = now()
WHERE id = $1
  AND (
      last_used_at IS NULL
      OR last_used_at <= now() - interval '5 minutes'
  )
`

func (q *Queries) UpdateAuthUserTokenLastUsed(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, updateAuthUserTokenLastUsed, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
