// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: auth_user_agent.sql

package sqlc

import (
	"context"
)

const assignUserAgent = `-- name: AssignUserAgent :exec
INSERT INTO auth_user_agent (user_id, agent_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AssignUserAgentParams struct {
	UserID  string `json:"user_id"`
	AgentID string `json:"agent_id"`
}

func (q *Queries) AssignUserAgent(ctx context.Context, arg AssignUserAgentParams) error {
	_, err := q.db.Exec(ctx, assignUserAgent, arg.UserID, arg.AgentID)
	return err
}

const assignUserAgentAndTouchAgent = `-- name: AssignUserAgentAndTouchAgent :exec
WITH assigned AS (
    INSERT INTO auth_user_agent (user_id, agent_id)
    VALUES ($1, $2)
    ON CONFLICT DO NOTHING
    RETURNING agent_id
)
UPDATE agent
SET updated_at = GREATEST(now(), updated_at + interval '1 microsecond')
WHERE id IN (SELECT agent_id FROM assigned)
`

type AssignUserAgentAndTouchAgentParams struct {
	UserID  string `json:"user_id"`
	AgentID string `json:"agent_id"`
}

func (q *Queries) AssignUserAgentAndTouchAgent(ctx context.Context, arg AssignUserAgentAndTouchAgentParams) error {
	_, err := q.db.Exec(ctx, assignUserAgentAndTouchAgent, arg.UserID, arg.AgentID)
	return err
}

const listAgentUsers = `-- name: ListAgentUsers :many
SELECT user_id FROM auth_user_agent WHERE agent_id = $1 ORDER BY user_id
`

func (q *Queries) ListAgentUsers(ctx context.Context, agentID string) ([]string, error) {
	rows, err := q.db.Query(ctx, listAgentUsers, agentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var user_id string
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserAgents = `-- name: ListUserAgents :many
SELECT agent_id FROM auth_user_agent WHERE user_id = $1 ORDER BY agent_id
`

func (q *Queries) ListUserAgents(ctx context.Context, userID string) ([]string, error) {
	rows, err := q.db.Query(ctx, listUserAgents, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var agent_id string
		if err := rows.Scan(&agent_id); err != nil {
			return nil, err
		}
		items = append(items, agent_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeUserAgent = `-- name: RemoveUserAgent :exec
DELETE FROM auth_user_agent WHERE user_id = $1 AND agent_id = $2
`

type RemoveUserAgentParams struct {
	UserID  string `json:"user_id"`
	AgentID string `json:"agent_id"`
}

func (q *Queries) RemoveUserAgent(ctx context.Context, arg RemoveUserAgentParams) error {
	_, err := q.db.Exec(ctx, removeUserAgent, arg.UserID, arg.AgentID)
	return err
}

const removeUserAgentAndTouchAgent = `-- name: RemoveUserAgentAndTouchAgent :exec
WITH removed AS (
    DELETE FROM auth_user_agent WHERE user_id = $1 AND agent_id = $2
    RETURNING agent_id
)
UPDATE agent
SET updated_at = GREATEST(now(), updated_at + interval '1 microsecond')
WHERE id IN (SELECT agent_id FROM removed)
`

type RemoveUserAgentAndTouchAgentParams struct {
	UserID  string `json:"user_id"`
	AgentID string `json:"agent_id"`
}

func (q *Queries) RemoveUserAgentAndTouchAgent(ctx context.Context, arg RemoveUserAgentAndTouchAgentParams) error {
	_, err := q.db.Exec(ctx, removeUserAgentAndTouchAgent, arg.UserID, arg.AgentID)
	return err
}
