// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: channel_fifo.sql

package sqlc

import (
	"context"
	"encoding/json"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const blockLinkedChannelFIFOItem = `-- name: BlockLinkedChannelFIFOItem :one
UPDATE channel_fifo_item
SET state = 'blocked',
    lease_owner = '',
    lease_expires_at = NULL,
    error_code = $1,
    error_detail = $2,
    updated_at = now()
WHERE id = $3::uuid
  AND run_id IS NOT NULL
  AND released_at IS NULL
  AND state IN ('pending', 'running', 'blocked')
RETURNING id, binding_id, principal_key, seq, source_key, schema_version, payload, payload_bytes, media_bytes, capability_bytes, byte_cost, command, args, state, attempt, lease_owner, lease_expires_at, next_attempt_at, run_id, expected_session_id, expected_binding_revision, result_text, result_handled, error_code, error_detail, rejected_by, rejected_reason, released_at, created_at, updated_at
`

type BlockLinkedChannelFIFOItemParams struct {
	ErrorCode   string `json:"error_code"`
	ErrorDetail string `json:"error_detail"`
	ID          string `json:"id"`
}

// A linked Run is never replayed.  This transition is the audit-preserving
// fallback when its terminal outcome was failed, canceled, interrupted, or
// unknown; an operator may later use RejectChannelFIFOItem to release it.
func (q *Queries) BlockLinkedChannelFIFOItem(ctx context.Context, arg BlockLinkedChannelFIFOItemParams) (ChannelFifoItem, error) {
	row := q.db.QueryRow(ctx, blockLinkedChannelFIFOItem, arg.ErrorCode, arg.ErrorDetail, arg.ID)
	var i ChannelFifoItem
	err := row.Scan(
		&i.ID,
		&i.BindingID,
		&i.PrincipalKey,
		&i.Seq,
		&i.SourceKey,
		&i.SchemaVersion,
		&i.Payload,
		&i.PayloadBytes,
		&i.MediaBytes,
		&i.CapabilityBytes,
		&i.ByteCost,
		&i.Command,
		&i.Args,
		&i.State,
		&i.Attempt,
		&i.LeaseOwner,
		&i.LeaseExpiresAt,
		&i.NextAttemptAt,
		&i.RunID,
		&i.ExpectedSessionID,
		&i.ExpectedBindingRevision,
		&i.ResultText,
		&i.ResultHandled,
		&i.ErrorCode,
		&i.ErrorDetail,
		&i.RejectedBy,
		&i.RejectedReason,
		&i.ReleasedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const claimNextChannelFIFOItem = `-- name: ClaimNextChannelFIFOItem :one
WITH candidate AS (
    SELECT item.id
    FROM channel_fifo_item AS item
    WHERE (
        (item.state = 'pending' AND item.next_attempt_at <= now())
        OR (item.state = 'running' AND item.lease_expires_at <= now())
    )
      AND item.run_id IS NULL
      AND NOT EXISTS (
          SELECT 1
          FROM channel_fifo_item AS prior
          WHERE prior.binding_id = item.binding_id
            AND prior.seq < item.seq
            AND prior.state NOT IN ('completed', 'rejected', 'discarded')
      )
    ORDER BY item.binding_id, item.seq
    FOR UPDATE SKIP LOCKED
    LIMIT 1
)
UPDATE channel_fifo_item AS item
SET state = 'running',
    attempt = item.attempt + 1,
    lease_owner = $1,
    lease_expires_at = now() + $2::double precision * interval '1 second',
    updated_at = now()
FROM candidate
WHERE item.id = candidate.id
RETURNING item.id, item.binding_id, item.principal_key, item.seq, item.source_key, item.schema_version, item.payload, item.payload_bytes, item.media_bytes, item.capability_bytes, item.byte_cost, item.command, item.args, item.state, item.attempt, item.lease_owner, item.lease_expires_at, item.next_attempt_at, item.run_id, item.expected_session_id, item.expected_binding_revision, item.result_text, item.result_handled, item.error_code, item.error_detail, item.rejected_by, item.rejected_reason, item.released_at, item.created_at, item.updated_at
`

type ClaimNextChannelFIFOItemParams struct {
	LeaseOwner   string  `json:"lease_owner"`
	LeaseSeconds float64 `json:"lease_seconds"`
}

// The candidate must be the oldest non-terminal item in its binding. A lease
// expiry makes an unlinked claim eligible again; linked AgentRuns are never
// reclaimed here because they follow the Run's terminal state instead of
// replaying a model turn.
func (q *Queries) ClaimNextChannelFIFOItem(ctx context.Context, arg ClaimNextChannelFIFOItemParams) (ChannelFifoItem, error) {
	row := q.db.QueryRow(ctx, claimNextChannelFIFOItem, arg.LeaseOwner, arg.LeaseSeconds)
	var i ChannelFifoItem
	err := row.Scan(
		&i.ID,
		&i.BindingID,
		&i.PrincipalKey,
		&i.Seq,
		&i.SourceKey,
		&i.SchemaVersion,
		&i.Payload,
		&i.PayloadBytes,
		&i.MediaBytes,
		&i.CapabilityBytes,
		&i.ByteCost,
		&i.Command,
		&i.Args,
		&i.State,
		&i.Attempt,
		&i.LeaseOwner,
		&i.LeaseExpiresAt,
		&i.NextAttemptAt,
		&i.RunID,
		&i.ExpectedSessionID,
		&i.ExpectedBindingRevision,
		&i.ResultText,
		&i.ResultHandled,
		&i.ErrorCode,
		&i.ErrorDetail,
		&i.RejectedBy,
		&i.RejectedReason,
		&i.ReleasedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const completeChannelFIFOItem = `-- name: CompleteChannelFIFOItem :one
UPDATE channel_fifo_item
SET state = 'completed',
    lease_owner = '',
    lease_expires_at = NULL,
    released_at = now(),
    updated_at = now()
WHERE id = $1::uuid
  AND state = 'running'
  AND lease_owner = $2
  AND released_at IS NULL
RETURNING id, binding_id, principal_key, seq, source_key, schema_version, payload, payload_bytes, media_bytes, capability_bytes, byte_cost, command, args, state, attempt, lease_owner, lease_expires_at, next_attempt_at, run_id, expected_session_id, expected_binding_revision, result_text, result_handled, error_code, error_detail, rejected_by, rejected_reason, released_at, created_at, updated_at
`

type CompleteChannelFIFOItemParams struct {
	ID         string `json:"id"`
	LeaseOwner string `json:"lease_owner"`
}

func (q *Queries) CompleteChannelFIFOItem(ctx context.Context, arg CompleteChannelFIFOItemParams) (ChannelFifoItem, error) {
	row := q.db.QueryRow(ctx, completeChannelFIFOItem, arg.ID, arg.LeaseOwner)
	var i ChannelFifoItem
	err := row.Scan(
		&i.ID,
		&i.BindingID,
		&i.PrincipalKey,
		&i.Seq,
		&i.SourceKey,
		&i.SchemaVersion,
		&i.Payload,
		&i.PayloadBytes,
		&i.MediaBytes,
		&i.CapabilityBytes,
		&i.ByteCost,
		&i.Command,
		&i.Args,
		&i.State,
		&i.Attempt,
		&i.LeaseOwner,
		&i.LeaseExpiresAt,
		&i.NextAttemptAt,
		&i.RunID,
		&i.ExpectedSessionID,
		&i.ExpectedBindingRevision,
		&i.ResultText,
		&i.ResultHandled,
		&i.ErrorCode,
		&i.ErrorDetail,
		&i.RejectedBy,
		&i.RejectedReason,
		&i.ReleasedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const completeLinkedChannelFIFOItem = `-- name: CompleteLinkedChannelFIFOItem :one
UPDATE channel_fifo_item
SET state = 'completed',
    lease_owner = '',
    lease_expires_at = NULL,
    released_at = now(),
    updated_at = now()
WHERE id = $1::uuid
  AND run_id IS NOT NULL
  AND released_at IS NULL
  AND state IN ('pending', 'running', 'blocked')
RETURNING id, binding_id, principal_key, seq, source_key, schema_version, payload, payload_bytes, media_bytes, capability_bytes, byte_cost, command, args, state, attempt, lease_owner, lease_expires_at, next_attempt_at, run_id, expected_session_id, expected_binding_revision, result_text, result_handled, error_code, error_detail, rejected_by, rejected_reason, released_at, created_at, updated_at
`

// A delivered terminal Run proves the adapter settled successfully before a
// crash in FIFO bookkeeping, so the item can be released without replaying
// model work.  Quota updates remain in the caller's ordered transaction.
func (q *Queries) CompleteLinkedChannelFIFOItem(ctx context.Context, id string) (ChannelFifoItem, error) {
	row := q.db.QueryRow(ctx, completeLinkedChannelFIFOItem, id)
	var i ChannelFifoItem
	err := row.Scan(
		&i.ID,
		&i.BindingID,
		&i.PrincipalKey,
		&i.Seq,
		&i.SourceKey,
		&i.SchemaVersion,
		&i.Payload,
		&i.PayloadBytes,
		&i.MediaBytes,
		&i.CapabilityBytes,
		&i.ByteCost,
		&i.Command,
		&i.Args,
		&i.State,
		&i.Attempt,
		&i.LeaseOwner,
		&i.LeaseExpiresAt,
		&i.NextAttemptAt,
		&i.RunID,
		&i.ExpectedSessionID,
		&i.ExpectedBindingRevision,
		&i.ResultText,
		&i.ResultHandled,
		&i.ErrorCode,
		&i.ErrorDetail,
		&i.RejectedBy,
		&i.RejectedReason,
		&i.ReleasedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const ensureChannelDeploymentQuota = `-- name: EnsureChannelDeploymentQuota :one
INSERT INTO channel_deployment_quota (channel_id, max_rows, max_bytes)
VALUES ($1, $2::bigint, $3::bigint)
ON CONFLICT (channel_id) DO UPDATE
SET updated_at = now()
RETURNING channel_id, max_rows, max_bytes, accepted_rows, accepted_bytes, released_rows, released_bytes, created_at, updated_at
`

type EnsureChannelDeploymentQuotaParams struct {
	ChannelID string `json:"channel_id"`
	MaxRows   int64  `json:"max_rows"`
	MaxBytes  int64  `json:"max_bytes"`
}

func (q *Queries) EnsureChannelDeploymentQuota(ctx context.Context, arg EnsureChannelDeploymentQuotaParams) (ChannelDeploymentQuotum, error) {
	row := q.db.QueryRow(ctx, ensureChannelDeploymentQuota, arg.ChannelID, arg.MaxRows, arg.MaxBytes)
	var i ChannelDeploymentQuotum
	err := row.Scan(
		&i.ChannelID,
		&i.MaxRows,
		&i.MaxBytes,
		&i.AcceptedRows,
		&i.AcceptedBytes,
		&i.ReleasedRows,
		&i.ReleasedBytes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const ensureChannelPrincipalQuota = `-- name: EnsureChannelPrincipalQuota :one
INSERT INTO channel_principal_quota (
    principal_key, principal_kind, principal_id, max_rows, max_bytes
)
VALUES (
    $1, $2, $3,
    $4::bigint, $5::bigint
)
ON CONFLICT (principal_key) DO UPDATE
SET principal_kind = excluded.principal_kind,
    principal_id = excluded.principal_id,
    updated_at = now()
RETURNING principal_key, principal_kind, principal_id, max_rows, max_bytes, accepted_rows, accepted_bytes, released_rows, released_bytes, created_at, updated_at
`

type EnsureChannelPrincipalQuotaParams struct {
	PrincipalKey  string `json:"principal_key"`
	PrincipalKind string `json:"principal_kind"`
	PrincipalID   string `json:"principal_id"`
	MaxRows       int64  `json:"max_rows"`
	MaxBytes      int64  `json:"max_bytes"`
}

func (q *Queries) EnsureChannelPrincipalQuota(ctx context.Context, arg EnsureChannelPrincipalQuotaParams) (ChannelPrincipalQuotum, error) {
	row := q.db.QueryRow(ctx, ensureChannelPrincipalQuota,
		arg.PrincipalKey,
		arg.PrincipalKind,
		arg.PrincipalID,
		arg.MaxRows,
		arg.MaxBytes,
	)
	var i ChannelPrincipalQuotum
	err := row.Scan(
		&i.PrincipalKey,
		&i.PrincipalKind,
		&i.PrincipalID,
		&i.MaxRows,
		&i.MaxBytes,
		&i.AcceptedRows,
		&i.AcceptedBytes,
		&i.ReleasedRows,
		&i.ReleasedBytes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getChannelDeploymentQuotaForUpdate = `-- name: GetChannelDeploymentQuotaForUpdate :one
SELECT channel_id, max_rows, max_bytes, accepted_rows, accepted_bytes, released_rows, released_bytes, created_at, updated_at
FROM channel_deployment_quota
WHERE channel_id = $1
FOR UPDATE
`

func (q *Queries) GetChannelDeploymentQuotaForUpdate(ctx context.Context, channelID string) (ChannelDeploymentQuotum, error) {
	row := q.db.QueryRow(ctx, getChannelDeploymentQuotaForUpdate, channelID)
	var i ChannelDeploymentQuotum
	err := row.Scan(
		&i.ChannelID,
		&i.MaxRows,
		&i.MaxBytes,
		&i.AcceptedRows,
		&i.AcceptedBytes,
		&i.ReleasedRows,
		&i.ReleasedBytes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getChannelFIFOItem = `-- name: GetChannelFIFOItem :one
SELECT id, binding_id, principal_key, seq, source_key, schema_version, payload, payload_bytes, media_bytes, capability_bytes, byte_cost, command, args, state, attempt, lease_owner, lease_expires_at, next_attempt_at, run_id, expected_session_id, expected_binding_revision, result_text, result_handled, error_code, error_detail, rejected_by, rejected_reason, released_at, created_at, updated_at FROM channel_fifo_item WHERE id = $1::uuid
`

func (q *Queries) GetChannelFIFOItem(ctx context.Context, id string) (ChannelFifoItem, error) {
	row := q.db.QueryRow(ctx, getChannelFIFOItem, id)
	var i ChannelFifoItem
	err := row.Scan(
		&i.ID,
		&i.BindingID,
		&i.PrincipalKey,
		&i.Seq,
		&i.SourceKey,
		&i.SchemaVersion,
		&i.Payload,
		&i.PayloadBytes,
		&i.MediaBytes,
		&i.CapabilityBytes,
		&i.ByteCost,
		&i.Command,
		&i.Args,
		&i.State,
		&i.Attempt,
		&i.LeaseOwner,
		&i.LeaseExpiresAt,
		&i.NextAttemptAt,
		&i.RunID,
		&i.ExpectedSessionID,
		&i.ExpectedBindingRevision,
		&i.ResultText,
		&i.ResultHandled,
		&i.ErrorCode,
		&i.ErrorDetail,
		&i.RejectedBy,
		&i.RejectedReason,
		&i.ReleasedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getChannelFIFOItemBySource = `-- name: GetChannelFIFOItemBySource :one
SELECT id, binding_id, principal_key, seq, source_key, schema_version, payload, payload_bytes, media_bytes, capability_bytes, byte_cost, command, args, state, attempt, lease_owner, lease_expires_at, next_attempt_at, run_id, expected_session_id, expected_binding_revision, result_text, result_handled, error_code, error_detail, rejected_by, rejected_reason, released_at, created_at, updated_at
FROM channel_fifo_item
WHERE binding_id = $1::uuid
  AND source_key = $2
`

type GetChannelFIFOItemBySourceParams struct {
	BindingID string `json:"binding_id"`
	SourceKey string `json:"source_key"`
}

func (q *Queries) GetChannelFIFOItemBySource(ctx context.Context, arg GetChannelFIFOItemBySourceParams) (ChannelFifoItem, error) {
	row := q.db.QueryRow(ctx, getChannelFIFOItemBySource, arg.BindingID, arg.SourceKey)
	var i ChannelFifoItem
	err := row.Scan(
		&i.ID,
		&i.BindingID,
		&i.PrincipalKey,
		&i.Seq,
		&i.SourceKey,
		&i.SchemaVersion,
		&i.Payload,
		&i.PayloadBytes,
		&i.MediaBytes,
		&i.CapabilityBytes,
		&i.ByteCost,
		&i.Command,
		&i.Args,
		&i.State,
		&i.Attempt,
		&i.LeaseOwner,
		&i.LeaseExpiresAt,
		&i.NextAttemptAt,
		&i.RunID,
		&i.ExpectedSessionID,
		&i.ExpectedBindingRevision,
		&i.ResultText,
		&i.ResultHandled,
		&i.ErrorCode,
		&i.ErrorDetail,
		&i.RejectedBy,
		&i.RejectedReason,
		&i.ReleasedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getChannelPrincipalQuotaForUpdate = `-- name: GetChannelPrincipalQuotaForUpdate :one
SELECT principal_key, principal_kind, principal_id, max_rows, max_bytes, accepted_rows, accepted_bytes, released_rows, released_bytes, created_at, updated_at
FROM channel_principal_quota
WHERE principal_key = $1
FOR UPDATE
`

func (q *Queries) GetChannelPrincipalQuotaForUpdate(ctx context.Context, principalKey string) (ChannelPrincipalQuotum, error) {
	row := q.db.QueryRow(ctx, getChannelPrincipalQuotaForUpdate, principalKey)
	var i ChannelPrincipalQuotum
	err := row.Scan(
		&i.PrincipalKey,
		&i.PrincipalKind,
		&i.PrincipalID,
		&i.MaxRows,
		&i.MaxBytes,
		&i.AcceptedRows,
		&i.AcceptedBytes,
		&i.ReleasedRows,
		&i.ReleasedBytes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertChannelFIFOItem = `-- name: InsertChannelFIFOItem :one
INSERT INTO channel_fifo_item (
    id, binding_id, principal_key, seq, source_key, schema_version, payload,
    payload_bytes, media_bytes, capability_bytes, byte_cost, command, args,
    expected_session_id, expected_binding_revision
)
VALUES (
    $1::uuid,
    $2::uuid,
    $3,
    $4::bigint,
    $5,
    $6::integer,
    $7::jsonb,
    $8::bigint,
    $9::bigint,
    $10::bigint,
    $11::bigint,
    $12,
    $13,
    NULLIF($14, ''),
    NULLIF($15, 0)::bigint
)
ON CONFLICT (binding_id, source_key) WHERE source_key <> '' DO NOTHING
RETURNING id, binding_id, principal_key, seq, source_key, schema_version, payload, payload_bytes, media_bytes, capability_bytes, byte_cost, command, args, state, attempt, lease_owner, lease_expires_at, next_attempt_at, run_id, expected_session_id, expected_binding_revision, result_text, result_handled, error_code, error_detail, rejected_by, rejected_reason, released_at, created_at, updated_at
`

type InsertChannelFIFOItemParams struct {
	ID                      string          `json:"id"`
	BindingID               string          `json:"binding_id"`
	PrincipalKey            string          `json:"principal_key"`
	Seq                     int64           `json:"seq"`
	SourceKey               string          `json:"source_key"`
	SchemaVersion           int32           `json:"schema_version"`
	Payload                 json.RawMessage `json:"payload"`
	PayloadBytes            int64           `json:"payload_bytes"`
	MediaBytes              int64           `json:"media_bytes"`
	CapabilityBytes         int64           `json:"capability_bytes"`
	ByteCost                int64           `json:"byte_cost"`
	Command                 string          `json:"command"`
	Args                    string          `json:"args"`
	ExpectedSessionID       interface{}     `json:"expected_session_id"`
	ExpectedBindingRevision interface{}     `json:"expected_binding_revision"`
}

func (q *Queries) InsertChannelFIFOItem(ctx context.Context, arg InsertChannelFIFOItemParams) (ChannelFifoItem, error) {
	row := q.db.QueryRow(ctx, insertChannelFIFOItem,
		arg.ID,
		arg.BindingID,
		arg.PrincipalKey,
		arg.Seq,
		arg.SourceKey,
		arg.SchemaVersion,
		arg.Payload,
		arg.PayloadBytes,
		arg.MediaBytes,
		arg.CapabilityBytes,
		arg.ByteCost,
		arg.Command,
		arg.Args,
		arg.ExpectedSessionID,
		arg.ExpectedBindingRevision,
	)
	var i ChannelFifoItem
	err := row.Scan(
		&i.ID,
		&i.BindingID,
		&i.PrincipalKey,
		&i.Seq,
		&i.SourceKey,
		&i.SchemaVersion,
		&i.Payload,
		&i.PayloadBytes,
		&i.MediaBytes,
		&i.CapabilityBytes,
		&i.ByteCost,
		&i.Command,
		&i.Args,
		&i.State,
		&i.Attempt,
		&i.LeaseOwner,
		&i.LeaseExpiresAt,
		&i.NextAttemptAt,
		&i.RunID,
		&i.ExpectedSessionID,
		&i.ExpectedBindingRevision,
		&i.ResultText,
		&i.ResultHandled,
		&i.ErrorCode,
		&i.ErrorDetail,
		&i.RejectedBy,
		&i.RejectedReason,
		&i.ReleasedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const linkChannelFIFOAgentRun = `-- name: LinkChannelFIFOAgentRun :execrows
UPDATE channel_fifo_item
SET run_id = $1::uuid,
    updated_at = now()
FROM channel_binding
WHERE channel_fifo_item.id = $2::uuid
  AND channel_fifo_item.binding_id = channel_binding.id
  AND channel_fifo_item.state = 'running'
  AND channel_fifo_item.lease_owner = $3
  AND channel_fifo_item.attempt = $4::integer
  AND channel_fifo_item.lease_expires_at > clock_timestamp()
  AND channel_fifo_item.run_id IS NULL
  AND (channel_fifo_item.expected_session_id IS NULL
       OR channel_fifo_item.expected_session_id = $5)
  AND channel_binding.revision = $6::bigint
  AND channel_binding.state = 'active'
`

type LinkChannelFIFOAgentRunParams struct {
	RunID           string      `json:"run_id"`
	ID              string      `json:"id"`
	LeaseOwner      string      `json:"lease_owner"`
	Attempt         int32       `json:"attempt"`
	SessionID       pgtype.Text `json:"session_id"`
	BindingRevision int64       `json:"binding_revision"`
}

func (q *Queries) LinkChannelFIFOAgentRun(ctx context.Context, arg LinkChannelFIFOAgentRunParams) (int64, error) {
	result, err := q.db.Exec(ctx, linkChannelFIFOAgentRun,
		arg.RunID,
		arg.ID,
		arg.LeaseOwner,
		arg.Attempt,
		arg.SessionID,
		arg.BindingRevision,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listLinkedChannelFIFOItemsNeedingRunRecovery = `-- name: ListLinkedChannelFIFOItemsNeedingRunRecovery :many
SELECT item.id, item.binding_id, item.principal_key, item.seq, item.source_key, item.schema_version, item.payload, item.payload_bytes, item.media_bytes, item.capability_bytes, item.byte_cost, item.command, item.args, item.state, item.attempt, item.lease_owner, item.lease_expires_at, item.next_attempt_at, item.run_id, item.expected_session_id, item.expected_binding_revision, item.result_text, item.result_handled, item.error_code, item.error_detail, item.rejected_by, item.rejected_reason, item.released_at, item.created_at, item.updated_at, run.status AS run_status, run.completion_outcome AS run_completion_outcome
FROM channel_fifo_item AS item
JOIN agent_run AS run ON run.id = item.run_id
WHERE item.released_at IS NULL
  AND item.state IN ('pending', 'running', 'blocked')
  AND run.status <> 'running'
ORDER BY item.binding_id, item.seq
`

type ListLinkedChannelFIFOItemsNeedingRunRecoveryRow struct {
	ID                      string             `json:"id"`
	BindingID               string             `json:"binding_id"`
	PrincipalKey            string             `json:"principal_key"`
	Seq                     int64              `json:"seq"`
	SourceKey               string             `json:"source_key"`
	SchemaVersion           int32              `json:"schema_version"`
	Payload                 json.RawMessage    `json:"payload"`
	PayloadBytes            int64              `json:"payload_bytes"`
	MediaBytes              int64              `json:"media_bytes"`
	CapabilityBytes         int64              `json:"capability_bytes"`
	ByteCost                int64              `json:"byte_cost"`
	Command                 string             `json:"command"`
	Args                    string             `json:"args"`
	State                   string             `json:"state"`
	Attempt                 int32              `json:"attempt"`
	LeaseOwner              string             `json:"lease_owner"`
	LeaseExpiresAt          pgtype.Timestamptz `json:"lease_expires_at"`
	NextAttemptAt           time.Time          `json:"next_attempt_at"`
	RunID                   pgtype.Text        `json:"run_id"`
	ExpectedSessionID       pgtype.Text        `json:"expected_session_id"`
	ExpectedBindingRevision pgtype.Int8        `json:"expected_binding_revision"`
	ResultText              string             `json:"result_text"`
	ResultHandled           bool               `json:"result_handled"`
	ErrorCode               string             `json:"error_code"`
	ErrorDetail             string             `json:"error_detail"`
	RejectedBy              string             `json:"rejected_by"`
	RejectedReason          string             `json:"rejected_reason"`
	ReleasedAt              pgtype.Timestamptz `json:"released_at"`
	CreatedAt               time.Time          `json:"created_at"`
	UpdatedAt               time.Time          `json:"updated_at"`
	RunStatus               string             `json:"run_status"`
	RunCompletionOutcome    string             `json:"run_completion_outcome"`
}

func (q *Queries) ListLinkedChannelFIFOItemsNeedingRunRecovery(ctx context.Context) ([]ListLinkedChannelFIFOItemsNeedingRunRecoveryRow, error) {
	rows, err := q.db.Query(ctx, listLinkedChannelFIFOItemsNeedingRunRecovery)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLinkedChannelFIFOItemsNeedingRunRecoveryRow{}
	for rows.Next() {
		var i ListLinkedChannelFIFOItemsNeedingRunRecoveryRow
		if err := rows.Scan(
			&i.ID,
			&i.BindingID,
			&i.PrincipalKey,
			&i.Seq,
			&i.SourceKey,
			&i.SchemaVersion,
			&i.Payload,
			&i.PayloadBytes,
			&i.MediaBytes,
			&i.CapabilityBytes,
			&i.ByteCost,
			&i.Command,
			&i.Args,
			&i.State,
			&i.Attempt,
			&i.LeaseOwner,
			&i.LeaseExpiresAt,
			&i.NextAttemptAt,
			&i.RunID,
			&i.ExpectedSessionID,
			&i.ExpectedBindingRevision,
			&i.ResultText,
			&i.ResultHandled,
			&i.ErrorCode,
			&i.ErrorDetail,
			&i.RejectedBy,
			&i.RejectedReason,
			&i.ReleasedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RunStatus,
			&i.RunCompletionOutcome,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reapExpiredUnlinkedChannelFIFOItems = `-- name: ReapExpiredUnlinkedChannelFIFOItems :many
UPDATE channel_fifo_item
SET state = 'pending',
    lease_owner = '',
    lease_expires_at = NULL,
    error_code = 'lease_expired',
    error_detail = 'executor lease expired before AgentRun link',
    updated_at = now()
WHERE state = 'running'
  AND run_id IS NULL
  AND lease_expires_at IS NOT NULL
  AND lease_expires_at <= now()
RETURNING id, binding_id, principal_key, seq, source_key, schema_version, payload, payload_bytes, media_bytes, capability_bytes, byte_cost, command, args, state, attempt, lease_owner, lease_expires_at, next_attempt_at, run_id, expected_session_id, expected_binding_revision, result_text, result_handled, error_code, error_detail, rejected_by, rejected_reason, released_at, created_at, updated_at
`

// Expiry recovery is intentionally limited to unlinked work.  A linked item
// is reconciled from AgentRun and cannot be claimed as a fresh model turn.
func (q *Queries) ReapExpiredUnlinkedChannelFIFOItems(ctx context.Context) ([]ChannelFifoItem, error) {
	rows, err := q.db.Query(ctx, reapExpiredUnlinkedChannelFIFOItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChannelFifoItem{}
	for rows.Next() {
		var i ChannelFifoItem
		if err := rows.Scan(
			&i.ID,
			&i.BindingID,
			&i.PrincipalKey,
			&i.Seq,
			&i.SourceKey,
			&i.SchemaVersion,
			&i.Payload,
			&i.PayloadBytes,
			&i.MediaBytes,
			&i.CapabilityBytes,
			&i.ByteCost,
			&i.Command,
			&i.Args,
			&i.State,
			&i.Attempt,
			&i.LeaseOwner,
			&i.LeaseExpiresAt,
			&i.NextAttemptAt,
			&i.RunID,
			&i.ExpectedSessionID,
			&i.ExpectedBindingRevision,
			&i.ResultText,
			&i.ResultHandled,
			&i.ErrorCode,
			&i.ErrorDetail,
			&i.RejectedBy,
			&i.RejectedReason,
			&i.ReleasedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rejectChannelFIFOItem = `-- name: RejectChannelFIFOItem :one
UPDATE channel_fifo_item
SET state = 'rejected',
    lease_owner = '',
    lease_expires_at = NULL,
    rejected_by = $1,
    rejected_reason = $2,
    released_at = now(),
    updated_at = now()
WHERE id = $3::uuid
  AND state IN ('pending', 'running', 'blocked')
  AND (state <> 'running' OR lease_owner = $4)
  AND released_at IS NULL
RETURNING id, binding_id, principal_key, seq, source_key, schema_version, payload, payload_bytes, media_bytes, capability_bytes, byte_cost, command, args, state, attempt, lease_owner, lease_expires_at, next_attempt_at, run_id, expected_session_id, expected_binding_revision, result_text, result_handled, error_code, error_detail, rejected_by, rejected_reason, released_at, created_at, updated_at
`

type RejectChannelFIFOItemParams struct {
	RejectedBy     string `json:"rejected_by"`
	RejectedReason string `json:"rejected_reason"`
	ID             string `json:"id"`
	LeaseOwner     string `json:"lease_owner"`
}

func (q *Queries) RejectChannelFIFOItem(ctx context.Context, arg RejectChannelFIFOItemParams) (ChannelFifoItem, error) {
	row := q.db.QueryRow(ctx, rejectChannelFIFOItem,
		arg.RejectedBy,
		arg.RejectedReason,
		arg.ID,
		arg.LeaseOwner,
	)
	var i ChannelFifoItem
	err := row.Scan(
		&i.ID,
		&i.BindingID,
		&i.PrincipalKey,
		&i.Seq,
		&i.SourceKey,
		&i.SchemaVersion,
		&i.Payload,
		&i.PayloadBytes,
		&i.MediaBytes,
		&i.CapabilityBytes,
		&i.ByteCost,
		&i.Command,
		&i.Args,
		&i.State,
		&i.Attempt,
		&i.LeaseOwner,
		&i.LeaseExpiresAt,
		&i.NextAttemptAt,
		&i.RunID,
		&i.ExpectedSessionID,
		&i.ExpectedBindingRevision,
		&i.ResultText,
		&i.ResultHandled,
		&i.ErrorCode,
		&i.ErrorDetail,
		&i.RejectedBy,
		&i.RejectedReason,
		&i.ReleasedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const releaseChannelBindingQuota = `-- name: ReleaseChannelBindingQuota :execrows
UPDATE channel_binding
SET released_rows = released_rows + 1,
    released_bytes = released_bytes + $1::bigint,
    updated_at = now()
WHERE id = $2::uuid
  AND accepted_rows >= released_rows + 1
  AND accepted_bytes >= released_bytes + $1::bigint
`

type ReleaseChannelBindingQuotaParams struct {
	ByteCost  int64  `json:"byte_cost"`
	BindingID string `json:"binding_id"`
}

func (q *Queries) ReleaseChannelBindingQuota(ctx context.Context, arg ReleaseChannelBindingQuotaParams) (int64, error) {
	result, err := q.db.Exec(ctx, releaseChannelBindingQuota, arg.ByteCost, arg.BindingID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const releaseChannelDeploymentQuota = `-- name: ReleaseChannelDeploymentQuota :execrows
UPDATE channel_deployment_quota
SET released_rows = released_rows + 1,
    released_bytes = released_bytes + $1::bigint,
    updated_at = now()
WHERE channel_id = $2
  AND accepted_rows >= released_rows + 1
  AND accepted_bytes >= released_bytes + $1::bigint
`

type ReleaseChannelDeploymentQuotaParams struct {
	ByteCost  int64  `json:"byte_cost"`
	ChannelID string `json:"channel_id"`
}

func (q *Queries) ReleaseChannelDeploymentQuota(ctx context.Context, arg ReleaseChannelDeploymentQuotaParams) (int64, error) {
	result, err := q.db.Exec(ctx, releaseChannelDeploymentQuota, arg.ByteCost, arg.ChannelID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const releaseChannelPrincipalQuota = `-- name: ReleaseChannelPrincipalQuota :execrows
UPDATE channel_principal_quota
SET released_rows = released_rows + 1,
    released_bytes = released_bytes + $1::bigint,
    updated_at = now()
WHERE principal_key = $2
  AND accepted_rows >= released_rows + 1
  AND accepted_bytes >= released_bytes + $1::bigint
`

type ReleaseChannelPrincipalQuotaParams struct {
	ByteCost     int64  `json:"byte_cost"`
	PrincipalKey string `json:"principal_key"`
}

func (q *Queries) ReleaseChannelPrincipalQuota(ctx context.Context, arg ReleaseChannelPrincipalQuotaParams) (int64, error) {
	result, err := q.db.Exec(ctx, releaseChannelPrincipalQuota, arg.ByteCost, arg.PrincipalKey)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const reserveChannelBindingQuota = `-- name: ReserveChannelBindingQuota :execrows
UPDATE channel_binding
SET accepted_rows = accepted_rows + 1,
    accepted_bytes = accepted_bytes + $1::bigint,
    updated_at = now()
WHERE id = $2::uuid
  AND accepted_rows - released_rows + 1 <= max_rows
  AND accepted_bytes - released_bytes + $1::bigint <= max_bytes
`

type ReserveChannelBindingQuotaParams struct {
	ByteCost  int64  `json:"byte_cost"`
	BindingID string `json:"binding_id"`
}

func (q *Queries) ReserveChannelBindingQuota(ctx context.Context, arg ReserveChannelBindingQuotaParams) (int64, error) {
	result, err := q.db.Exec(ctx, reserveChannelBindingQuota, arg.ByteCost, arg.BindingID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const reserveChannelDeploymentQuota = `-- name: ReserveChannelDeploymentQuota :execrows
UPDATE channel_deployment_quota
SET accepted_rows = accepted_rows + 1,
    accepted_bytes = accepted_bytes + $1::bigint,
    updated_at = now()
WHERE channel_id = $2
  AND accepted_rows - released_rows + 1 <= max_rows
  AND accepted_bytes - released_bytes + $1::bigint <= max_bytes
`

type ReserveChannelDeploymentQuotaParams struct {
	ByteCost  int64  `json:"byte_cost"`
	ChannelID string `json:"channel_id"`
}

func (q *Queries) ReserveChannelDeploymentQuota(ctx context.Context, arg ReserveChannelDeploymentQuotaParams) (int64, error) {
	result, err := q.db.Exec(ctx, reserveChannelDeploymentQuota, arg.ByteCost, arg.ChannelID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const reserveChannelPrincipalQuota = `-- name: ReserveChannelPrincipalQuota :execrows
UPDATE channel_principal_quota
SET accepted_rows = accepted_rows + 1,
    accepted_bytes = accepted_bytes + $1::bigint,
    updated_at = now()
WHERE principal_key = $2
  AND accepted_rows - released_rows + 1 <= max_rows
  AND accepted_bytes - released_bytes + $1::bigint <= max_bytes
`

type ReserveChannelPrincipalQuotaParams struct {
	ByteCost     int64  `json:"byte_cost"`
	PrincipalKey string `json:"principal_key"`
}

func (q *Queries) ReserveChannelPrincipalQuota(ctx context.Context, arg ReserveChannelPrincipalQuotaParams) (int64, error) {
	result, err := q.db.Exec(ctx, reserveChannelPrincipalQuota, arg.ByteCost, arg.PrincipalKey)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const retryChannelFIFOItem = `-- name: RetryChannelFIFOItem :one
UPDATE channel_fifo_item
SET state = CASE
        -- The Go item is a claim snapshot.  AgentRun linking happens in a
        -- separate admission transaction, so the database row is the only
        -- authoritative answer when deciding whether retry may replay work.
        WHEN $1::boolean OR run_id IS NOT NULL THEN 'blocked'
        ELSE 'pending'
    END,
    lease_owner = '',
    lease_expires_at = NULL,
    next_attempt_at = $2::timestamptz,
    error_code = $3,
    error_detail = $4,
    updated_at = now()
WHERE id = $5::uuid
  AND state = 'running'
  AND lease_owner = $6
  AND released_at IS NULL
RETURNING id, binding_id, principal_key, seq, source_key, schema_version, payload, payload_bytes, media_bytes, capability_bytes, byte_cost, command, args, state, attempt, lease_owner, lease_expires_at, next_attempt_at, run_id, expected_session_id, expected_binding_revision, result_text, result_handled, error_code, error_detail, rejected_by, rejected_reason, released_at, created_at, updated_at
`

type RetryChannelFIFOItemParams struct {
	Block         bool      `json:"block"`
	NextAttemptAt time.Time `json:"next_attempt_at"`
	ErrorCode     string    `json:"error_code"`
	ErrorDetail   string    `json:"error_detail"`
	ID            string    `json:"id"`
	LeaseOwner    string    `json:"lease_owner"`
}

func (q *Queries) RetryChannelFIFOItem(ctx context.Context, arg RetryChannelFIFOItemParams) (ChannelFifoItem, error) {
	row := q.db.QueryRow(ctx, retryChannelFIFOItem,
		arg.Block,
		arg.NextAttemptAt,
		arg.ErrorCode,
		arg.ErrorDetail,
		arg.ID,
		arg.LeaseOwner,
	)
	var i ChannelFifoItem
	err := row.Scan(
		&i.ID,
		&i.BindingID,
		&i.PrincipalKey,
		&i.Seq,
		&i.SourceKey,
		&i.SchemaVersion,
		&i.Payload,
		&i.PayloadBytes,
		&i.MediaBytes,
		&i.CapabilityBytes,
		&i.ByteCost,
		&i.Command,
		&i.Args,
		&i.State,
		&i.Attempt,
		&i.LeaseOwner,
		&i.LeaseExpiresAt,
		&i.NextAttemptAt,
		&i.RunID,
		&i.ExpectedSessionID,
		&i.ExpectedBindingRevision,
		&i.ResultText,
		&i.ResultHandled,
		&i.ErrorCode,
		&i.ErrorDetail,
		&i.RejectedBy,
		&i.RejectedReason,
		&i.ReleasedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setChannelFIFOResult = `-- name: SetChannelFIFOResult :execrows
UPDATE channel_fifo_item
SET result_text = $1,
    result_handled = $2,
    updated_at = now()
WHERE id = $3::uuid
  AND state = 'running'
  AND lease_owner = $4
`

type SetChannelFIFOResultParams struct {
	ResultText    string `json:"result_text"`
	ResultHandled bool   `json:"result_handled"`
	ID            string `json:"id"`
	LeaseOwner    string `json:"lease_owner"`
}

func (q *Queries) SetChannelFIFOResult(ctx context.Context, arg SetChannelFIFOResultParams) (int64, error) {
	result, err := q.db.Exec(ctx, setChannelFIFOResult,
		arg.ResultText,
		arg.ResultHandled,
		arg.ID,
		arg.LeaseOwner,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
