// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: channel_ingress_lease.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acquireChannelIngressLease = `-- name: AcquireChannelIngressLease :one
UPDATE channel_ingress_lease
SET owner_id = $1,
    acquired_at = CASE
        WHEN owner_id = $1 THEN acquired_at
        ELSE now()
    END,
    heartbeat_at = now(),
    lease_expires_at = now() + make_interval(secs => $2::double precision),
    updated_at = now()
WHERE id = 1
  AND (
        owner_id = $1
     OR owner_id = ''
     OR lease_expires_at IS NULL
     OR lease_expires_at < now()
  )
RETURNING owner_id, lease_expires_at
`

type AcquireChannelIngressLeaseParams struct {
	OwnerID    string  `json:"owner_id"`
	TtlSeconds float64 `json:"ttl_seconds"`
}

type AcquireChannelIngressLeaseRow struct {
	OwnerID        string             `json:"owner_id"`
	LeaseExpiresAt pgtype.Timestamptz `json:"lease_expires_at"`
}

// Atomic acquire-or-renew CAS against the single lease row. Succeeds (returns a
// row) when this replica already holds the lease, when the lease is free, or when
// the current holder's lease has expired; returns no rows when another replica
// holds a live lease. acquired_at is preserved across renewals by the same owner
// and reset to now() on a fresh acquisition. lease_expires_at is computed from the
// DATABASE clock so expiry is comparable across replicas regardless of local skew.
func (q *Queries) AcquireChannelIngressLease(ctx context.Context, arg AcquireChannelIngressLeaseParams) (AcquireChannelIngressLeaseRow, error) {
	row := q.db.QueryRow(ctx, acquireChannelIngressLease, arg.OwnerID, arg.TtlSeconds)
	var i AcquireChannelIngressLeaseRow
	err := row.Scan(&i.OwnerID, &i.LeaseExpiresAt)
	return i, err
}

const getChannelIngressLease = `-- name: GetChannelIngressLease :one
SELECT id, owner_id, acquired_at, heartbeat_at, lease_expires_at, updated_at FROM channel_ingress_lease WHERE id = 1
`

// Read the singleton lease row (observability + tests).
func (q *Queries) GetChannelIngressLease(ctx context.Context) (ChannelIngressLease, error) {
	row := q.db.QueryRow(ctx, getChannelIngressLease)
	var i ChannelIngressLease
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.AcquiredAt,
		&i.HeartbeatAt,
		&i.LeaseExpiresAt,
		&i.UpdatedAt,
	)
	return i, err
}

const releaseChannelIngressLease = `-- name: ReleaseChannelIngressLease :execrows
UPDATE channel_ingress_lease
SET owner_id = '',
    lease_expires_at = now(),
    updated_at = now()
WHERE id = 1 AND owner_id = $1
`

// Graceful release on shutdown: frees the lease so a peer can acquire immediately
// (no waiting for expiry). Guarded by owner_id so a replica can only release a
// lease it still holds — a stale ex-holder cannot free a lease a peer has taken.
func (q *Queries) ReleaseChannelIngressLease(ctx context.Context, ownerID string) (int64, error) {
	result, err := q.db.Exec(ctx, releaseChannelIngressLease, ownerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
