// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: ctx_summary.sql

package sqlc

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
	pgvector_go "github.com/pgvector/pgvector-go"
)

const createSummary = `-- name: CreateSummary :exec
INSERT INTO ctx_summary (id, conversation_id, kind, depth, content, token_count, earliest_at, latest_at, descendant_count, descendant_token_count, source_message_token_count, contains_non_principal_input)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
`

type CreateSummaryParams struct {
	ID                        string             `json:"id"`
	ConversationID            string             `json:"conversation_id"`
	Kind                      string             `json:"kind"`
	Depth                     int64              `json:"depth"`
	Content                   string             `json:"content"`
	TokenCount                int64              `json:"token_count"`
	EarliestAt                pgtype.Timestamptz `json:"earliest_at"`
	LatestAt                  pgtype.Timestamptz `json:"latest_at"`
	DescendantCount           int64              `json:"descendant_count"`
	DescendantTokenCount      int64              `json:"descendant_token_count"`
	SourceMessageTokenCount   int64              `json:"source_message_token_count"`
	ContainsNonPrincipalInput bool               `json:"contains_non_principal_input"`
}

func (q *Queries) CreateSummary(ctx context.Context, arg CreateSummaryParams) error {
	_, err := q.db.Exec(ctx, createSummary,
		arg.ID,
		arg.ConversationID,
		arg.Kind,
		arg.Depth,
		arg.Content,
		arg.TokenCount,
		arg.EarliestAt,
		arg.LatestAt,
		arg.DescendantCount,
		arg.DescendantTokenCount,
		arg.SourceMessageTokenCount,
		arg.ContainsNonPrincipalInput,
	)
	return err
}

const getSummariesByConversation = `-- name: GetSummariesByConversation :many
SELECT id, conversation_id, kind, depth, content, token_count, earliest_at, latest_at, descendant_count, descendant_token_count, source_message_token_count, created_at, contains_non_principal_input FROM ctx_summary WHERE conversation_id = $1 ORDER BY created_at ASC
`

func (q *Queries) GetSummariesByConversation(ctx context.Context, conversationID string) ([]CtxSummary, error) {
	rows, err := q.db.Query(ctx, getSummariesByConversation, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CtxSummary{}
	for rows.Next() {
		var i CtxSummary
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.Kind,
			&i.Depth,
			&i.Content,
			&i.TokenCount,
			&i.EarliestAt,
			&i.LatestAt,
			&i.DescendantCount,
			&i.DescendantTokenCount,
			&i.SourceMessageTokenCount,
			&i.CreatedAt,
			&i.ContainsNonPrincipalInput,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSummariesByDepth = `-- name: GetSummariesByDepth :many
SELECT id, conversation_id, kind, depth, content, token_count, earliest_at, latest_at, descendant_count, descendant_token_count, source_message_token_count, created_at, contains_non_principal_input FROM ctx_summary
WHERE conversation_id = $1 AND depth = $2
ORDER BY created_at ASC
`

type GetSummariesByDepthParams struct {
	ConversationID string `json:"conversation_id"`
	Depth          int64  `json:"depth"`
}

func (q *Queries) GetSummariesByDepth(ctx context.Context, arg GetSummariesByDepthParams) ([]CtxSummary, error) {
	rows, err := q.db.Query(ctx, getSummariesByDepth, arg.ConversationID, arg.Depth)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CtxSummary{}
	for rows.Next() {
		var i CtxSummary
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.Kind,
			&i.Depth,
			&i.Content,
			&i.TokenCount,
			&i.EarliestAt,
			&i.LatestAt,
			&i.DescendantCount,
			&i.DescendantTokenCount,
			&i.SourceMessageTokenCount,
			&i.CreatedAt,
			&i.ContainsNonPrincipalInput,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSummary = `-- name: GetSummary :one
SELECT id, conversation_id, kind, depth, content, token_count, earliest_at, latest_at, descendant_count, descendant_token_count, source_message_token_count, created_at, contains_non_principal_input FROM ctx_summary WHERE id = $1 AND conversation_id = $2
`

type GetSummaryParams struct {
	ID             string `json:"id"`
	ConversationID string `json:"conversation_id"`
}

func (q *Queries) GetSummary(ctx context.Context, arg GetSummaryParams) (CtxSummary, error) {
	row := q.db.QueryRow(ctx, getSummary, arg.ID, arg.ConversationID)
	var i CtxSummary
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.Kind,
		&i.Depth,
		&i.Content,
		&i.TokenCount,
		&i.EarliestAt,
		&i.LatestAt,
		&i.DescendantCount,
		&i.DescendantTokenCount,
		&i.SourceMessageTokenCount,
		&i.CreatedAt,
		&i.ContainsNonPrincipalInput,
	)
	return i, err
}

const getSummaryByID = `-- name: GetSummaryByID :one
SELECT id, conversation_id, kind, depth, content, token_count, earliest_at, latest_at, descendant_count, descendant_token_count, source_message_token_count, created_at, contains_non_principal_input FROM ctx_summary WHERE id = $1
`

func (q *Queries) GetSummaryByID(ctx context.Context, id string) (CtxSummary, error) {
	row := q.db.QueryRow(ctx, getSummaryByID, id)
	var i CtxSummary
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.Kind,
		&i.Depth,
		&i.Content,
		&i.TokenCount,
		&i.EarliestAt,
		&i.LatestAt,
		&i.DescendantCount,
		&i.DescendantTokenCount,
		&i.SourceMessageTokenCount,
		&i.CreatedAt,
		&i.ContainsNonPrincipalInput,
	)
	return i, err
}

const getSummaryChildren = `-- name: GetSummaryChildren :many
SELECT s.id, s.conversation_id, s.kind, s.depth, s.content, s.token_count, s.earliest_at, s.latest_at, s.descendant_count, s.descendant_token_count, s.source_message_token_count, s.created_at, s.contains_non_principal_input FROM ctx_summary s
JOIN ctx_summary_parent sp ON sp.summary_id = s.id
WHERE sp.parent_summary_id = $1
ORDER BY sp.ordinal ASC
`

func (q *Queries) GetSummaryChildren(ctx context.Context, parentSummaryID string) ([]CtxSummary, error) {
	rows, err := q.db.Query(ctx, getSummaryChildren, parentSummaryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CtxSummary{}
	for rows.Next() {
		var i CtxSummary
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.Kind,
			&i.Depth,
			&i.Content,
			&i.TokenCount,
			&i.EarliestAt,
			&i.LatestAt,
			&i.DescendantCount,
			&i.DescendantTokenCount,
			&i.SourceMessageTokenCount,
			&i.CreatedAt,
			&i.ContainsNonPrincipalInput,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSummaryMessageSeqRange = `-- name: GetSummaryMessageSeqRange :one
SELECT
  CAST(COALESCE(MIN(m.seq), 0) AS BIGINT) AS message_seq_from,
  CAST(COALESCE(MAX(m.seq), 0) AS BIGINT) AS message_seq_to
FROM ctx_summary_message sm
JOIN ctx_message m ON sm.message_id = m.id
WHERE sm.summary_id = $1
`

type GetSummaryMessageSeqRangeRow struct {
	MessageSeqFrom int64 `json:"message_seq_from"`
	MessageSeqTo   int64 `json:"message_seq_to"`
}

func (q *Queries) GetSummaryMessageSeqRange(ctx context.Context, summaryID string) (GetSummaryMessageSeqRangeRow, error) {
	row := q.db.QueryRow(ctx, getSummaryMessageSeqRange, summaryID)
	var i GetSummaryMessageSeqRangeRow
	err := row.Scan(&i.MessageSeqFrom, &i.MessageSeqTo)
	return i, err
}

const getSummaryMessages = `-- name: GetSummaryMessages :many
SELECT m.id, m.conversation_id, m.seq, m.role, m.event_type, m.content, m.token_count, m.created_at, m.actor_type, m.actor_id, m.source_session_id, m.inbox_id FROM ctx_message m
JOIN ctx_summary_message sm ON sm.message_id = m.id
WHERE sm.summary_id = $1
ORDER BY sm.ordinal ASC
`

func (q *Queries) GetSummaryMessages(ctx context.Context, summaryID string) ([]CtxMessage, error) {
	rows, err := q.db.Query(ctx, getSummaryMessages, summaryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CtxMessage{}
	for rows.Next() {
		var i CtxMessage
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.Seq,
			&i.Role,
			&i.EventType,
			&i.Content,
			&i.TokenCount,
			&i.CreatedAt,
			&i.ActorType,
			&i.ActorID,
			&i.SourceSessionID,
			&i.InboxID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSummaryParents = `-- name: GetSummaryParents :many
SELECT s.id, s.conversation_id, s.kind, s.depth, s.content, s.token_count, s.earliest_at, s.latest_at, s.descendant_count, s.descendant_token_count, s.source_message_token_count, s.created_at, s.contains_non_principal_input FROM ctx_summary s
JOIN ctx_summary_parent sp ON sp.parent_summary_id = s.id
WHERE sp.summary_id = $1
ORDER BY sp.ordinal ASC
`

// Legacy naming note: compaction stores the containing condensed summary in
// summary_id and each constituent summary in parent_summary_id. Consequently,
// GetSummaryParents returns conceptual children/constituents, while
// GetSummaryChildren returns conceptual parents/containers.
func (q *Queries) GetSummaryParents(ctx context.Context, summaryID string) ([]CtxSummary, error) {
	rows, err := q.db.Query(ctx, getSummaryParents, summaryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CtxSummary{}
	for rows.Next() {
		var i CtxSummary
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.Kind,
			&i.Depth,
			&i.Content,
			&i.TokenCount,
			&i.EarliestAt,
			&i.LatestAt,
			&i.DescendantCount,
			&i.DescendantTokenCount,
			&i.SourceMessageTokenCount,
			&i.CreatedAt,
			&i.ContainsNonPrincipalInput,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const linkSummaryToMessage = `-- name: LinkSummaryToMessage :exec
INSERT INTO ctx_summary_message (summary_id, message_id, ordinal)
VALUES ($1, $2, $3)
`

type LinkSummaryToMessageParams struct {
	SummaryID string `json:"summary_id"`
	MessageID string `json:"message_id"`
	Ordinal   int64  `json:"ordinal"`
}

func (q *Queries) LinkSummaryToMessage(ctx context.Context, arg LinkSummaryToMessageParams) error {
	_, err := q.db.Exec(ctx, linkSummaryToMessage, arg.SummaryID, arg.MessageID, arg.Ordinal)
	return err
}

const linkSummaryToParent = `-- name: LinkSummaryToParent :exec
INSERT INTO ctx_summary_parent (summary_id, parent_summary_id, ordinal)
VALUES ($1, $2, $3)
`

type LinkSummaryToParentParams struct {
	SummaryID       string `json:"summary_id"`
	ParentSummaryID string `json:"parent_summary_id"`
	Ordinal         int64  `json:"ordinal"`
}

func (q *Queries) LinkSummaryToParent(ctx context.Context, arg LinkSummaryToParentParams) error {
	_, err := q.db.Exec(ctx, linkSummaryToParent, arg.SummaryID, arg.ParentSummaryID, arg.Ordinal)
	return err
}

const listRecallSummaryByIDs = `-- name: ListRecallSummaryByIDs :many
SELECT id, conversation_id
FROM ctx_summary
WHERE id = ANY($1::text[])
ORDER BY id
`

type ListRecallSummaryByIDsRow struct {
	ID             string `json:"id"`
	ConversationID string `json:"conversation_id"`
}

// As with recall messages, return only the resource ID and its exact owning
// conversation for a bounded, fail-closed batch verification.
func (q *Queries) ListRecallSummaryByIDs(ctx context.Context, summaryIds []string) ([]ListRecallSummaryByIDsRow, error) {
	rows, err := q.db.Query(ctx, listRecallSummaryByIDs, summaryIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecallSummaryByIDsRow{}
	for rows.Next() {
		var i ListRecallSummaryByIDsRow
		if err := rows.Scan(&i.ID, &i.ConversationID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSummariesByIDs = `-- name: ListSummariesByIDs :many
SELECT id, conversation_id, kind, depth, content, token_count, earliest_at, latest_at, descendant_count, descendant_token_count, source_message_token_count, created_at, contains_non_principal_input FROM ctx_summary WHERE conversation_id = $1 AND id = ANY($2::text[]) ORDER BY created_at ASC
`

type ListSummariesByIDsParams struct {
	ConversationID string   `json:"conversation_id"`
	SummaryIds     []string `json:"summary_ids"`
}

func (q *Queries) ListSummariesByIDs(ctx context.Context, arg ListSummariesByIDsParams) ([]CtxSummary, error) {
	rows, err := q.db.Query(ctx, listSummariesByIDs, arg.ConversationID, arg.SummaryIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CtxSummary{}
	for rows.Next() {
		var i CtxSummary
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.Kind,
			&i.Depth,
			&i.Content,
			&i.TokenCount,
			&i.EarliestAt,
			&i.LatestAt,
			&i.DescendantCount,
			&i.DescendantTokenCount,
			&i.SourceMessageTokenCount,
			&i.CreatedAt,
			&i.ContainsNonPrincipalInput,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSummariesNeedingEmbedding = `-- name: ListSummariesNeedingEmbedding :many
SELECT s.id, s.content, e.model AS embedded_model, e.content_hash AS embedded_hash
FROM ctx_summary s
JOIN ctx_conversation c ON c.id = s.conversation_id
LEFT JOIN ctx_summary_embedding e ON e.summary_id = s.id
WHERE c.archived = false
  AND (e.summary_id IS NULL OR e.model <> $1)
ORDER BY s.created_at DESC
LIMIT $2
`

type ListSummariesNeedingEmbeddingParams struct {
	Model string `json:"model"`
	Limit int32  `json:"limit"`
}

type ListSummariesNeedingEmbeddingRow struct {
	ID            string      `json:"id"`
	Content       string      `json:"content"`
	EmbeddedModel pgtype.Text `json:"embedded_model"`
	EmbeddedHash  []byte      `json:"embedded_hash"`
}

// Backfill candidates for summaries; see ListMessagesNeedingEmbedding. Summary
// content is immutable, so missing or model-mismatch are the only cases. ASCII.
func (q *Queries) ListSummariesNeedingEmbedding(ctx context.Context, arg ListSummariesNeedingEmbeddingParams) ([]ListSummariesNeedingEmbeddingRow, error) {
	rows, err := q.db.Query(ctx, listSummariesNeedingEmbedding, arg.Model, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSummariesNeedingEmbeddingRow{}
	for rows.Next() {
		var i ListSummariesNeedingEmbeddingRow
		if err := rows.Scan(
			&i.ID,
			&i.Content,
			&i.EmbeddedModel,
			&i.EmbeddedHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSummaryParentsBySummaryIDs = `-- name: ListSummaryParentsBySummaryIDs :many
SELECT summary_id, parent_summary_id, ordinal
FROM ctx_summary_parent
WHERE summary_id = ANY($1::text[])
ORDER BY summary_id, ordinal
`

func (q *Queries) ListSummaryParentsBySummaryIDs(ctx context.Context, summaryIds []string) ([]CtxSummaryParent, error) {
	rows, err := q.db.Query(ctx, listSummaryParentsBySummaryIDs, summaryIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CtxSummaryParent{}
	for rows.Next() {
		var i CtxSummaryParent
		if err := rows.Scan(&i.SummaryID, &i.ParentSummaryID, &i.Ordinal); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchSummaries = `-- name: SearchSummaries :many
SELECT
    s.id, s.conversation_id, s.kind, s.depth, s.content, s.token_count, s.earliest_at, s.latest_at, s.descendant_count, s.descendant_token_count, s.source_message_token_count, s.created_at, s.contains_non_principal_input,
    c.session_id AS session_id,
    c.title AS conversation_title,
    paradedb.snippet(s.content)::text AS snippet,
    paradedb.score(s.id)::double precision AS score
FROM ctx_summary s
JOIN ctx_conversation c ON c.id = s.conversation_id
WHERE s.id @@@ paradedb.match('content', $1::text)
  AND c.user_id = $2
  AND c.agent_id IS NOT DISTINCT FROM $3
  AND c.archived = false
ORDER BY score DESC, COALESCE(s.latest_at, s.created_at) DESC, s.id DESC
LIMIT $4
`

type SearchSummariesParams struct {
	Match   string      `json:"match"`
	UserID  pgtype.Text `json:"user_id"`
	AgentID pgtype.Text `json:"agent_id"`
	Limit   int32       `json:"limit"`
}

type SearchSummariesRow struct {
	ID                        string             `json:"id"`
	ConversationID            string             `json:"conversation_id"`
	Kind                      string             `json:"kind"`
	Depth                     int64              `json:"depth"`
	Content                   string             `json:"content"`
	TokenCount                int64              `json:"token_count"`
	EarliestAt                pgtype.Timestamptz `json:"earliest_at"`
	LatestAt                  pgtype.Timestamptz `json:"latest_at"`
	DescendantCount           int64              `json:"descendant_count"`
	DescendantTokenCount      int64              `json:"descendant_token_count"`
	SourceMessageTokenCount   int64              `json:"source_message_token_count"`
	CreatedAt                 time.Time          `json:"created_at"`
	ContainsNonPrincipalInput bool               `json:"contains_non_principal_input"`
	SessionID                 string             `json:"session_id"`
	ConversationTitle         pgtype.Text        `json:"conversation_title"`
	Snippet                   string             `json:"snippet"`
	Score                     float64            `json:"score"`
}

// Spans every active conversation of the current (user_id, agent_id); see SearchMessages.
// Lexical ranking is pg_search BM25; paradedb.match tokenizes the raw user text
// with the jieba tokenizer (dictionary + statistical CJK word segmentation, CJK
// matches natively) and never errors on punctuation. The match arg is the raw
// user text.
// Stable score tie-break (see SearchMessages): content time, then id, so the
// per-source rank that cross-source RRF consumes is deterministic.
func (q *Queries) SearchSummaries(ctx context.Context, arg SearchSummariesParams) ([]SearchSummariesRow, error) {
	rows, err := q.db.Query(ctx, searchSummaries,
		arg.Match,
		arg.UserID,
		arg.AgentID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchSummariesRow{}
	for rows.Next() {
		var i SearchSummariesRow
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.Kind,
			&i.Depth,
			&i.Content,
			&i.TokenCount,
			&i.EarliestAt,
			&i.LatestAt,
			&i.DescendantCount,
			&i.DescendantTokenCount,
			&i.SourceMessageTokenCount,
			&i.CreatedAt,
			&i.ContainsNonPrincipalInput,
			&i.SessionID,
			&i.ConversationTitle,
			&i.Snippet,
			&i.Score,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchSummaryEmbeddings = `-- name: SearchSummaryEmbeddings :many
SELECT
    s.id, s.conversation_id, s.kind, s.depth, s.content, s.token_count, s.earliest_at, s.latest_at, s.descendant_count, s.descendant_token_count, s.source_message_token_count, s.created_at, s.contains_non_principal_input,
    c.session_id AS session_id,
    c.title AS conversation_title,
    (1 - e.distance)::double precision AS score
FROM (
    -- Keep the HNSW distance stream lazy so the outer scope/archive filters can
    -- consume more candidates under strict iterative scan when needed.
    SELECT summary_id, embedding <=> $1::vector(1536) AS distance
    FROM ctx_summary_embedding
    WHERE model = $2
    ORDER BY embedding <=> $1::vector(1536)
    OFFSET 0
) e
JOIN ctx_summary s ON s.id = e.summary_id
JOIN ctx_conversation c ON c.id = s.conversation_id
WHERE c.user_id = $3
  AND c.agent_id IS NOT DISTINCT FROM $4
  AND c.archived = false
ORDER BY e.distance
LIMIT $5
`

type SearchSummaryEmbeddingsParams struct {
	Query   pgvector_go.Vector `json:"query"`
	Model   string             `json:"model"`
	UserID  pgtype.Text        `json:"user_id"`
	AgentID pgtype.Text        `json:"agent_id"`
	Limit   int32              `json:"limit"`
}

type SearchSummaryEmbeddingsRow struct {
	ID                        string             `json:"id"`
	ConversationID            string             `json:"conversation_id"`
	Kind                      string             `json:"kind"`
	Depth                     int64              `json:"depth"`
	Content                   string             `json:"content"`
	TokenCount                int64              `json:"token_count"`
	EarliestAt                pgtype.Timestamptz `json:"earliest_at"`
	LatestAt                  pgtype.Timestamptz `json:"latest_at"`
	DescendantCount           int64              `json:"descendant_count"`
	DescendantTokenCount      int64              `json:"descendant_token_count"`
	SourceMessageTokenCount   int64              `json:"source_message_token_count"`
	CreatedAt                 time.Time          `json:"created_at"`
	ContainsNonPrincipalInput bool               `json:"contains_non_principal_input"`
	SessionID                 string             `json:"session_id"`
	ConversationTitle         pgtype.Text        `json:"conversation_title"`
	Score                     float64            `json:"score"`
}

// Vector KNN over summary embeddings; mirror of SearchMessageEmbeddings (same
// space + scope guards, cosine similarity score). Keep ORDER BY limited to
// distance so HNSW can drive the scan; the Go merge layer orders score ties.
func (q *Queries) SearchSummaryEmbeddings(ctx context.Context, arg SearchSummaryEmbeddingsParams) ([]SearchSummaryEmbeddingsRow, error) {
	rows, err := q.db.Query(ctx, searchSummaryEmbeddings,
		arg.Query,
		arg.Model,
		arg.UserID,
		arg.AgentID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchSummaryEmbeddingsRow{}
	for rows.Next() {
		var i SearchSummaryEmbeddingsRow
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.Kind,
			&i.Depth,
			&i.Content,
			&i.TokenCount,
			&i.EarliestAt,
			&i.LatestAt,
			&i.DescendantCount,
			&i.DescendantTokenCount,
			&i.SourceMessageTokenCount,
			&i.CreatedAt,
			&i.ContainsNonPrincipalInput,
			&i.SessionID,
			&i.ConversationTitle,
			&i.Score,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSummaryEmbedding = `-- name: UpsertSummaryEmbedding :exec
INSERT INTO ctx_summary_embedding (summary_id, model, content_hash, embedding)
VALUES ($1, $2, $3, $4::vector(1536))
ON CONFLICT (summary_id) DO UPDATE
SET model        = EXCLUDED.model,
    content_hash = EXCLUDED.content_hash,
    embedding    = EXCLUDED.embedding,
    updated_at   = now()
`

type UpsertSummaryEmbeddingParams struct {
	SummaryID   string             `json:"summary_id"`
	Model       string             `json:"model"`
	ContentHash []byte             `json:"content_hash"`
	Embedding   pgvector_go.Vector `json:"embedding"`
}

// Semantic-search vector for one summary; see UpsertMessageEmbedding. Keep ASCII.
func (q *Queries) UpsertSummaryEmbedding(ctx context.Context, arg UpsertSummaryEmbeddingParams) error {
	_, err := q.db.Exec(ctx, upsertSummaryEmbedding,
		arg.SummaryID,
		arg.Model,
		arg.ContentHash,
		arg.Embedding,
	)
	return err
}
