// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: ctx_session_inbox.sql

package sqlc

import (
	"context"
)

const claimSessionInboxDelivery = `-- name: ClaimSessionInboxDelivery :one
UPDATE ctx_session_inbox
SET delivered_at = now(), updated_at = now()
WHERE id = $1
  AND source_session_id = $2
  AND target_session_id = $3
  AND actor_id = $4
  AND content = $5
  AND delivered_at IS NULL
  AND failed_at IS NULL
RETURNING id, enqueue_seq, source_session_id, target_session_id, actor_id, content, delivered_at, failed_at, error_code, created_at, updated_at
`

type ClaimSessionInboxDeliveryParams struct {
	ID              string `json:"id"`
	SourceSessionID string `json:"source_session_id"`
	TargetSessionID string `json:"target_session_id"`
	ActorID         string `json:"actor_id"`
	Content         string `json:"content"`
}

// Claim and validate the immutable delivery facts in one CAS. The enclosing LCM
// transaction rolls this UPDATE back if any transcript write fails afterwards.
func (q *Queries) ClaimSessionInboxDelivery(ctx context.Context, arg ClaimSessionInboxDeliveryParams) (CtxSessionInbox, error) {
	row := q.db.QueryRow(ctx, claimSessionInboxDelivery,
		arg.ID,
		arg.SourceSessionID,
		arg.TargetSessionID,
		arg.ActorID,
		arg.Content,
	)
	var i CtxSessionInbox
	err := row.Scan(
		&i.ID,
		&i.EnqueueSeq,
		&i.SourceSessionID,
		&i.TargetSessionID,
		&i.ActorID,
		&i.Content,
		&i.DeliveredAt,
		&i.FailedAt,
		&i.ErrorCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const enqueueSessionInbox = `-- name: EnqueueSessionInbox :one
INSERT INTO ctx_session_inbox (
    id, source_session_id, target_session_id, actor_id, content
)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, enqueue_seq, source_session_id, target_session_id, actor_id, content, delivered_at, failed_at, error_code, created_at, updated_at
`

type EnqueueSessionInboxParams struct {
	ID              string `json:"id"`
	SourceSessionID string `json:"source_session_id"`
	TargetSessionID string `json:"target_session_id"`
	ActorID         string `json:"actor_id"`
	Content         string `json:"content"`
}

func (q *Queries) EnqueueSessionInbox(ctx context.Context, arg EnqueueSessionInboxParams) (CtxSessionInbox, error) {
	row := q.db.QueryRow(ctx, enqueueSessionInbox,
		arg.ID,
		arg.SourceSessionID,
		arg.TargetSessionID,
		arg.ActorID,
		arg.Content,
	)
	var i CtxSessionInbox
	err := row.Scan(
		&i.ID,
		&i.EnqueueSeq,
		&i.SourceSessionID,
		&i.TargetSessionID,
		&i.ActorID,
		&i.Content,
		&i.DeliveredAt,
		&i.FailedAt,
		&i.ErrorCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const failPendingSessionInbox = `-- name: FailPendingSessionInbox :execrows
UPDATE ctx_session_inbox
SET failed_at = now(), error_code = $1, updated_at = now()
WHERE id = $2
  AND delivered_at IS NULL
  AND failed_at IS NULL
`

type FailPendingSessionInboxParams struct {
	ErrorCode string `json:"error_code"`
	ID        string `json:"id"`
}

func (q *Queries) FailPendingSessionInbox(ctx context.Context, arg FailPendingSessionInboxParams) (int64, error) {
	result, err := q.db.Exec(ctx, failPendingSessionInbox, arg.ErrorCode, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSessionInbox = `-- name: GetSessionInbox :one
SELECT id, enqueue_seq, source_session_id, target_session_id, actor_id, content, delivered_at, failed_at, error_code, created_at, updated_at FROM ctx_session_inbox WHERE id = $1
`

func (q *Queries) GetSessionInbox(ctx context.Context, id string) (CtxSessionInbox, error) {
	row := q.db.QueryRow(ctx, getSessionInbox, id)
	var i CtxSessionInbox
	err := row.Scan(
		&i.ID,
		&i.EnqueueSeq,
		&i.SourceSessionID,
		&i.TargetSessionID,
		&i.ActorID,
		&i.Content,
		&i.DeliveredAt,
		&i.FailedAt,
		&i.ErrorCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPendingSessionInbox = `-- name: ListPendingSessionInbox :many
SELECT id, enqueue_seq, source_session_id, target_session_id, actor_id, content, delivered_at, failed_at, error_code, created_at, updated_at
FROM ctx_session_inbox
WHERE delivered_at IS NULL
  AND failed_at IS NULL
  AND enqueue_seq > $1::bigint
ORDER BY enqueue_seq
LIMIT $2::integer
`

type ListPendingSessionInboxParams struct {
	AfterEnqueueSeq int64 `json:"after_enqueue_seq"`
	PageSize        int32 `json:"page_size"`
}

func (q *Queries) ListPendingSessionInbox(ctx context.Context, arg ListPendingSessionInboxParams) ([]CtxSessionInbox, error) {
	rows, err := q.db.Query(ctx, listPendingSessionInbox, arg.AfterEnqueueSeq, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CtxSessionInbox{}
	for rows.Next() {
		var i CtxSessionInbox
		if err := rows.Scan(
			&i.ID,
			&i.EnqueueSeq,
			&i.SourceSessionID,
			&i.TargetSessionID,
			&i.ActorID,
			&i.Content,
			&i.DeliveredAt,
			&i.FailedAt,
			&i.ErrorCode,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
