// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: ctx_group_claim.sql

package sqlc

import (
	"context"
	"time"
)

const claimGroupWork = `-- name: ClaimGroupWork :one
INSERT INTO ctx_group_claim (id, group_id, key, owner_agent_id, note, lease_until)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (group_id, key) DO UPDATE
SET owner_agent_id = EXCLUDED.owner_agent_id,
    note = EXCLUDED.note,
    lease_until = EXCLUDED.lease_until,
    updated_at = now()
WHERE ctx_group_claim.lease_until < now()
   OR ctx_group_claim.owner_agent_id = EXCLUDED.owner_agent_id
RETURNING id, group_id, key, owner_agent_id, note, lease_until, created_at, updated_at
`

type ClaimGroupWorkParams struct {
	ID           string    `json:"id"`
	GroupID      string    `json:"group_id"`
	Key          string    `json:"key"`
	OwnerAgentID string    `json:"owner_agent_id"`
	Note         string    `json:"note"`
	LeaseUntil   time.Time `json:"lease_until"`
}

func (q *Queries) ClaimGroupWork(ctx context.Context, arg ClaimGroupWorkParams) (CtxGroupClaim, error) {
	row := q.db.QueryRow(ctx, claimGroupWork,
		arg.ID,
		arg.GroupID,
		arg.Key,
		arg.OwnerAgentID,
		arg.Note,
		arg.LeaseUntil,
	)
	var i CtxGroupClaim
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Key,
		&i.OwnerAgentID,
		&i.Note,
		&i.LeaseUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLiveGroupClaim = `-- name: GetLiveGroupClaim :one
SELECT id, group_id, key, owner_agent_id, note, lease_until, created_at, updated_at FROM ctx_group_claim
WHERE group_id = $1
  AND key = $2
  AND lease_until > now()
`

type GetLiveGroupClaimParams struct {
	GroupID string `json:"group_id"`
	Key     string `json:"key"`
}

func (q *Queries) GetLiveGroupClaim(ctx context.Context, arg GetLiveGroupClaimParams) (CtxGroupClaim, error) {
	row := q.db.QueryRow(ctx, getLiveGroupClaim, arg.GroupID, arg.Key)
	var i CtxGroupClaim
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Key,
		&i.OwnerAgentID,
		&i.Note,
		&i.LeaseUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listLiveGroupClaims = `-- name: ListLiveGroupClaims :many
SELECT id, group_id, key, owner_agent_id, note, lease_until, created_at, updated_at FROM ctx_group_claim
WHERE group_id = $1
  AND lease_until > now()
ORDER BY created_at ASC, key ASC
`

func (q *Queries) ListLiveGroupClaims(ctx context.Context, groupID string) ([]CtxGroupClaim, error) {
	rows, err := q.db.Query(ctx, listLiveGroupClaims, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CtxGroupClaim{}
	for rows.Next() {
		var i CtxGroupClaim
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.Key,
			&i.OwnerAgentID,
			&i.Note,
			&i.LeaseUntil,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseGroupClaim = `-- name: ReleaseGroupClaim :execrows
DELETE FROM ctx_group_claim
WHERE group_id = $1
  AND key = $2
  AND owner_agent_id = $3
`

type ReleaseGroupClaimParams struct {
	GroupID      string `json:"group_id"`
	Key          string `json:"key"`
	OwnerAgentID string `json:"owner_agent_id"`
}

func (q *Queries) ReleaseGroupClaim(ctx context.Context, arg ReleaseGroupClaimParams) (int64, error) {
	result, err := q.db.Exec(ctx, releaseGroupClaim, arg.GroupID, arg.Key, arg.OwnerAgentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
