// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: ctx_message.sql

package sqlc

import (
	"context"
	"database/sql"
	"strings"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO ctx_message (id, conversation_id, seq, role, event_type, content, token_count)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, conversation_id, seq, role, event_type, content, token_count, created_at
`

type CreateMessageParams struct {
	ID             string `json:"id"`
	ConversationID string `json:"conversation_id"`
	Seq            int64  `json:"seq"`
	Role           string `json:"role"`
	EventType      string `json:"event_type"`
	Content        string `json:"content"`
	TokenCount     int64  `json:"token_count"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (CtxMessage, error) {
	row := q.db.QueryRowContext(ctx, createMessage,
		arg.ID,
		arg.ConversationID,
		arg.Seq,
		arg.Role,
		arg.EventType,
		arg.Content,
		arg.TokenCount,
	)
	var i CtxMessage
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.Seq,
		&i.Role,
		&i.EventType,
		&i.Content,
		&i.TokenCount,
		&i.CreatedAt,
	)
	return i, err
}

const createMessagePart = `-- name: CreateMessagePart :exec
INSERT INTO ctx_message_part (id, message_id, part_type, ordinal, text_content, tool_call_id, tool_name, tool_input, tool_output, metadata)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateMessagePartParams struct {
	ID          string         `json:"id"`
	MessageID   string         `json:"message_id"`
	PartType    string         `json:"part_type"`
	Ordinal     int64          `json:"ordinal"`
	TextContent sql.NullString `json:"text_content"`
	ToolCallID  sql.NullString `json:"tool_call_id"`
	ToolName    sql.NullString `json:"tool_name"`
	ToolInput   sql.NullString `json:"tool_input"`
	ToolOutput  sql.NullString `json:"tool_output"`
	Metadata    sql.NullString `json:"metadata"`
}

func (q *Queries) CreateMessagePart(ctx context.Context, arg CreateMessagePartParams) error {
	_, err := q.db.ExecContext(ctx, createMessagePart,
		arg.ID,
		arg.MessageID,
		arg.PartType,
		arg.Ordinal,
		arg.TextContent,
		arg.ToolCallID,
		arg.ToolName,
		arg.ToolInput,
		arg.ToolOutput,
		arg.Metadata,
	)
	return err
}

const getConversationTimeBounds = `-- name: GetConversationTimeBounds :one
SELECT MIN(created_at) AS earliest_at, MAX(created_at) AS latest_at
FROM ctx_message
WHERE conversation_id = ?
`

type GetConversationTimeBoundsRow struct {
	EarliestAt interface{} `json:"earliest_at"`
	LatestAt   interface{} `json:"latest_at"`
}

func (q *Queries) GetConversationTimeBounds(ctx context.Context, conversationID string) (GetConversationTimeBoundsRow, error) {
	row := q.db.QueryRowContext(ctx, getConversationTimeBounds, conversationID)
	var i GetConversationTimeBoundsRow
	err := row.Scan(&i.EarliestAt, &i.LatestAt)
	return i, err
}

const getMaxSeq = `-- name: GetMaxSeq :one
SELECT CAST(COALESCE(MAX(seq), 0) AS INTEGER) FROM ctx_message WHERE conversation_id = ?
`

func (q *Queries) GetMaxSeq(ctx context.Context, conversationID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getMaxSeq, conversationID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getMessage = `-- name: GetMessage :one
SELECT id, conversation_id, seq, role, event_type, content, token_count, created_at FROM ctx_message WHERE id = ? AND conversation_id = ?
`

type GetMessageParams struct {
	ID             string `json:"id"`
	ConversationID string `json:"conversation_id"`
}

func (q *Queries) GetMessage(ctx context.Context, arg GetMessageParams) (CtxMessage, error) {
	row := q.db.QueryRowContext(ctx, getMessage, arg.ID, arg.ConversationID)
	var i CtxMessage
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.Seq,
		&i.Role,
		&i.EventType,
		&i.Content,
		&i.TokenCount,
		&i.CreatedAt,
	)
	return i, err
}

const getMessageCount = `-- name: GetMessageCount :one
SELECT COUNT(*) FROM ctx_message WHERE conversation_id = ?
`

func (q *Queries) GetMessageCount(ctx context.Context, conversationID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getMessageCount, conversationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getMessageParts = `-- name: GetMessageParts :many
SELECT id, message_id, part_type, ordinal, text_content, tool_call_id, tool_name, tool_input, tool_output, metadata FROM ctx_message_part WHERE message_id = ? ORDER BY ordinal ASC
`

func (q *Queries) GetMessageParts(ctx context.Context, messageID string) ([]CtxMessagePart, error) {
	rows, err := q.db.QueryContext(ctx, getMessageParts, messageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CtxMessagePart{}
	for rows.Next() {
		var i CtxMessagePart
		if err := rows.Scan(
			&i.ID,
			&i.MessageID,
			&i.PartType,
			&i.Ordinal,
			&i.TextContent,
			&i.ToolCallID,
			&i.ToolName,
			&i.ToolInput,
			&i.ToolOutput,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMessagePartsByMessages = `-- name: GetMessagePartsByMessages :many
SELECT id, message_id, part_type, ordinal, text_content, tool_call_id, tool_name, tool_input, tool_output, metadata FROM ctx_message_part WHERE message_id IN (/*SLICE:message_ids*/?) ORDER BY message_id, ordinal ASC
`

func (q *Queries) GetMessagePartsByMessages(ctx context.Context, messageIds []string) ([]CtxMessagePart, error) {
	query := getMessagePartsByMessages
	var queryParams []interface{}
	if len(messageIds) > 0 {
		for _, v := range messageIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:message_ids*/?", strings.Repeat(",?", len(messageIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:message_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CtxMessagePart{}
	for rows.Next() {
		var i CtxMessagePart
		if err := rows.Scan(
			&i.ID,
			&i.MessageID,
			&i.PartType,
			&i.Ordinal,
			&i.TextContent,
			&i.ToolCallID,
			&i.ToolName,
			&i.ToolInput,
			&i.ToolOutput,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMessagesByConversation = `-- name: GetMessagesByConversation :many
SELECT id, conversation_id, seq, role, event_type, content, token_count, created_at FROM ctx_message WHERE conversation_id = ? ORDER BY seq ASC
`

func (q *Queries) GetMessagesByConversation(ctx context.Context, conversationID string) ([]CtxMessage, error) {
	rows, err := q.db.QueryContext(ctx, getMessagesByConversation, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CtxMessage{}
	for rows.Next() {
		var i CtxMessage
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.Seq,
			&i.Role,
			&i.EventType,
			&i.Content,
			&i.TokenCount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMessagesByConversationRange = `-- name: GetMessagesByConversationRange :many
SELECT id, conversation_id, seq, role, event_type, content, token_count, created_at FROM ctx_message
WHERE conversation_id = ? AND seq >= ? AND seq <= ?
ORDER BY seq ASC
`

type GetMessagesByConversationRangeParams struct {
	ConversationID string `json:"conversation_id"`
	Seq            int64  `json:"seq"`
	Seq_2          int64  `json:"seq_2"`
}

func (q *Queries) GetMessagesByConversationRange(ctx context.Context, arg GetMessagesByConversationRangeParams) ([]CtxMessage, error) {
	rows, err := q.db.QueryContext(ctx, getMessagesByConversationRange, arg.ConversationID, arg.Seq, arg.Seq_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CtxMessage{}
	for rows.Next() {
		var i CtxMessage
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.Seq,
			&i.Role,
			&i.EventType,
			&i.Content,
			&i.TokenCount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMessagesSince = `-- name: GetMessagesSince :many
SELECT id, conversation_id, seq, role, event_type, content, token_count, created_at FROM ctx_message
WHERE conversation_id = ? AND created_at > ?
ORDER BY seq ASC
`

type GetMessagesSinceParams struct {
	ConversationID string `json:"conversation_id"`
	CreatedAt      string `json:"created_at"`
}

func (q *Queries) GetMessagesSince(ctx context.Context, arg GetMessagesSinceParams) ([]CtxMessage, error) {
	rows, err := q.db.QueryContext(ctx, getMessagesSince, arg.ConversationID, arg.CreatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CtxMessage{}
	for rows.Next() {
		var i CtxMessage
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.Seq,
			&i.Role,
			&i.EventType,
			&i.Content,
			&i.TokenCount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExistingUserMessageContent = `-- name: ListExistingUserMessageContent :many
SELECT content FROM ctx_message
WHERE conversation_id = ?1
  AND role = 'user'
  AND content IN (/*SLICE:contents*/?)
ORDER BY seq ASC
`

type ListExistingUserMessageContentParams struct {
	ConversationID string   `json:"conversation_id"`
	Contents       []string `json:"contents"`
}

func (q *Queries) ListExistingUserMessageContent(ctx context.Context, arg ListExistingUserMessageContentParams) ([]string, error) {
	query := listExistingUserMessageContent
	var queryParams []interface{}
	queryParams = append(queryParams, arg.ConversationID)
	if len(arg.Contents) > 0 {
		for _, v := range arg.Contents {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:contents*/?", strings.Repeat(",?", len(arg.Contents))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:contents*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var content string
		if err := rows.Scan(&content); err != nil {
			return nil, err
		}
		items = append(items, content)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesByIDs = `-- name: ListMessagesByIDs :many
SELECT id, conversation_id, seq, role, event_type, content, token_count, created_at FROM ctx_message WHERE conversation_id = ? AND id IN (/*SLICE:message_ids*/?) ORDER BY seq ASC
`

type ListMessagesByIDsParams struct {
	ConversationID string   `json:"conversation_id"`
	MessageIds     []string `json:"message_ids"`
}

func (q *Queries) ListMessagesByIDs(ctx context.Context, arg ListMessagesByIDsParams) ([]CtxMessage, error) {
	query := listMessagesByIDs
	var queryParams []interface{}
	queryParams = append(queryParams, arg.ConversationID)
	if len(arg.MessageIds) > 0 {
		for _, v := range arg.MessageIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:message_ids*/?", strings.Repeat(",?", len(arg.MessageIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:message_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CtxMessage{}
	for rows.Next() {
		var i CtxMessage
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.Seq,
			&i.Role,
			&i.EventType,
			&i.Content,
			&i.TokenCount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesByLogicalPage = `-- name: ListMessagesByLogicalPage :many
WITH ordered AS (
    SELECT
        id, conversation_id, seq, role, event_type, content, token_count, created_at,
        lag(role) OVER (ORDER BY seq ASC) AS prev_role
    FROM ctx_message
    WHERE conversation_id = ?1
      AND (?2 IS NULL OR created_at >= ?2)
      AND (?3 IS NULL OR created_at <= ?3)
), grouped AS (
    SELECT
        id, conversation_id, seq, role, event_type, content, token_count, created_at, prev_role,
        sum(CASE WHEN role = 'assistant' AND prev_role = 'assistant' THEN 0 ELSE 1 END)
            OVER (ORDER BY seq ASC ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS logical_idx
    FROM ordered
), selected_groups AS (
    SELECT logical_idx
    FROM grouped
    GROUP BY logical_idx
    ORDER BY logical_idx DESC
    LIMIT ?5 OFFSET ?4
)
SELECT id, conversation_id, seq, role, event_type, content, token_count, created_at
FROM grouped
WHERE logical_idx IN (SELECT logical_idx FROM selected_groups)
ORDER BY seq ASC
`

type ListMessagesByLogicalPageParams struct {
	ConversationID string      `json:"conversation_id"`
	After          interface{} `json:"after"`
	Before         interface{} `json:"before"`
	Offset         int64       `json:"offset"`
	Limit          int64       `json:"limit"`
}

type ListMessagesByLogicalPageRow struct {
	ID             string `json:"id"`
	ConversationID string `json:"conversation_id"`
	Seq            int64  `json:"seq"`
	Role           string `json:"role"`
	EventType      string `json:"event_type"`
	Content        string `json:"content"`
	TokenCount     int64  `json:"token_count"`
	CreatedAt      string `json:"created_at"`
}

// Keep this logical-message boundary in sync with serializeDBMessages in
// internal/server/sessions.go: consecutive assistant rows render as one
// response message, so SQL pagination must count them as one too.
func (q *Queries) ListMessagesByLogicalPage(ctx context.Context, arg ListMessagesByLogicalPageParams) ([]ListMessagesByLogicalPageRow, error) {
	rows, err := q.db.QueryContext(ctx, listMessagesByLogicalPage,
		arg.ConversationID,
		arg.After,
		arg.Before,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMessagesByLogicalPageRow{}
	for rows.Next() {
		var i ListMessagesByLogicalPageRow
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.Seq,
			&i.Role,
			&i.EventType,
			&i.Content,
			&i.TokenCount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchMessages = `-- name: SearchMessages :many
SELECT
    m.id, m.conversation_id, m.seq, m.role, m.event_type, m.content, m.token_count, m.created_at,
    snippet(ctx_message_fts, 0, '<<', '>>', '...', 32) AS snippet,
    bm25(ctx_message_fts) AS score
FROM ctx_message_fts
JOIN ctx_message m ON m.rowid = ctx_message_fts.rowid
WHERE ctx_message_fts.content MATCH ?1
  AND m.conversation_id = ?2
ORDER BY score ASC
LIMIT ?3
`

type SearchMessagesParams struct {
	Match          string `json:"match"`
	ConversationID string `json:"conversation_id"`
	Limit          int64  `json:"limit"`
}

type SearchMessagesRow struct {
	ID             string  `json:"id"`
	ConversationID string  `json:"conversation_id"`
	Seq            int64   `json:"seq"`
	Role           string  `json:"role"`
	EventType      string  `json:"event_type"`
	Content        string  `json:"content"`
	TokenCount     int64   `json:"token_count"`
	CreatedAt      string  `json:"created_at"`
	Snippet        string  `json:"snippet"`
	Score          float64 `json:"score"`
}

func (q *Queries) SearchMessages(ctx context.Context, arg SearchMessagesParams) ([]SearchMessagesRow, error) {
	rows, err := q.db.QueryContext(ctx, searchMessages, arg.Match, arg.ConversationID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchMessagesRow{}
	for rows.Next() {
		var i SearchMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.Seq,
			&i.Role,
			&i.EventType,
			&i.Content,
			&i.TokenCount,
			&i.CreatedAt,
			&i.Snippet,
			&i.Score,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchMessagesLike = `-- name: SearchMessagesLike :many
SELECT id, conversation_id, seq, role, event_type, content, token_count, created_at FROM ctx_message
WHERE conversation_id = ?1
  AND (content LIKE ?2 ESCAPE '\')
ORDER BY created_at DESC
LIMIT ?3
`

type SearchMessagesLikeParams struct {
	ConversationID string `json:"conversation_id"`
	Pattern        string `json:"pattern"`
	Limit          int64  `json:"limit"`
}

// Fallback for queries with no token of 3+ runes, which trigram MATCH would
// silently never hit. Scans the content table directly (faster there than on
// the FTS table, which pays external-content read-back), recency-ordered, no
// BM25. Pattern must be a full '%text%' built with ftsquery.EscapeLike; sqlc
// cannot parse || concatenation here, so the caller wraps it, and the parens
// around LIKE...ESCAPE are also required by sqlc's grammar. Keep these doc
// comments ASCII: multibyte chars corrupt sqlc's query rewriter offsets.
func (q *Queries) SearchMessagesLike(ctx context.Context, arg SearchMessagesLikeParams) ([]CtxMessage, error) {
	rows, err := q.db.QueryContext(ctx, searchMessagesLike, arg.ConversationID, arg.Pattern, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CtxMessage{}
	for rows.Next() {
		var i CtxMessage
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.Seq,
			&i.Role,
			&i.EventType,
			&i.Content,
			&i.TokenCount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
