// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: ctx_group_dispatch.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimExpiredGroupDispatch = `-- name: ClaimExpiredGroupDispatch :one
UPDATE ctx_group_dispatch
SET status = 'running',
    attempt_count = attempt_count + 1,
    lease_until = $1,
    next_attempt_at = NULL,
    last_error = '',
    updated_at = now()
WHERE id = $2
  AND status = 'running'
  AND lease_until IS NOT NULL
  AND lease_until <= $3
RETURNING id, group_message_id, group_id, agent_id, reply_channel_id, status, attempt_count, lease_until, next_attempt_at, last_error, result_message_id, created_at, updated_at, kind, trigger_seq, held_up_to_seq, published_at
`

type ClaimExpiredGroupDispatchParams struct {
	LeaseUntil pgtype.Timestamptz `json:"lease_until"`
	ID         string             `json:"id"`
	Now        pgtype.Timestamptz `json:"now"`
}

func (q *Queries) ClaimExpiredGroupDispatch(ctx context.Context, arg ClaimExpiredGroupDispatchParams) (CtxGroupDispatch, error) {
	row := q.db.QueryRow(ctx, claimExpiredGroupDispatch, arg.LeaseUntil, arg.ID, arg.Now)
	var i CtxGroupDispatch
	err := row.Scan(
		&i.ID,
		&i.GroupMessageID,
		&i.GroupID,
		&i.AgentID,
		&i.ReplyChannelID,
		&i.Status,
		&i.AttemptCount,
		&i.LeaseUntil,
		&i.NextAttemptAt,
		&i.LastError,
		&i.ResultMessageID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Kind,
		&i.TriggerSeq,
		&i.HeldUpToSeq,
		&i.PublishedAt,
	)
	return i, err
}

const claimNewestGroupWake = `-- name: ClaimNewestGroupWake :one
WITH newest AS (
  SELECT id
  FROM ctx_group_dispatch candidate
  WHERE candidate.group_id = $2
    AND candidate.agent_id = $3
    AND candidate.kind = 'wake'
    AND candidate.status = 'pending'
    AND (candidate.next_attempt_at IS NULL OR candidate.next_attempt_at <= $4)
    AND NOT EXISTS (
      SELECT 1
      FROM ctx_group_dispatch running
      WHERE running.group_id = candidate.group_id
        AND running.agent_id = candidate.agent_id
        AND running.kind = 'wake'
        AND running.status = 'running'
        AND running.lease_until IS NOT NULL
        AND running.lease_until > $4
    )
    -- A HOLD is only safe to retry once the wake snapshot covers the peer
    -- activity that caused it. Scope the gate to the current causal chain:
    -- a later human message or this agent's accepted post starts a new chain.
    AND candidate.trigger_seq >= COALESCE((
      SELECT MAX(held.held_up_to_seq)
      FROM ctx_group_dispatch held
      WHERE held.group_id = candidate.group_id
        AND held.agent_id = candidate.agent_id
        AND held.kind = 'wake'
        AND held.status = 'held'
        AND held.trigger_seq > GREATEST(
          COALESCE((
            SELECT MAX(own.seq)
            FROM ctx_group_dispatch accepted
            JOIN ctx_group_message own ON own.id = accepted.result_message_id
            WHERE accepted.group_id = candidate.group_id
              AND accepted.agent_id = candidate.agent_id
              AND accepted.result_message_id IS NOT NULL
          ), 0),
          COALESCE((
            SELECT MAX(human.seq)
            FROM ctx_group_message human
            WHERE human.group_id = candidate.group_id
              AND human.actor_type = 'human'
              AND human.seq <= candidate.trigger_seq
          ), 0)
        )
    ), 0)
  ORDER BY candidate.trigger_seq DESC
  LIMIT 1
), supersede AS (
  UPDATE ctx_group_dispatch older
  SET status = 'superseded',
      lease_until = NULL,
      next_attempt_at = NULL,
      updated_at = now()
  WHERE older.group_id = $2
    AND older.agent_id = $3
    AND older.kind = 'wake'
    AND older.status = 'pending'
    AND older.trigger_seq < (SELECT trigger_seq FROM ctx_group_dispatch WHERE id = (SELECT id FROM newest))
)
UPDATE ctx_group_dispatch dispatch
SET status = 'running',
    attempt_count = attempt_count + 1,
    lease_until = $1,
    next_attempt_at = NULL,
    last_error = '',
    updated_at = now()
WHERE dispatch.id = (SELECT id FROM newest)
RETURNING dispatch.id, dispatch.group_message_id, dispatch.group_id, dispatch.agent_id, dispatch.reply_channel_id, dispatch.status, dispatch.attempt_count, dispatch.lease_until, dispatch.next_attempt_at, dispatch.last_error, dispatch.result_message_id, dispatch.created_at, dispatch.updated_at, dispatch.kind, dispatch.trigger_seq, dispatch.held_up_to_seq, dispatch.published_at
`

type ClaimNewestGroupWakeParams struct {
	LeaseUntil pgtype.Timestamptz `json:"lease_until"`
	GroupID    string             `json:"group_id"`
	AgentID    string             `json:"agent_id"`
	Now        pgtype.Timestamptz `json:"now"`
}

// Claim the current high-water wake and retire older pending snapshots in the
// same transaction. A live sibling owns the agent's group session already.
func (q *Queries) ClaimNewestGroupWake(ctx context.Context, arg ClaimNewestGroupWakeParams) (CtxGroupDispatch, error) {
	row := q.db.QueryRow(ctx, claimNewestGroupWake,
		arg.LeaseUntil,
		arg.GroupID,
		arg.AgentID,
		arg.Now,
	)
	var i CtxGroupDispatch
	err := row.Scan(
		&i.ID,
		&i.GroupMessageID,
		&i.GroupID,
		&i.AgentID,
		&i.ReplyChannelID,
		&i.Status,
		&i.AttemptCount,
		&i.LeaseUntil,
		&i.NextAttemptAt,
		&i.LastError,
		&i.ResultMessageID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Kind,
		&i.TriggerSeq,
		&i.HeldUpToSeq,
		&i.PublishedAt,
	)
	return i, err
}

const claimPendingGroupDispatch = `-- name: ClaimPendingGroupDispatch :one
UPDATE ctx_group_dispatch
SET status = 'running',
    attempt_count = attempt_count + 1,
    lease_until = $1,
    next_attempt_at = NULL,
    last_error = '',
    updated_at = now()
WHERE id = $2
  AND status = 'pending'
  AND (next_attempt_at IS NULL OR next_attempt_at <= $3)
RETURNING id, group_message_id, group_id, agent_id, reply_channel_id, status, attempt_count, lease_until, next_attempt_at, last_error, result_message_id, created_at, updated_at, kind, trigger_seq, held_up_to_seq, published_at
`

type ClaimPendingGroupDispatchParams struct {
	LeaseUntil pgtype.Timestamptz `json:"lease_until"`
	ID         string             `json:"id"`
	Now        pgtype.Timestamptz `json:"now"`
}

func (q *Queries) ClaimPendingGroupDispatch(ctx context.Context, arg ClaimPendingGroupDispatchParams) (CtxGroupDispatch, error) {
	row := q.db.QueryRow(ctx, claimPendingGroupDispatch, arg.LeaseUntil, arg.ID, arg.Now)
	var i CtxGroupDispatch
	err := row.Scan(
		&i.ID,
		&i.GroupMessageID,
		&i.GroupID,
		&i.AgentID,
		&i.ReplyChannelID,
		&i.Status,
		&i.AttemptCount,
		&i.LeaseUntil,
		&i.NextAttemptAt,
		&i.LastError,
		&i.ResultMessageID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Kind,
		&i.TriggerSeq,
		&i.HeldUpToSeq,
		&i.PublishedAt,
	)
	return i, err
}

const claimPendingGroupDispatchesByMessage = `-- name: ClaimPendingGroupDispatchesByMessage :many
UPDATE ctx_group_dispatch
SET status = 'running',
    attempt_count = attempt_count + 1,
    lease_until = $1,
    next_attempt_at = NULL,
    last_error = '',
    updated_at = now()
WHERE group_message_id = $2
  AND status = 'pending'
  AND kind = 'reply'
RETURNING id, group_message_id, group_id, agent_id, reply_channel_id, status, attempt_count, lease_until, next_attempt_at, last_error, result_message_id, created_at, updated_at, kind, trigger_seq, held_up_to_seq, published_at
`

type ClaimPendingGroupDispatchesByMessageParams struct {
	LeaseUntil     pgtype.Timestamptz `json:"lease_until"`
	GroupMessageID string             `json:"group_message_id"`
}

// DispatchSync reserves its just-materialized rows before releasing the outbox
// completion transaction. This keeps the web request as the publisher owner.
func (q *Queries) ClaimPendingGroupDispatchesByMessage(ctx context.Context, arg ClaimPendingGroupDispatchesByMessageParams) ([]CtxGroupDispatch, error) {
	rows, err := q.db.Query(ctx, claimPendingGroupDispatchesByMessage, arg.LeaseUntil, arg.GroupMessageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CtxGroupDispatch{}
	for rows.Next() {
		var i CtxGroupDispatch
		if err := rows.Scan(
			&i.ID,
			&i.GroupMessageID,
			&i.GroupID,
			&i.AgentID,
			&i.ReplyChannelID,
			&i.Status,
			&i.AttemptCount,
			&i.LeaseUntil,
			&i.NextAttemptAt,
			&i.LastError,
			&i.ResultMessageID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Kind,
			&i.TriggerSeq,
			&i.HeldUpToSeq,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countGroupDispatchByMessage = `-- name: CountGroupDispatchByMessage :one
SELECT CAST(COUNT(*) AS BIGINT) FROM ctx_group_dispatch
WHERE group_message_id = $1
`

func (q *Queries) CountGroupDispatchByMessage(ctx context.Context, groupMessageID string) (int64, error) {
	row := q.db.QueryRow(ctx, countGroupDispatchByMessage, groupMessageID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countHeldGroupDispatchesInChain = `-- name: CountHeldGroupDispatchesInChain :one
SELECT COUNT(*)::bigint
FROM ctx_group_dispatch held
WHERE held.group_id = $1
  AND held.agent_id = $2
  AND held.status = 'held'
  AND held.trigger_seq > GREATEST($3, $4)
`

type CountHeldGroupDispatchesInChainParams struct {
	GroupID         string `json:"group_id"`
	AgentID         string `json:"agent_id"`
	AfterOwnPostSeq int64  `json:"after_own_post_seq"`
	AfterHumanSeq   int64  `json:"after_human_seq"`
}

func (q *Queries) CountHeldGroupDispatchesInChain(ctx context.Context, arg CountHeldGroupDispatchesInChainParams) (int64, error) {
	row := q.db.QueryRow(ctx, countHeldGroupDispatchesInChain,
		arg.GroupID,
		arg.AgentID,
		arg.AfterOwnPostSeq,
		arg.AfterHumanSeq,
	)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countNonTerminalGroupDispatchByMessage = `-- name: CountNonTerminalGroupDispatchByMessage :one
SELECT CAST(COUNT(*) AS BIGINT) FROM ctx_group_dispatch
WHERE group_message_id = $1
  AND status IN ('pending', 'running')
`

func (q *Queries) CountNonTerminalGroupDispatchByMessage(ctx context.Context, groupMessageID string) (int64, error) {
	row := q.db.QueryRow(ctx, countNonTerminalGroupDispatchByMessage, groupMessageID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createGroupDispatch = `-- name: CreateGroupDispatch :exec
INSERT INTO ctx_group_dispatch (
  id, group_message_id, group_id, agent_id, reply_channel_id, status, attempt_count, lease_until, next_attempt_at, last_error, trigger_seq, kind
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10,
  (SELECT seq FROM ctx_group_message WHERE id = $2), 'reply') ON CONFLICT DO NOTHING
`

type CreateGroupDispatchParams struct {
	ID             string             `json:"id"`
	GroupMessageID string             `json:"group_message_id"`
	GroupID        string             `json:"group_id"`
	AgentID        string             `json:"agent_id"`
	ReplyChannelID string             `json:"reply_channel_id"`
	Status         string             `json:"status"`
	AttemptCount   int64              `json:"attempt_count"`
	LeaseUntil     pgtype.Timestamptz `json:"lease_until"`
	NextAttemptAt  pgtype.Timestamptz `json:"next_attempt_at"`
	LastError      string             `json:"last_error"`
}

func (q *Queries) CreateGroupDispatch(ctx context.Context, arg CreateGroupDispatchParams) error {
	_, err := q.db.Exec(ctx, createGroupDispatch,
		arg.ID,
		arg.GroupMessageID,
		arg.GroupID,
		arg.AgentID,
		arg.ReplyChannelID,
		arg.Status,
		arg.AttemptCount,
		arg.LeaseUntil,
		arg.NextAttemptAt,
		arg.LastError,
	)
	return err
}

const extendRunningGroupDispatchLease = `-- name: ExtendRunningGroupDispatchLease :execrows
UPDATE ctx_group_dispatch
SET lease_until = $1,
    updated_at = now()
WHERE id = $2
  AND status = 'running'
  AND attempt_count = $3
`

type ExtendRunningGroupDispatchLeaseParams struct {
	LeaseUntil   pgtype.Timestamptz `json:"lease_until"`
	ID           string             `json:"id"`
	AttemptCount int64              `json:"attempt_count"`
}

func (q *Queries) ExtendRunningGroupDispatchLease(ctx context.Context, arg ExtendRunningGroupDispatchLeaseParams) (int64, error) {
	result, err := q.db.Exec(ctx, extendRunningGroupDispatchLease, arg.LeaseUntil, arg.ID, arg.AttemptCount)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getGroupDispatch = `-- name: GetGroupDispatch :one
SELECT id, group_message_id, group_id, agent_id, reply_channel_id, status, attempt_count, lease_until, next_attempt_at, last_error, result_message_id, created_at, updated_at, kind, trigger_seq, held_up_to_seq, published_at FROM ctx_group_dispatch WHERE id = $1
`

func (q *Queries) GetGroupDispatch(ctx context.Context, id string) (CtxGroupDispatch, error) {
	row := q.db.QueryRow(ctx, getGroupDispatch, id)
	var i CtxGroupDispatch
	err := row.Scan(
		&i.ID,
		&i.GroupMessageID,
		&i.GroupID,
		&i.AgentID,
		&i.ReplyChannelID,
		&i.Status,
		&i.AttemptCount,
		&i.LeaseUntil,
		&i.NextAttemptAt,
		&i.LastError,
		&i.ResultMessageID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Kind,
		&i.TriggerSeq,
		&i.HeldUpToSeq,
		&i.PublishedAt,
	)
	return i, err
}

const listExpiredRunningGroupDispatch = `-- name: ListExpiredRunningGroupDispatch :many
SELECT id, group_message_id, group_id, agent_id, reply_channel_id, status, attempt_count, lease_until, next_attempt_at, last_error, result_message_id, created_at, updated_at, kind, trigger_seq, held_up_to_seq, published_at FROM ctx_group_dispatch
WHERE status = 'running'
  AND lease_until IS NOT NULL
  AND lease_until <= $1
ORDER BY lease_until ASC
LIMIT $2
`

type ListExpiredRunningGroupDispatchParams struct {
	Now        pgtype.Timestamptz `json:"now"`
	LimitCount int32              `json:"limit_count"`
}

func (q *Queries) ListExpiredRunningGroupDispatch(ctx context.Context, arg ListExpiredRunningGroupDispatchParams) ([]CtxGroupDispatch, error) {
	rows, err := q.db.Query(ctx, listExpiredRunningGroupDispatch, arg.Now, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CtxGroupDispatch{}
	for rows.Next() {
		var i CtxGroupDispatch
		if err := rows.Scan(
			&i.ID,
			&i.GroupMessageID,
			&i.GroupID,
			&i.AgentID,
			&i.ReplyChannelID,
			&i.Status,
			&i.AttemptCount,
			&i.LeaseUntil,
			&i.NextAttemptAt,
			&i.LastError,
			&i.ResultMessageID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Kind,
			&i.TriggerSeq,
			&i.HeldUpToSeq,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingGroupDispatch = `-- name: ListPendingGroupDispatch :many
SELECT id, group_message_id, group_id, agent_id, reply_channel_id, status, attempt_count, lease_until, next_attempt_at, last_error, result_message_id, created_at, updated_at, kind, trigger_seq, held_up_to_seq, published_at FROM ctx_group_dispatch gd
WHERE gd.status = 'pending'
  AND gd.kind = 'reply'
  AND (gd.next_attempt_at IS NULL OR gd.next_attempt_at <= $1)
  AND NOT EXISTS (
    SELECT 1
    FROM ctx_group_dispatch earlier
    JOIN ctx_group_message earlier_msg ON earlier_msg.id = earlier.group_message_id
    JOIN ctx_group_message current_msg ON current_msg.id = gd.group_message_id
    WHERE earlier.group_id = gd.group_id
      AND earlier.agent_id = gd.agent_id
      AND earlier_msg.seq < current_msg.seq
      AND (
        earlier.status = 'pending'
        OR (earlier.status = 'running' AND earlier.lease_until IS NOT NULL AND earlier.lease_until >= $1)
      )
  )
  AND NOT EXISTS (
    SELECT 1
    FROM ctx_group_outbox earlier_outbox
    JOIN ctx_group_message earlier_msg ON earlier_msg.id = earlier_outbox.group_message_id
    JOIN ctx_group_message current_msg ON current_msg.id = gd.group_message_id
    WHERE earlier_outbox.group_id = gd.group_id
      AND earlier_msg.seq < current_msg.seq
      AND (
        earlier_outbox.status = 'pending'
        OR (earlier_outbox.status = 'running' AND earlier_outbox.lease_until IS NOT NULL AND earlier_outbox.lease_until >= $1)
      )
  )
ORDER BY gd.created_at ASC
LIMIT $2
`

type ListPendingGroupDispatchParams struct {
	Now        pgtype.Timestamptz `json:"now"`
	LimitCount int32              `json:"limit_count"`
}

func (q *Queries) ListPendingGroupDispatch(ctx context.Context, arg ListPendingGroupDispatchParams) ([]CtxGroupDispatch, error) {
	rows, err := q.db.Query(ctx, listPendingGroupDispatch, arg.Now, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CtxGroupDispatch{}
	for rows.Next() {
		var i CtxGroupDispatch
		if err := rows.Scan(
			&i.ID,
			&i.GroupMessageID,
			&i.GroupID,
			&i.AgentID,
			&i.ReplyChannelID,
			&i.Status,
			&i.AttemptCount,
			&i.LeaseUntil,
			&i.NextAttemptAt,
			&i.LastError,
			&i.ResultMessageID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Kind,
			&i.TriggerSeq,
			&i.HeldUpToSeq,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingGroupDispatchByMessage = `-- name: ListPendingGroupDispatchByMessage :many
SELECT id, group_message_id, group_id, agent_id, reply_channel_id, status, attempt_count, lease_until, next_attempt_at, last_error, result_message_id, created_at, updated_at, kind, trigger_seq, held_up_to_seq, published_at FROM ctx_group_dispatch gd
WHERE gd.group_message_id = $1
  AND gd.status = 'pending'
  AND gd.kind = 'reply'
  AND (gd.next_attempt_at IS NULL OR gd.next_attempt_at <= $2)
  AND NOT EXISTS (
    SELECT 1
    FROM ctx_group_dispatch earlier
    JOIN ctx_group_message earlier_msg ON earlier_msg.id = earlier.group_message_id
    JOIN ctx_group_message current_msg ON current_msg.id = gd.group_message_id
    WHERE earlier.group_id = gd.group_id
      AND earlier.agent_id = gd.agent_id
      AND earlier_msg.seq < current_msg.seq
      AND (
        earlier.status = 'pending'
        OR (earlier.status = 'running' AND earlier.lease_until IS NOT NULL AND earlier.lease_until >= $2)
      )
  )
  AND NOT EXISTS (
    SELECT 1
    FROM ctx_group_outbox earlier_outbox
    JOIN ctx_group_message earlier_msg ON earlier_msg.id = earlier_outbox.group_message_id
    JOIN ctx_group_message current_msg ON current_msg.id = gd.group_message_id
    WHERE earlier_outbox.group_id = gd.group_id
      AND earlier_msg.seq < current_msg.seq
      AND (
        earlier_outbox.status = 'pending'
        OR (earlier_outbox.status = 'running' AND earlier_outbox.lease_until IS NOT NULL AND earlier_outbox.lease_until >= $2)
      )
  )
ORDER BY gd.created_at ASC
`

type ListPendingGroupDispatchByMessageParams struct {
	GroupMessageID string             `json:"group_message_id"`
	Now            pgtype.Timestamptz `json:"now"`
}

func (q *Queries) ListPendingGroupDispatchByMessage(ctx context.Context, arg ListPendingGroupDispatchByMessageParams) ([]CtxGroupDispatch, error) {
	rows, err := q.db.Query(ctx, listPendingGroupDispatchByMessage, arg.GroupMessageID, arg.Now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CtxGroupDispatch{}
	for rows.Next() {
		var i CtxGroupDispatch
		if err := rows.Scan(
			&i.ID,
			&i.GroupMessageID,
			&i.GroupID,
			&i.AgentID,
			&i.ReplyChannelID,
			&i.Status,
			&i.AttemptCount,
			&i.LeaseUntil,
			&i.NextAttemptAt,
			&i.LastError,
			&i.ResultMessageID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Kind,
			&i.TriggerSeq,
			&i.HeldUpToSeq,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingGroupWakePairs = `-- name: ListPendingGroupWakePairs :many
SELECT DISTINCT ON (group_id, agent_id) id, group_message_id, group_id, agent_id, reply_channel_id, status, attempt_count, lease_until, next_attempt_at, last_error, result_message_id, created_at, updated_at, kind, trigger_seq, held_up_to_seq, published_at
FROM ctx_group_dispatch
WHERE kind = 'wake'
  AND status = 'pending'
  AND (next_attempt_at IS NULL OR next_attempt_at <= $1)
ORDER BY group_id, agent_id, trigger_seq DESC
LIMIT $2
`

type ListPendingGroupWakePairsParams struct {
	Now        pgtype.Timestamptz `json:"now"`
	LimitCount int32              `json:"limit_count"`
}

// One representative per (group, agent) wakes the bounded pool. Claiming
// chooses newest again transactionally, so this advisory feed may be stale.
func (q *Queries) ListPendingGroupWakePairs(ctx context.Context, arg ListPendingGroupWakePairsParams) ([]CtxGroupDispatch, error) {
	rows, err := q.db.Query(ctx, listPendingGroupWakePairs, arg.Now, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CtxGroupDispatch{}
	for rows.Next() {
		var i CtxGroupDispatch
		if err := rows.Scan(
			&i.ID,
			&i.GroupMessageID,
			&i.GroupID,
			&i.AgentID,
			&i.ReplyChannelID,
			&i.Status,
			&i.AttemptCount,
			&i.LeaseUntil,
			&i.NextAttemptAt,
			&i.LastError,
			&i.ResultMessageID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Kind,
			&i.TriggerSeq,
			&i.HeldUpToSeq,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markGroupDispatchCompleted = `-- name: MarkGroupDispatchCompleted :execrows
UPDATE ctx_group_dispatch
SET status = 'completed',
    lease_until = NULL,
    next_attempt_at = NULL,
    updated_at = now()
WHERE id = $1
  AND status = 'running'
  AND attempt_count = $2
`

type MarkGroupDispatchCompletedParams struct {
	ID           string `json:"id"`
	AttemptCount int64  `json:"attempt_count"`
}

func (q *Queries) MarkGroupDispatchCompleted(ctx context.Context, arg MarkGroupDispatchCompletedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markGroupDispatchCompleted, arg.ID, arg.AttemptCount)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markGroupDispatchFailed = `-- name: MarkGroupDispatchFailed :execrows
UPDATE ctx_group_dispatch
SET status = 'failed',
    lease_until = NULL,
    next_attempt_at = NULL,
    last_error = $1,
    updated_at = now()
WHERE id = $2
  AND status = 'running'
  AND attempt_count = $3
`

type MarkGroupDispatchFailedParams struct {
	LastError    string `json:"last_error"`
	ID           string `json:"id"`
	AttemptCount int64  `json:"attempt_count"`
}

func (q *Queries) MarkGroupDispatchFailed(ctx context.Context, arg MarkGroupDispatchFailedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markGroupDispatchFailed, arg.LastError, arg.ID, arg.AttemptCount)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markGroupDispatchHeld = `-- name: MarkGroupDispatchHeld :execrows
UPDATE ctx_group_dispatch
SET status = 'held',
    lease_until = NULL,
    next_attempt_at = NULL,
    held_up_to_seq = $1,
    updated_at = now()
WHERE id = $2
  AND status = 'running'
  AND attempt_count = $3
`

type MarkGroupDispatchHeldParams struct {
	HeldUpToSeq  pgtype.Int8 `json:"held_up_to_seq"`
	ID           string      `json:"id"`
	AttemptCount int64       `json:"attempt_count"`
}

func (q *Queries) MarkGroupDispatchHeld(ctx context.Context, arg MarkGroupDispatchHeldParams) (int64, error) {
	result, err := q.db.Exec(ctx, markGroupDispatchHeld, arg.HeldUpToSeq, arg.ID, arg.AttemptCount)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markGroupDispatchPublished = `-- name: MarkGroupDispatchPublished :execrows
UPDATE ctx_group_dispatch
SET published_at = now(),
    updated_at = now()
WHERE id = $1
  AND status = 'running'
  AND attempt_count = $2
  AND result_message_id = $3
  AND published_at IS NULL
`

type MarkGroupDispatchPublishedParams struct {
	ID              string `json:"id"`
	AttemptCount    int64  `json:"attempt_count"`
	ResultMessageID string `json:"result_message_id"`
}

func (q *Queries) MarkGroupDispatchPublished(ctx context.Context, arg MarkGroupDispatchPublishedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markGroupDispatchPublished, arg.ID, arg.AttemptCount, arg.ResultMessageID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const requeueGroupDispatch = `-- name: RequeueGroupDispatch :execrows
UPDATE ctx_group_dispatch
SET status = 'pending',
    lease_until = NULL,
    next_attempt_at = $1,
    last_error = $2,
    updated_at = now()
WHERE id = $3
  AND status = 'running'
  AND attempt_count = $4
`

type RequeueGroupDispatchParams struct {
	NextAttemptAt pgtype.Timestamptz `json:"next_attempt_at"`
	LastError     string             `json:"last_error"`
	ID            string             `json:"id"`
	AttemptCount  int64              `json:"attempt_count"`
}

func (q *Queries) RequeueGroupDispatch(ctx context.Context, arg RequeueGroupDispatchParams) (int64, error) {
	result, err := q.db.Exec(ctx, requeueGroupDispatch,
		arg.NextAttemptAt,
		arg.LastError,
		arg.ID,
		arg.AttemptCount,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setGroupDispatchResultMessage = `-- name: SetGroupDispatchResultMessage :execrows
UPDATE ctx_group_dispatch
SET result_message_id = $1,
    updated_at = now()
WHERE id = $2
  AND status = 'running'
  AND attempt_count = $3
`

type SetGroupDispatchResultMessageParams struct {
	ResultMessageID string `json:"result_message_id"`
	ID              string `json:"id"`
	AttemptCount    int64  `json:"attempt_count"`
}

func (q *Queries) SetGroupDispatchResultMessage(ctx context.Context, arg SetGroupDispatchResultMessageParams) (int64, error) {
	result, err := q.db.Exec(ctx, setGroupDispatchResultMessage, arg.ResultMessageID, arg.ID, arg.AttemptCount)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
