// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: oauth_flow.sql

package sqlc

import (
	"context"
	"encoding/json"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimOAuthFlow = `-- name: ClaimOAuthFlow :one
UPDATE oauth_flow
SET state = 'completing', consumed_at = now(), updated_at = now()
WHERE id = $1
  AND state = 'pending'
  AND consumed_at IS NULL
  AND expires_at > now()
RETURNING id, server_id, user_id, credential_scope, credential_user_id, credential_agent_id, pkce_verifier, oauth_config, expires_at, consumed_at, created_at, provider_key, target_kind, target_id, bundle_name, state, error, updated_at
`

func (q *Queries) ClaimOAuthFlow(ctx context.Context, id string) (OauthFlow, error) {
	row := q.db.QueryRow(ctx, claimOAuthFlow, id)
	var i OauthFlow
	err := row.Scan(
		&i.ID,
		&i.ServerID,
		&i.UserID,
		&i.CredentialScope,
		&i.CredentialUserID,
		&i.CredentialAgentID,
		&i.PkceVerifier,
		&i.OauthConfig,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
		&i.ProviderKey,
		&i.TargetKind,
		&i.TargetID,
		&i.BundleName,
		&i.State,
		&i.Error,
		&i.UpdatedAt,
	)
	return i, err
}

const createOAuthFlow = `-- name: CreateOAuthFlow :one
INSERT INTO oauth_flow (
    id, server_id, user_id, credential_scope, credential_user_id,
    credential_agent_id, pkce_verifier, oauth_config, expires_at,
    provider_key, target_kind, target_id, bundle_name, state, error
)
VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9,
    $10, $11, $12, $13, $14, $15
)
RETURNING id, server_id, user_id, credential_scope, credential_user_id, credential_agent_id, pkce_verifier, oauth_config, expires_at, consumed_at, created_at, provider_key, target_kind, target_id, bundle_name, state, error, updated_at
`

type CreateOAuthFlowParams struct {
	ID                string          `json:"id"`
	ServerID          pgtype.Text     `json:"server_id"`
	UserID            string          `json:"user_id"`
	CredentialScope   string          `json:"credential_scope"`
	CredentialUserID  pgtype.Text     `json:"credential_user_id"`
	CredentialAgentID pgtype.Text     `json:"credential_agent_id"`
	PkceVerifier      string          `json:"pkce_verifier"`
	OauthConfig       json.RawMessage `json:"oauth_config"`
	ExpiresAt         time.Time       `json:"expires_at"`
	ProviderKey       string          `json:"provider_key"`
	TargetKind        string          `json:"target_kind"`
	TargetID          string          `json:"target_id"`
	BundleName        string          `json:"bundle_name"`
	State             string          `json:"state"`
	Error             string          `json:"error"`
}

func (q *Queries) CreateOAuthFlow(ctx context.Context, arg CreateOAuthFlowParams) (OauthFlow, error) {
	row := q.db.QueryRow(ctx, createOAuthFlow,
		arg.ID,
		arg.ServerID,
		arg.UserID,
		arg.CredentialScope,
		arg.CredentialUserID,
		arg.CredentialAgentID,
		arg.PkceVerifier,
		arg.OauthConfig,
		arg.ExpiresAt,
		arg.ProviderKey,
		arg.TargetKind,
		arg.TargetID,
		arg.BundleName,
		arg.State,
		arg.Error,
	)
	var i OauthFlow
	err := row.Scan(
		&i.ID,
		&i.ServerID,
		&i.UserID,
		&i.CredentialScope,
		&i.CredentialUserID,
		&i.CredentialAgentID,
		&i.PkceVerifier,
		&i.OauthConfig,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
		&i.ProviderKey,
		&i.TargetKind,
		&i.TargetID,
		&i.BundleName,
		&i.State,
		&i.Error,
		&i.UpdatedAt,
	)
	return i, err
}

const getOAuthFlow = `-- name: GetOAuthFlow :one
SELECT id, server_id, user_id, credential_scope, credential_user_id, credential_agent_id, pkce_verifier, oauth_config, expires_at, consumed_at, created_at, provider_key, target_kind, target_id, bundle_name, state, error, updated_at FROM oauth_flow WHERE id = $1
`

func (q *Queries) GetOAuthFlow(ctx context.Context, id string) (OauthFlow, error) {
	row := q.db.QueryRow(ctx, getOAuthFlow, id)
	var i OauthFlow
	err := row.Scan(
		&i.ID,
		&i.ServerID,
		&i.UserID,
		&i.CredentialScope,
		&i.CredentialUserID,
		&i.CredentialAgentID,
		&i.PkceVerifier,
		&i.OauthConfig,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
		&i.ProviderKey,
		&i.TargetKind,
		&i.TargetID,
		&i.BundleName,
		&i.State,
		&i.Error,
		&i.UpdatedAt,
	)
	return i, err
}

const updateOAuthFlow = `-- name: UpdateOAuthFlow :exec
UPDATE oauth_flow
SET state = $2, error = $3, updated_at = now()
WHERE id = $1
`

type UpdateOAuthFlowParams struct {
	ID    string `json:"id"`
	State string `json:"state"`
	Error string `json:"error"`
}

func (q *Queries) UpdateOAuthFlow(ctx context.Context, arg UpdateOAuthFlowParams) error {
	_, err := q.db.Exec(ctx, updateOAuthFlow, arg.ID, arg.State, arg.Error)
	return err
}
