// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: oauth_authorization_code.sql

package sqlc

import (
	"context"
	"time"
)

const consumeOAuthAuthorizationCode = `-- name: ConsumeOAuthAuthorizationCode :one
UPDATE oauth_authorization_code
SET consumed_at = now()
WHERE code_hash = $1 AND consumed_at IS NULL
RETURNING id, code_hash, client_id, user_id, redirect_uri, scopes, code_challenge, code_challenge_method, expires_at, consumed_at, created_at
`

// Single-use exchange: mark consumed only if not already consumed. A second
// exchange of the same code returns no row, which the caller treats as reuse.
func (q *Queries) ConsumeOAuthAuthorizationCode(ctx context.Context, codeHash string) (OauthAuthorizationCode, error) {
	row := q.db.QueryRow(ctx, consumeOAuthAuthorizationCode, codeHash)
	var i OauthAuthorizationCode
	err := row.Scan(
		&i.ID,
		&i.CodeHash,
		&i.ClientID,
		&i.UserID,
		&i.RedirectUri,
		&i.Scopes,
		&i.CodeChallenge,
		&i.CodeChallengeMethod,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createOAuthAuthorizationCode = `-- name: CreateOAuthAuthorizationCode :one
INSERT INTO oauth_authorization_code (
    code_hash, client_id, user_id, redirect_uri, scopes, code_challenge, code_challenge_method, expires_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, code_hash, client_id, user_id, redirect_uri, scopes, code_challenge, code_challenge_method, expires_at, consumed_at, created_at
`

type CreateOAuthAuthorizationCodeParams struct {
	CodeHash            string    `json:"code_hash"`
	ClientID            string    `json:"client_id"`
	UserID              string    `json:"user_id"`
	RedirectUri         string    `json:"redirect_uri"`
	Scopes              []string  `json:"scopes"`
	CodeChallenge       string    `json:"code_challenge"`
	CodeChallengeMethod string    `json:"code_challenge_method"`
	ExpiresAt           time.Time `json:"expires_at"`
}

func (q *Queries) CreateOAuthAuthorizationCode(ctx context.Context, arg CreateOAuthAuthorizationCodeParams) (OauthAuthorizationCode, error) {
	row := q.db.QueryRow(ctx, createOAuthAuthorizationCode,
		arg.CodeHash,
		arg.ClientID,
		arg.UserID,
		arg.RedirectUri,
		arg.Scopes,
		arg.CodeChallenge,
		arg.CodeChallengeMethod,
		arg.ExpiresAt,
	)
	var i OauthAuthorizationCode
	err := row.Scan(
		&i.ID,
		&i.CodeHash,
		&i.ClientID,
		&i.UserID,
		&i.RedirectUri,
		&i.Scopes,
		&i.CodeChallenge,
		&i.CodeChallengeMethod,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}
