// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: oauth_refresh_family.sql

package sqlc

import (
	"context"
)

const createOAuthRefreshFamily = `-- name: CreateOAuthRefreshFamily :one
INSERT INTO oauth_refresh_family (user_id, client_id)
VALUES ($1, $2)
RETURNING id, user_id, client_id, revoked_at, created_at
`

type CreateOAuthRefreshFamilyParams struct {
	UserID   string `json:"user_id"`
	ClientID string `json:"client_id"`
}

// Open a new revocation family for a grant. Every refresh token in the rotation
// chain and every access token minted under the grant reference this row.
func (q *Queries) CreateOAuthRefreshFamily(ctx context.Context, arg CreateOAuthRefreshFamilyParams) (OauthRefreshFamily, error) {
	row := q.db.QueryRow(ctx, createOAuthRefreshFamily, arg.UserID, arg.ClientID)
	var i OauthRefreshFamily
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ClientID,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const revokeOAuthRefreshFamiliesForUserClient = `-- name: RevokeOAuthRefreshFamiliesForUserClient :execrows
UPDATE oauth_refresh_family
SET revoked_at = now()
WHERE user_id = $1 AND client_id = $2 AND revoked_at IS NULL
`

type RevokeOAuthRefreshFamiliesForUserClientParams struct {
	UserID   string `json:"user_id"`
	ClientID string `json:"client_id"`
}

// User-initiated per-client revoke: kill every family the user holds for a
// client. One UPDATE covers all the client's access + refresh tokens.
func (q *Queries) RevokeOAuthRefreshFamiliesForUserClient(ctx context.Context, arg RevokeOAuthRefreshFamiliesForUserClientParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeOAuthRefreshFamiliesForUserClient, arg.UserID, arg.ClientID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeOAuthRefreshFamily = `-- name: RevokeOAuthRefreshFamily :execrows
UPDATE oauth_refresh_family
SET revoked_at = now()
WHERE id = $1 AND revoked_at IS NULL
`

// Kill one family: reuse detection or a single-grant revoke. Access and refresh
// tokens in the family fail closed at resolve time by joining revoked_at.
func (q *Queries) RevokeOAuthRefreshFamily(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, revokeOAuthRefreshFamily, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
