// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: plugin_oauth_provider.sql

package sqlc

import (
	"context"
)

const deleteAuthOAuthProvider = `-- name: DeleteAuthOAuthProvider :exec
DELETE FROM plugin_oauth_provider WHERE provider_id = $1
`

func (q *Queries) DeleteAuthOAuthProvider(ctx context.Context, providerID string) error {
	_, err := q.db.Exec(ctx, deleteAuthOAuthProvider, providerID)
	return err
}

const getAuthOAuthProvider = `-- name: GetAuthOAuthProvider :one
SELECT id, provider_id, client_id, client_secret_enc, redirect_url, created_at, updated_at
FROM plugin_oauth_provider
WHERE provider_id = $1
`

func (q *Queries) GetAuthOAuthProvider(ctx context.Context, providerID string) (PluginOauthProvider, error) {
	row := q.db.QueryRow(ctx, getAuthOAuthProvider, providerID)
	var i PluginOauthProvider
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.ClientID,
		&i.ClientSecretEnc,
		&i.RedirectUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertAuthOAuthProvider = `-- name: UpsertAuthOAuthProvider :exec
INSERT INTO plugin_oauth_provider (id, provider_id, client_id, client_secret_enc, redirect_url)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT(provider_id) DO UPDATE SET
    client_id         = excluded.client_id,
    client_secret_enc = excluded.client_secret_enc,
    redirect_url      = excluded.redirect_url,
    updated_at        = now()
`

type UpsertAuthOAuthProviderParams struct {
	ID              string `json:"id"`
	ProviderID      string `json:"provider_id"`
	ClientID        string `json:"client_id"`
	ClientSecretEnc string `json:"client_secret_enc"`
	RedirectUrl     string `json:"redirect_url"`
}

func (q *Queries) UpsertAuthOAuthProvider(ctx context.Context, arg UpsertAuthOAuthProviderParams) error {
	_, err := q.db.Exec(ctx, upsertAuthOAuthProvider,
		arg.ID,
		arg.ProviderID,
		arg.ClientID,
		arg.ClientSecretEnc,
		arg.RedirectUrl,
	)
	return err
}
