// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: plugin_state_entries.sql

package sqlc

import (
	"context"
)

const deletePluginStateEntry = `-- name: DeletePluginStateEntry :exec
DELETE FROM plugin_state_entries
WHERE plugin_id = ? AND scope_kind = ? AND scope_id = ? AND state_key = ?
`

type DeletePluginStateEntryParams struct {
	PluginID  string `json:"plugin_id"`
	ScopeKind string `json:"scope_kind"`
	ScopeID   string `json:"scope_id"`
	StateKey  string `json:"state_key"`
}

func (q *Queries) DeletePluginStateEntry(ctx context.Context, arg DeletePluginStateEntryParams) error {
	_, err := q.db.ExecContext(ctx, deletePluginStateEntry,
		arg.PluginID,
		arg.ScopeKind,
		arg.ScopeID,
		arg.StateKey,
	)
	return err
}

const getPluginStateEntry = `-- name: GetPluginStateEntry :one
SELECT value FROM plugin_state_entries
WHERE plugin_id = ? AND scope_kind = ? AND scope_id = ? AND state_key = ?
`

type GetPluginStateEntryParams struct {
	PluginID  string `json:"plugin_id"`
	ScopeKind string `json:"scope_kind"`
	ScopeID   string `json:"scope_id"`
	StateKey  string `json:"state_key"`
}

func (q *Queries) GetPluginStateEntry(ctx context.Context, arg GetPluginStateEntryParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getPluginStateEntry,
		arg.PluginID,
		arg.ScopeKind,
		arg.ScopeID,
		arg.StateKey,
	)
	var value string
	err := row.Scan(&value)
	return value, err
}

const upsertPluginStateEntry = `-- name: UpsertPluginStateEntry :exec
INSERT INTO plugin_state_entries (plugin_id, scope_kind, scope_id, state_key, value, updated_at)
VALUES (?, ?, ?, ?, ?, datetime('now'))
ON CONFLICT(plugin_id, scope_kind, scope_id, state_key)
DO UPDATE SET value = excluded.value, updated_at = datetime('now')
`

type UpsertPluginStateEntryParams struct {
	PluginID  string `json:"plugin_id"`
	ScopeKind string `json:"scope_kind"`
	ScopeID   string `json:"scope_id"`
	StateKey  string `json:"state_key"`
	Value     string `json:"value"`
}

func (q *Queries) UpsertPluginStateEntry(ctx context.Context, arg UpsertPluginStateEntryParams) error {
	_, err := q.db.ExecContext(ctx, upsertPluginStateEntry,
		arg.PluginID,
		arg.ScopeKind,
		arg.ScopeID,
		arg.StateKey,
		arg.Value,
	)
	return err
}
