// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: recally_article.sql

package sqlc

import (
	"context"
	"database/sql"
)

const countArticlesByStatus = `-- name: CountArticlesByStatus :one
SELECT COUNT(*) as count FROM recally_article WHERE user_id = ? AND status = ?
`

type CountArticlesByStatusParams struct {
	UserID string `json:"user_id"`
	Status string `json:"status"`
}

func (q *Queries) CountArticlesByStatus(ctx context.Context, arg CountArticlesByStatusParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countArticlesByStatus, arg.UserID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countStarredArticles = `-- name: CountStarredArticles :one
SELECT COUNT(*) as count FROM recally_article WHERE user_id = ? AND starred = 1
`

func (q *Queries) CountStarredArticles(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countStarredArticles, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createArticle = `-- name: CreateArticle :one
INSERT INTO recally_article (
    id, user_id, agent_id, url, canonical_url, source_type,
    title, author, summary, tags, status, starred, file_path, metadata,
    published_at, saved_at, read_at
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, user_id, agent_id, url, canonical_url, source_type, title, author, summary, tags, status, starred, file_path, metadata, published_at, saved_at, read_at, created_at, updated_at
`

type CreateArticleParams struct {
	ID           string         `json:"id"`
	UserID       string         `json:"user_id"`
	AgentID      sql.NullString `json:"agent_id"`
	Url          string         `json:"url"`
	CanonicalUrl string         `json:"canonical_url"`
	SourceType   string         `json:"source_type"`
	Title        string         `json:"title"`
	Author       string         `json:"author"`
	Summary      string         `json:"summary"`
	Tags         string         `json:"tags"`
	Status       string         `json:"status"`
	Starred      int64          `json:"starred"`
	FilePath     string         `json:"file_path"`
	Metadata     string         `json:"metadata"`
	PublishedAt  sql.NullString `json:"published_at"`
	SavedAt      string         `json:"saved_at"`
	ReadAt       sql.NullString `json:"read_at"`
}

func (q *Queries) CreateArticle(ctx context.Context, arg CreateArticleParams) (RecallyArticle, error) {
	row := q.db.QueryRowContext(ctx, createArticle,
		arg.ID,
		arg.UserID,
		arg.AgentID,
		arg.Url,
		arg.CanonicalUrl,
		arg.SourceType,
		arg.Title,
		arg.Author,
		arg.Summary,
		arg.Tags,
		arg.Status,
		arg.Starred,
		arg.FilePath,
		arg.Metadata,
		arg.PublishedAt,
		arg.SavedAt,
		arg.ReadAt,
	)
	var i RecallyArticle
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AgentID,
		&i.Url,
		&i.CanonicalUrl,
		&i.SourceType,
		&i.Title,
		&i.Author,
		&i.Summary,
		&i.Tags,
		&i.Status,
		&i.Starred,
		&i.FilePath,
		&i.Metadata,
		&i.PublishedAt,
		&i.SavedAt,
		&i.ReadAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteArticle = `-- name: DeleteArticle :exec
DELETE FROM recally_article WHERE id = ? AND user_id = ?
`

type DeleteArticleParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeleteArticle(ctx context.Context, arg DeleteArticleParams) error {
	_, err := q.db.ExecContext(ctx, deleteArticle, arg.ID, arg.UserID)
	return err
}

const getArticle = `-- name: GetArticle :one
SELECT id, user_id, agent_id, url, canonical_url, source_type, title, author, summary, tags, status, starred, file_path, metadata, published_at, saved_at, read_at, created_at, updated_at FROM recally_article WHERE id = ? AND user_id = ?
`

type GetArticleParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) GetArticle(ctx context.Context, arg GetArticleParams) (RecallyArticle, error) {
	row := q.db.QueryRowContext(ctx, getArticle, arg.ID, arg.UserID)
	var i RecallyArticle
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AgentID,
		&i.Url,
		&i.CanonicalUrl,
		&i.SourceType,
		&i.Title,
		&i.Author,
		&i.Summary,
		&i.Tags,
		&i.Status,
		&i.Starred,
		&i.FilePath,
		&i.Metadata,
		&i.PublishedAt,
		&i.SavedAt,
		&i.ReadAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getArticleByCanonicalURL = `-- name: GetArticleByCanonicalURL :one
SELECT id, user_id, agent_id, url, canonical_url, source_type, title, author, summary, tags, status, starred, file_path, metadata, published_at, saved_at, read_at, created_at, updated_at FROM recally_article WHERE user_id = ? AND canonical_url = ?
`

type GetArticleByCanonicalURLParams struct {
	UserID       string `json:"user_id"`
	CanonicalUrl string `json:"canonical_url"`
}

func (q *Queries) GetArticleByCanonicalURL(ctx context.Context, arg GetArticleByCanonicalURLParams) (RecallyArticle, error) {
	row := q.db.QueryRowContext(ctx, getArticleByCanonicalURL, arg.UserID, arg.CanonicalUrl)
	var i RecallyArticle
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AgentID,
		&i.Url,
		&i.CanonicalUrl,
		&i.SourceType,
		&i.Title,
		&i.Author,
		&i.Summary,
		&i.Tags,
		&i.Status,
		&i.Starred,
		&i.FilePath,
		&i.Metadata,
		&i.PublishedAt,
		&i.SavedAt,
		&i.ReadAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getArticlesSavedThisWeek = `-- name: GetArticlesSavedThisWeek :many
SELECT id, user_id, agent_id, url, canonical_url, source_type, title, author, summary, tags, status, starred, file_path, metadata, published_at, saved_at, read_at, created_at, updated_at FROM recally_article
WHERE user_id = ?
  AND datetime(saved_at) >= datetime('now', '-7 days')
ORDER BY saved_at DESC
`

func (q *Queries) GetArticlesSavedThisWeek(ctx context.Context, userID string) ([]RecallyArticle, error) {
	rows, err := q.db.QueryContext(ctx, getArticlesSavedThisWeek, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecallyArticle{}
	for rows.Next() {
		var i RecallyArticle
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AgentID,
			&i.Url,
			&i.CanonicalUrl,
			&i.SourceType,
			&i.Title,
			&i.Author,
			&i.Summary,
			&i.Tags,
			&i.Status,
			&i.Starred,
			&i.FilePath,
			&i.Metadata,
			&i.PublishedAt,
			&i.SavedAt,
			&i.ReadAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArticles = `-- name: ListArticles :many
SELECT id, user_id, agent_id, url, canonical_url, source_type, title, author, summary, tags, status, starred, file_path, metadata, published_at, saved_at, read_at, created_at, updated_at FROM recally_article
WHERE user_id = ?1
  AND (?2 = '' OR status = ?2)
  AND (?3 = '' OR source_type = ?3)
  AND (?4 = 0 OR starred = ?4)
ORDER BY saved_at DESC, id DESC
LIMIT ?6 OFFSET ?5
`

type ListArticlesParams struct {
	UserID     string      `json:"user_id"`
	Status     interface{} `json:"status"`
	SourceType interface{} `json:"source_type"`
	Starred    interface{} `json:"starred"`
	Offset     int64       `json:"offset"`
	Limit      int64       `json:"limit"`
}

func (q *Queries) ListArticles(ctx context.Context, arg ListArticlesParams) ([]RecallyArticle, error) {
	rows, err := q.db.QueryContext(ctx, listArticles,
		arg.UserID,
		arg.Status,
		arg.SourceType,
		arg.Starred,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecallyArticle{}
	for rows.Next() {
		var i RecallyArticle
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AgentID,
			&i.Url,
			&i.CanonicalUrl,
			&i.SourceType,
			&i.Title,
			&i.Author,
			&i.Summary,
			&i.Tags,
			&i.Status,
			&i.Starred,
			&i.FilePath,
			&i.Metadata,
			&i.PublishedAt,
			&i.SavedAt,
			&i.ReadAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArticlesSavedYesterday = `-- name: ListArticlesSavedYesterday :many
SELECT id, user_id, agent_id, url, canonical_url, source_type, title, author, summary, tags, status, starred, file_path, metadata, published_at, saved_at, read_at, created_at, updated_at FROM recally_article
WHERE user_id = ?
  AND date(saved_at) = date('now', '-1 day')
ORDER BY saved_at DESC
`

func (q *Queries) ListArticlesSavedYesterday(ctx context.Context, userID string) ([]RecallyArticle, error) {
	rows, err := q.db.QueryContext(ctx, listArticlesSavedYesterday, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecallyArticle{}
	for rows.Next() {
		var i RecallyArticle
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AgentID,
			&i.Url,
			&i.CanonicalUrl,
			&i.SourceType,
			&i.Title,
			&i.Author,
			&i.Summary,
			&i.Tags,
			&i.Status,
			&i.Starred,
			&i.FilePath,
			&i.Metadata,
			&i.PublishedAt,
			&i.SavedAt,
			&i.ReadAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnreadArticlesOlderThan = `-- name: ListUnreadArticlesOlderThan :many
SELECT id, user_id, agent_id, url, canonical_url, source_type, title, author, summary, tags, status, starred, file_path, metadata, published_at, saved_at, read_at, created_at, updated_at FROM recally_article
WHERE user_id = ?
  AND status = 'unread'
  AND datetime(saved_at) < datetime('now', ?)
ORDER BY saved_at ASC
LIMIT ?
`

type ListUnreadArticlesOlderThanParams struct {
	UserID   string      `json:"user_id"`
	Datetime interface{} `json:"datetime"`
	Limit    int64       `json:"limit"`
}

func (q *Queries) ListUnreadArticlesOlderThan(ctx context.Context, arg ListUnreadArticlesOlderThanParams) ([]RecallyArticle, error) {
	rows, err := q.db.QueryContext(ctx, listUnreadArticlesOlderThan, arg.UserID, arg.Datetime, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecallyArticle{}
	for rows.Next() {
		var i RecallyArticle
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AgentID,
			&i.Url,
			&i.CanonicalUrl,
			&i.SourceType,
			&i.Title,
			&i.Author,
			&i.Summary,
			&i.Tags,
			&i.Status,
			&i.Starred,
			&i.FilePath,
			&i.Metadata,
			&i.PublishedAt,
			&i.SavedAt,
			&i.ReadAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchArticles = `-- name: SearchArticles :many
SELECT
    a.id, a.user_id, a.agent_id, a.url, a.canonical_url, a.source_type, a.title, a.author, a.summary, a.tags, a.status, a.starred, a.file_path, a.metadata, a.published_at, a.saved_at, a.read_at, a.created_at, a.updated_at,
    snippet(recally_article_fts, -1, '<<', '>>', '...', 32) AS snippet,
    bm25(recally_article_fts, 4.0, 2.0, 2.0, 1.0) AS score
FROM recally_article_fts
JOIN recally_article a ON a.rowid = recally_article_fts.rowid
WHERE recally_article_fts.recally_article_fts MATCH ?1
  AND a.user_id = ?2
ORDER BY score ASC
LIMIT ?3
`

type SearchArticlesParams struct {
	Match  string `json:"match"`
	UserID string `json:"user_id"`
	Limit  int64  `json:"limit"`
}

type SearchArticlesRow struct {
	RecallyArticle RecallyArticle `json:"recally_article"`
	Snippet        string         `json:"snippet"`
	Score          float64        `json:"score"`
}

// FTS5/BM25 search over title/summary/tags/author. Matching against the
// hidden table-name column searches every indexed column (declared for sqlc
// in recally_article_fts_sqlc.sql); bm25 weights rank title hits highest,
// and snippet column -1 picks the best-matching column. More negative bm25
// means more relevant, hence ORDER BY score ASC.
func (q *Queries) SearchArticles(ctx context.Context, arg SearchArticlesParams) ([]SearchArticlesRow, error) {
	rows, err := q.db.QueryContext(ctx, searchArticles, arg.Match, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchArticlesRow{}
	for rows.Next() {
		var i SearchArticlesRow
		if err := rows.Scan(
			&i.RecallyArticle.ID,
			&i.RecallyArticle.UserID,
			&i.RecallyArticle.AgentID,
			&i.RecallyArticle.Url,
			&i.RecallyArticle.CanonicalUrl,
			&i.RecallyArticle.SourceType,
			&i.RecallyArticle.Title,
			&i.RecallyArticle.Author,
			&i.RecallyArticle.Summary,
			&i.RecallyArticle.Tags,
			&i.RecallyArticle.Status,
			&i.RecallyArticle.Starred,
			&i.RecallyArticle.FilePath,
			&i.RecallyArticle.Metadata,
			&i.RecallyArticle.PublishedAt,
			&i.RecallyArticle.SavedAt,
			&i.RecallyArticle.ReadAt,
			&i.RecallyArticle.CreatedAt,
			&i.RecallyArticle.UpdatedAt,
			&i.Snippet,
			&i.Score,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateArticle = `-- name: UpdateArticle :one
UPDATE recally_article
SET title       = ?1,
    author      = ?2,
    summary     = ?3,
    tags        = ?4,
    status      = ?5,
    starred     = ?6,
    file_path   = ?7,
    metadata    = ?8,
    published_at = ?9,
    read_at     = ?10,
    updated_at  = datetime('now')
WHERE id = ?11 AND user_id = ?12
RETURNING id, user_id, agent_id, url, canonical_url, source_type, title, author, summary, tags, status, starred, file_path, metadata, published_at, saved_at, read_at, created_at, updated_at
`

type UpdateArticleParams struct {
	Title       string         `json:"title"`
	Author      string         `json:"author"`
	Summary     string         `json:"summary"`
	Tags        string         `json:"tags"`
	Status      string         `json:"status"`
	Starred     int64          `json:"starred"`
	FilePath    string         `json:"file_path"`
	Metadata    string         `json:"metadata"`
	PublishedAt sql.NullString `json:"published_at"`
	ReadAt      sql.NullString `json:"read_at"`
	ID          string         `json:"id"`
	UserID      string         `json:"user_id"`
}

func (q *Queries) UpdateArticle(ctx context.Context, arg UpdateArticleParams) (RecallyArticle, error) {
	row := q.db.QueryRowContext(ctx, updateArticle,
		arg.Title,
		arg.Author,
		arg.Summary,
		arg.Tags,
		arg.Status,
		arg.Starred,
		arg.FilePath,
		arg.Metadata,
		arg.PublishedAt,
		arg.ReadAt,
		arg.ID,
		arg.UserID,
	)
	var i RecallyArticle
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AgentID,
		&i.Url,
		&i.CanonicalUrl,
		&i.SourceType,
		&i.Title,
		&i.Author,
		&i.Summary,
		&i.Tags,
		&i.Status,
		&i.Starred,
		&i.FilePath,
		&i.Metadata,
		&i.PublishedAt,
		&i.SavedAt,
		&i.ReadAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
