// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: recally_feed.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createFeed = `-- name: CreateFeed :one
INSERT INTO recally_feed (
    id, user_id, agent_id, url, kind, metadata, title, description, check_interval,
    last_checked_at, last_etag, last_modified, enabled
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, user_id, agent_id, url, kind, metadata, title, description, check_interval, last_checked_at, last_etag, last_modified, enabled, created_at, updated_at
`

type CreateFeedParams struct {
	ID            string         `json:"id"`
	UserID        string         `json:"user_id"`
	AgentID       sql.NullString `json:"agent_id"`
	Url           string         `json:"url"`
	Kind          string         `json:"kind"`
	Metadata      string         `json:"metadata"`
	Title         string         `json:"title"`
	Description   string         `json:"description"`
	CheckInterval string         `json:"check_interval"`
	LastCheckedAt sql.NullString `json:"last_checked_at"`
	LastEtag      string         `json:"last_etag"`
	LastModified  string         `json:"last_modified"`
	Enabled       int64          `json:"enabled"`
}

func (q *Queries) CreateFeed(ctx context.Context, arg CreateFeedParams) (RecallyFeed, error) {
	row := q.db.QueryRowContext(ctx, createFeed,
		arg.ID,
		arg.UserID,
		arg.AgentID,
		arg.Url,
		arg.Kind,
		arg.Metadata,
		arg.Title,
		arg.Description,
		arg.CheckInterval,
		arg.LastCheckedAt,
		arg.LastEtag,
		arg.LastModified,
		arg.Enabled,
	)
	var i RecallyFeed
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AgentID,
		&i.Url,
		&i.Kind,
		&i.Metadata,
		&i.Title,
		&i.Description,
		&i.CheckInterval,
		&i.LastCheckedAt,
		&i.LastEtag,
		&i.LastModified,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createFeedEntry = `-- name: CreateFeedEntry :one
INSERT INTO recally_feed_entry (
    id, feed_id, guid, url, title, status, article_id, attempts, error_msg,
    discovered_at, processed_at
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(feed_id, guid) DO NOTHING
RETURNING id, feed_id, guid, url, title, status, article_id, attempts, error_msg, discovered_at, processed_at
`

type CreateFeedEntryParams struct {
	ID           string         `json:"id"`
	FeedID       string         `json:"feed_id"`
	Guid         string         `json:"guid"`
	Url          string         `json:"url"`
	Title        string         `json:"title"`
	Status       string         `json:"status"`
	ArticleID    sql.NullString `json:"article_id"`
	Attempts     int64          `json:"attempts"`
	ErrorMsg     string         `json:"error_msg"`
	DiscoveredAt string         `json:"discovered_at"`
	ProcessedAt  sql.NullString `json:"processed_at"`
}

func (q *Queries) CreateFeedEntry(ctx context.Context, arg CreateFeedEntryParams) (RecallyFeedEntry, error) {
	row := q.db.QueryRowContext(ctx, createFeedEntry,
		arg.ID,
		arg.FeedID,
		arg.Guid,
		arg.Url,
		arg.Title,
		arg.Status,
		arg.ArticleID,
		arg.Attempts,
		arg.ErrorMsg,
		arg.DiscoveredAt,
		arg.ProcessedAt,
	)
	var i RecallyFeedEntry
	err := row.Scan(
		&i.ID,
		&i.FeedID,
		&i.Guid,
		&i.Url,
		&i.Title,
		&i.Status,
		&i.ArticleID,
		&i.Attempts,
		&i.ErrorMsg,
		&i.DiscoveredAt,
		&i.ProcessedAt,
	)
	return i, err
}

const deleteFeed = `-- name: DeleteFeed :exec
DELETE FROM recally_feed WHERE id = ? AND user_id = ?
`

type DeleteFeedParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeleteFeed(ctx context.Context, arg DeleteFeedParams) error {
	_, err := q.db.ExecContext(ctx, deleteFeed, arg.ID, arg.UserID)
	return err
}

const deleteOldEntries = `-- name: DeleteOldEntries :exec
DELETE FROM recally_feed_entry
WHERE feed_id = ?
  AND status IN ('skipped', 'error')
  AND processed_at < datetime('now', '-30 days')
`

func (q *Queries) DeleteOldEntries(ctx context.Context, feedID string) error {
	_, err := q.db.ExecContext(ctx, deleteOldEntries, feedID)
	return err
}

const getFeed = `-- name: GetFeed :one
SELECT id, user_id, agent_id, url, kind, metadata, title, description, check_interval, last_checked_at, last_etag, last_modified, enabled, created_at, updated_at FROM recally_feed WHERE id = ? AND user_id = ?
`

type GetFeedParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) GetFeed(ctx context.Context, arg GetFeedParams) (RecallyFeed, error) {
	row := q.db.QueryRowContext(ctx, getFeed, arg.ID, arg.UserID)
	var i RecallyFeed
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AgentID,
		&i.Url,
		&i.Kind,
		&i.Metadata,
		&i.Title,
		&i.Description,
		&i.CheckInterval,
		&i.LastCheckedAt,
		&i.LastEtag,
		&i.LastModified,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFeedByURL = `-- name: GetFeedByURL :one
SELECT id, user_id, agent_id, url, kind, metadata, title, description, check_interval, last_checked_at, last_etag, last_modified, enabled, created_at, updated_at FROM recally_feed WHERE user_id = ? AND url = ?
`

type GetFeedByURLParams struct {
	UserID string `json:"user_id"`
	Url    string `json:"url"`
}

func (q *Queries) GetFeedByURL(ctx context.Context, arg GetFeedByURLParams) (RecallyFeed, error) {
	row := q.db.QueryRowContext(ctx, getFeedByURL, arg.UserID, arg.Url)
	var i RecallyFeed
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AgentID,
		&i.Url,
		&i.Kind,
		&i.Metadata,
		&i.Title,
		&i.Description,
		&i.CheckInterval,
		&i.LastCheckedAt,
		&i.LastEtag,
		&i.LastModified,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFeedEntry = `-- name: GetFeedEntry :one
SELECT id, feed_id, guid, url, title, status, article_id, attempts, error_msg, discovered_at, processed_at FROM recally_feed_entry WHERE id = ? AND feed_id = ?
`

type GetFeedEntryParams struct {
	ID     string `json:"id"`
	FeedID string `json:"feed_id"`
}

func (q *Queries) GetFeedEntry(ctx context.Context, arg GetFeedEntryParams) (RecallyFeedEntry, error) {
	row := q.db.QueryRowContext(ctx, getFeedEntry, arg.ID, arg.FeedID)
	var i RecallyFeedEntry
	err := row.Scan(
		&i.ID,
		&i.FeedID,
		&i.Guid,
		&i.Url,
		&i.Title,
		&i.Status,
		&i.ArticleID,
		&i.Attempts,
		&i.ErrorMsg,
		&i.DiscoveredAt,
		&i.ProcessedAt,
	)
	return i, err
}

const listFeedEntries = `-- name: ListFeedEntries :many
SELECT id, feed_id, guid, url, title, status, article_id, attempts, error_msg, discovered_at, processed_at FROM recally_feed_entry
WHERE feed_id = ?1
  AND (?2 = '' OR status = ?2)
ORDER BY discovered_at DESC
LIMIT ?3
`

type ListFeedEntriesParams struct {
	FeedID string      `json:"feed_id"`
	Status interface{} `json:"status"`
	Limit  int64       `json:"limit"`
}

func (q *Queries) ListFeedEntries(ctx context.Context, arg ListFeedEntriesParams) ([]RecallyFeedEntry, error) {
	rows, err := q.db.QueryContext(ctx, listFeedEntries, arg.FeedID, arg.Status, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecallyFeedEntry{}
	for rows.Next() {
		var i RecallyFeedEntry
		if err := rows.Scan(
			&i.ID,
			&i.FeedID,
			&i.Guid,
			&i.Url,
			&i.Title,
			&i.Status,
			&i.ArticleID,
			&i.Attempts,
			&i.ErrorMsg,
			&i.DiscoveredAt,
			&i.ProcessedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFeeds = `-- name: ListFeeds :many
SELECT id, user_id, agent_id, url, kind, metadata, title, description, check_interval, last_checked_at, last_etag, last_modified, enabled, created_at, updated_at FROM recally_feed
WHERE user_id = ?1
ORDER BY created_at DESC, id DESC
LIMIT ?3 OFFSET ?2
`

type ListFeedsParams struct {
	UserID string `json:"user_id"`
	Offset int64  `json:"offset"`
	Limit  int64  `json:"limit"`
}

func (q *Queries) ListFeeds(ctx context.Context, arg ListFeedsParams) ([]RecallyFeed, error) {
	rows, err := q.db.QueryContext(ctx, listFeeds, arg.UserID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecallyFeed{}
	for rows.Next() {
		var i RecallyFeed
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AgentID,
			&i.Url,
			&i.Kind,
			&i.Metadata,
			&i.Title,
			&i.Description,
			&i.CheckInterval,
			&i.LastCheckedAt,
			&i.LastEtag,
			&i.LastModified,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingEntries = `-- name: ListPendingEntries :many
SELECT id, feed_id, guid, url, title, status, article_id, attempts, error_msg, discovered_at, processed_at FROM recally_feed_entry
WHERE feed_id = ?1
  AND status IN ('pending', 'error')
  AND attempts < 3
ORDER BY discovered_at ASC
LIMIT ?3 OFFSET ?2
`

type ListPendingEntriesParams struct {
	FeedID string `json:"feed_id"`
	Offset int64  `json:"offset"`
	Limit  int64  `json:"limit"`
}

func (q *Queries) ListPendingEntries(ctx context.Context, arg ListPendingEntriesParams) ([]RecallyFeedEntry, error) {
	rows, err := q.db.QueryContext(ctx, listPendingEntries, arg.FeedID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecallyFeedEntry{}
	for rows.Next() {
		var i RecallyFeedEntry
		if err := rows.Scan(
			&i.ID,
			&i.FeedID,
			&i.Guid,
			&i.Url,
			&i.Title,
			&i.Status,
			&i.ArticleID,
			&i.Attempts,
			&i.ErrorMsg,
			&i.DiscoveredAt,
			&i.ProcessedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFeed = `-- name: UpdateFeed :one
UPDATE recally_feed
SET title           = ?1,
    description     = ?2,
    metadata        = ?3,
    check_interval  = ?4,
    last_checked_at = ?5,
    last_etag       = ?6,
    last_modified   = ?7,
    enabled         = ?8,
    updated_at      = datetime('now')
WHERE id = ?9 AND user_id = ?10
RETURNING id, user_id, agent_id, url, kind, metadata, title, description, check_interval, last_checked_at, last_etag, last_modified, enabled, created_at, updated_at
`

type UpdateFeedParams struct {
	Title         string         `json:"title"`
	Description   string         `json:"description"`
	Metadata      string         `json:"metadata"`
	CheckInterval string         `json:"check_interval"`
	LastCheckedAt sql.NullString `json:"last_checked_at"`
	LastEtag      string         `json:"last_etag"`
	LastModified  string         `json:"last_modified"`
	Enabled       int64          `json:"enabled"`
	ID            string         `json:"id"`
	UserID        string         `json:"user_id"`
}

func (q *Queries) UpdateFeed(ctx context.Context, arg UpdateFeedParams) (RecallyFeed, error) {
	row := q.db.QueryRowContext(ctx, updateFeed,
		arg.Title,
		arg.Description,
		arg.Metadata,
		arg.CheckInterval,
		arg.LastCheckedAt,
		arg.LastEtag,
		arg.LastModified,
		arg.Enabled,
		arg.ID,
		arg.UserID,
	)
	var i RecallyFeed
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AgentID,
		&i.Url,
		&i.Kind,
		&i.Metadata,
		&i.Title,
		&i.Description,
		&i.CheckInterval,
		&i.LastCheckedAt,
		&i.LastEtag,
		&i.LastModified,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateFeedEntry = `-- name: UpdateFeedEntry :one
UPDATE recally_feed_entry
SET status       = ?1,
    article_id   = ?2,
    attempts     = attempts + 1,
    error_msg    = ?3,
    processed_at = datetime('now')
WHERE id = ?4 AND feed_id = ?5
RETURNING id, feed_id, guid, url, title, status, article_id, attempts, error_msg, discovered_at, processed_at
`

type UpdateFeedEntryParams struct {
	Status    string         `json:"status"`
	ArticleID sql.NullString `json:"article_id"`
	ErrorMsg  string         `json:"error_msg"`
	ID        string         `json:"id"`
	FeedID    string         `json:"feed_id"`
}

func (q *Queries) UpdateFeedEntry(ctx context.Context, arg UpdateFeedEntryParams) (RecallyFeedEntry, error) {
	row := q.db.QueryRowContext(ctx, updateFeedEntry,
		arg.Status,
		arg.ArticleID,
		arg.ErrorMsg,
		arg.ID,
		arg.FeedID,
	)
	var i RecallyFeedEntry
	err := row.Scan(
		&i.ID,
		&i.FeedID,
		&i.Guid,
		&i.Url,
		&i.Title,
		&i.Status,
		&i.ArticleID,
		&i.Attempts,
		&i.ErrorMsg,
		&i.DiscoveredAt,
		&i.ProcessedAt,
	)
	return i, err
}
