// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: settings_plugin.sql

package sqlc

import (
	"context"
)

const deletePlugin = `-- name: DeletePlugin :exec
DELETE FROM settings_plugin WHERE id = ? AND org_id = ?
`

type DeletePluginParams struct {
	ID    string `json:"id"`
	OrgID string `json:"org_id"`
}

func (q *Queries) DeletePlugin(ctx context.Context, arg DeletePluginParams) error {
	_, err := q.db.ExecContext(ctx, deletePlugin, arg.ID, arg.OrgID)
	return err
}

const getPlugin = `-- name: GetPlugin :one
SELECT id, kind, name, enabled, config, org_id, created_at, updated_at FROM settings_plugin WHERE id = ? AND org_id = ?
`

type GetPluginParams struct {
	ID    string `json:"id"`
	OrgID string `json:"org_id"`
}

func (q *Queries) GetPlugin(ctx context.Context, arg GetPluginParams) (SettingsPlugin, error) {
	row := q.db.QueryRowContext(ctx, getPlugin, arg.ID, arg.OrgID)
	var i SettingsPlugin
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Name,
		&i.Enabled,
		&i.Config,
		&i.OrgID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEnabledPlugins = `-- name: ListEnabledPlugins :many
SELECT id, kind, name, enabled, config, org_id, created_at, updated_at FROM settings_plugin WHERE org_id = ? AND enabled = 1 ORDER BY kind, name
`

func (q *Queries) ListEnabledPlugins(ctx context.Context, orgID string) ([]SettingsPlugin, error) {
	rows, err := q.db.QueryContext(ctx, listEnabledPlugins, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SettingsPlugin{}
	for rows.Next() {
		var i SettingsPlugin
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Name,
			&i.Enabled,
			&i.Config,
			&i.OrgID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlugins = `-- name: ListPlugins :many
SELECT id, kind, name, enabled, config, org_id, created_at, updated_at FROM settings_plugin WHERE org_id = ? ORDER BY kind, name
`

func (q *Queries) ListPlugins(ctx context.Context, orgID string) ([]SettingsPlugin, error) {
	rows, err := q.db.QueryContext(ctx, listPlugins, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SettingsPlugin{}
	for rows.Next() {
		var i SettingsPlugin
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Name,
			&i.Enabled,
			&i.Config,
			&i.OrgID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPluginsByKind = `-- name: ListPluginsByKind :many
SELECT id, kind, name, enabled, config, org_id, created_at, updated_at FROM settings_plugin WHERE kind = ? AND org_id = ? ORDER BY name
`

type ListPluginsByKindParams struct {
	Kind  string `json:"kind"`
	OrgID string `json:"org_id"`
}

func (q *Queries) ListPluginsByKind(ctx context.Context, arg ListPluginsByKindParams) ([]SettingsPlugin, error) {
	rows, err := q.db.QueryContext(ctx, listPluginsByKind, arg.Kind, arg.OrgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SettingsPlugin{}
	for rows.Next() {
		var i SettingsPlugin
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Name,
			&i.Enabled,
			&i.Config,
			&i.OrgID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const seedPlugin = `-- name: SeedPlugin :exec
INSERT OR IGNORE INTO settings_plugin (id, kind, name, enabled, config, org_id)
VALUES (?, ?, ?, ?, ?, ?)
`

type SeedPluginParams struct {
	ID      string `json:"id"`
	Kind    string `json:"kind"`
	Name    string `json:"name"`
	Enabled int64  `json:"enabled"`
	Config  string `json:"config"`
	OrgID   string `json:"org_id"`
}

func (q *Queries) SeedPlugin(ctx context.Context, arg SeedPluginParams) error {
	_, err := q.db.ExecContext(ctx, seedPlugin,
		arg.ID,
		arg.Kind,
		arg.Name,
		arg.Enabled,
		arg.Config,
		arg.OrgID,
	)
	return err
}

const updatePluginConfig = `-- name: UpdatePluginConfig :exec
UPDATE settings_plugin SET config = ?, updated_at = datetime('now')
WHERE id = ? AND org_id = ?
`

type UpdatePluginConfigParams struct {
	Config string `json:"config"`
	ID     string `json:"id"`
	OrgID  string `json:"org_id"`
}

func (q *Queries) UpdatePluginConfig(ctx context.Context, arg UpdatePluginConfigParams) error {
	_, err := q.db.ExecContext(ctx, updatePluginConfig, arg.Config, arg.ID, arg.OrgID)
	return err
}

const updatePluginEnabled = `-- name: UpdatePluginEnabled :exec
UPDATE settings_plugin SET enabled = ?, updated_at = datetime('now')
WHERE id = ? AND org_id = ?
`

type UpdatePluginEnabledParams struct {
	Enabled int64  `json:"enabled"`
	ID      string `json:"id"`
	OrgID   string `json:"org_id"`
}

func (q *Queries) UpdatePluginEnabled(ctx context.Context, arg UpdatePluginEnabledParams) error {
	_, err := q.db.ExecContext(ctx, updatePluginEnabled, arg.Enabled, arg.ID, arg.OrgID)
	return err
}

const upsertPlugin = `-- name: UpsertPlugin :exec
INSERT INTO settings_plugin (id, kind, name, enabled, config, org_id, updated_at)
VALUES (?, ?, ?, ?, ?, ?, datetime('now'))
ON CONFLICT(id, org_id) DO UPDATE SET
    kind = excluded.kind,
    name = excluded.name,
    enabled = excluded.enabled,
    config = excluded.config,
    updated_at = datetime('now')
`

type UpsertPluginParams struct {
	ID      string `json:"id"`
	Kind    string `json:"kind"`
	Name    string `json:"name"`
	Enabled int64  `json:"enabled"`
	Config  string `json:"config"`
	OrgID   string `json:"org_id"`
}

func (q *Queries) UpsertPlugin(ctx context.Context, arg UpsertPluginParams) error {
	_, err := q.db.ExecContext(ctx, upsertPlugin,
		arg.ID,
		arg.Kind,
		arg.Name,
		arg.Enabled,
		arg.Config,
		arg.OrgID,
	)
	return err
}
