#!/bin/bash
#MISE description="Lint migrations for potential issues"

atlas migrate lint \
    --dev-url "sqlite://dev?mode=memory" \
    --dir "file://internal/db/migrations" \
    --git-base "main"
