// Code generated by cmd/generatebuiltinmanifest; DO NOT EDIT.

package system

// RuntimeResources returns every system CLI, independent of plugin configuration.
// Each call returns fresh declarations, including nested options and skill refs.
func RuntimeResources() []RuntimeResource {
	return []RuntimeResource{
		{Name: "fd", MiseTool: "github:sharkdp/fd", Version: "10.4.2"},
		{Name: "mise", Embedded: true},
		{Name: "rg", MiseTool: "github:BurntSushi/ripgrep", Version: "15.2.0"},
		{Name: "xberg", Embedded: true, SkillRefs: []string{"builtin:xberg"}},
	}
}
