package db

import (
	"context"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/jackc/pgx/v5/pgxpool"

	"github.com/CherryHQ/stella/internal/auth"
	"github.com/CherryHQ/stella/pkg/db/sqlc"
)

// AuthStore implements auth.AuthStore using sqlc queries backed by PostgreSQL.
// It embeds OIDCStore to satisfy all new auth store interfaces so that
// gateway.go can pass a single *AuthStore to all wiring points without
// knowing about the split between sqlc-backed and raw-SQL-backed stores.
type AuthStore struct {
	*OIDCStore
	q *sqlc.Queries
}

// NewAuthStore creates a new AuthStore wrapping the given database connection.
func NewAuthStore(db *pgxpool.Pool) *AuthStore {
	return &AuthStore{OIDCStore: NewOIDCStore(db), q: sqlc.New(db)}
}

// --- User-Agent assignments ---

func (s *AuthStore) AssignAgent(ctx context.Context, userID string, agentID string) error {
	return s.withAgentAssignmentLock(ctx, userID, agentID, func(q *sqlc.Queries) error {
		return q.AssignUserAgent(ctx, sqlc.AssignUserAgentParams{UserID: userID, AgentID: agentID})
	})
}

func (s *AuthStore) RemoveAgent(ctx context.Context, userID string, agentID string) error {
	return s.withAgentAssignmentLock(ctx, userID, agentID, func(q *sqlc.Queries) error {
		return q.RemoveUserAgent(ctx, sqlc.RemoveUserAgentParams{UserID: userID, AgentID: agentID})
	})
}

// withAgentAssignmentLock serializes administrative assignment changes with the
// system→restricted transition in store.DBStore. Both sides must hold the same
// transaction-scoped lock: locking only the Agent row lets a child-row revoke
// commit between the transition's CAS and its assignment insert.
func (s *AuthStore) withAgentAssignmentLock(ctx context.Context, userID, agentID string, mutate func(*sqlc.Queries) error) error {
	if s.rawDB == nil {
		return fmt.Errorf("agent assignment %q for user %s: root database is unavailable", agentID, userID)
	}
	tx, err := s.rawDB.Begin(ctx)
	if err != nil {
		return fmt.Errorf("begin agent assignment %q for user %s: %w", agentID, userID, err)
	}
	defer tx.Rollback(ctx) //nolint:errcheck // successful commit makes rollback inert
	if err := AdvisoryXactLock(ctx, tx, AgentAssignmentLockKey(userID, agentID)); err != nil {
		return fmt.Errorf("lock agent assignment %q for user %s: %w", agentID, userID, err)
	}
	if err := mutate(s.q.WithTx(tx)); err != nil {
		return fmt.Errorf("mutate agent assignment %q for user %s: %w", agentID, userID, err)
	}
	if err := tx.Commit(ctx); err != nil {
		return fmt.Errorf("commit agent assignment %q for user %s: %w", agentID, userID, err)
	}
	return nil
}

func (s *AuthStore) ListUserAgentIDs(ctx context.Context, userID string) ([]string, error) {
	rows, err := s.q.ListUserAgents(ctx, userID)
	if err != nil {
		return nil, fmt.Errorf("list user agents for user %s: %w", userID, err)
	}
	out := make([]string, len(rows))
	copy(out, rows)
	return out, nil
}

func (s *AuthStore) ListAgentUserIDs(ctx context.Context, agentID string) ([]string, error) {
	rows, err := s.q.ListAgentUsers(ctx, agentID)
	if err != nil {
		return nil, fmt.Errorf("list agent users for agent %q: %w", agentID, err)
	}
	out := make([]string, len(rows))
	copy(out, rows)
	return out, nil
}

// --- User tokens ---

func (s *AuthStore) CreateUserToken(ctx context.Context, token auth.UserToken) (auth.UserToken, error) {
	r, err := s.q.CreateAuthUserToken(ctx, sqlc.CreateAuthUserTokenParams{
		ID:            uuid.Must(uuid.NewV7()).String(),
		UserID:        token.UserID,
		Name:          token.Name,
		TokenHash:     token.TokenHash,
		TokenPrefix:   token.TokenPrefix,
		AutoGenerated: token.AutoGenerated,
		ExpiresAt:     nullTimeFromTimePtr(token.ExpiresAt),
	})
	if err != nil {
		return auth.UserToken{}, fmt.Errorf("create user token for user %s: %w", token.UserID, err)
	}
	return userTokenFromDB(r), nil
}

func (s *AuthStore) GetUserTokenByHash(ctx context.Context, tokenHash string) (auth.UserToken, error) {
	r, err := s.q.GetAuthUserTokenByHash(ctx, tokenHash)
	if err != nil {
		return auth.UserToken{}, fmt.Errorf("get user token by hash: %w", err)
	}
	return userTokenFromDB(r), nil
}

func (s *AuthStore) GetActiveUserTokenByHash(ctx context.Context, tokenHash string) (auth.UserToken, error) {
	r, err := s.q.GetActiveAuthUserTokenByHash(ctx, tokenHash)
	if err != nil {
		return auth.UserToken{}, fmt.Errorf("get active user token by hash: %w", err)
	}
	return userTokenFromDB(r), nil
}

func (s *AuthStore) GetActiveAutoUserToken(ctx context.Context, userID string) (auth.UserToken, error) {
	r, err := s.q.GetActiveAutoAuthUserTokenByUser(ctx, userID)
	if err != nil {
		return auth.UserToken{}, fmt.Errorf("get active auto user token for user %s: %w", userID, err)
	}
	return userTokenFromDB(r), nil
}

func (s *AuthStore) RotateUserToken(ctx context.Context, id string) (int64, error) {
	rows, err := s.q.RotateAuthUserToken(ctx, id)
	if err != nil {
		return 0, fmt.Errorf("rotate user token %s: %w", id, err)
	}
	return rows, nil
}

func (s *AuthStore) RevokeUserToken(ctx context.Context, id string) (int64, error) {
	rows, err := s.q.RevokeAuthUserToken(ctx, id)
	if err != nil {
		return 0, fmt.Errorf("revoke user token %s: %w", id, err)
	}
	return rows, nil
}

func (s *AuthStore) UpdateUserTokenLastUsed(ctx context.Context, id string) (int64, error) {
	rows, err := s.q.UpdateAuthUserTokenLastUsed(ctx, id)
	if err != nil {
		return 0, fmt.Errorf("update user token %s last used: %w", id, err)
	}
	return rows, nil
}

// --- Helpers ---

func userTokenFromDB(r sqlc.AuthUserToken) auth.UserToken {
	return auth.UserToken{
		ID:            r.ID,
		UserID:        r.UserID,
		Name:          r.Name,
		TokenHash:     r.TokenHash,
		TokenPrefix:   r.TokenPrefix,
		AutoGenerated: r.AutoGenerated,
		LastUsedAt:    timePtrFromNullTime(r.LastUsedAt),
		ExpiresAt:     timePtrFromNullTime(r.ExpiresAt),
		RotatedAt:     timePtrFromNullTime(r.RotatedAt),
		RevokedAt:     timePtrFromNullTime(r.RevokedAt),
		CreatedAt:     r.CreatedAt.UTC(),
		UpdatedAt:     r.UpdatedAt.UTC(),
	}
}

func nullTimeFromTimePtr(t *time.Time) pgtype.Timestamptz {
	if t == nil || t.IsZero() {
		return pgtype.Timestamptz{}
	}
	return pgtype.Timestamptz{Time: t.UTC(), Valid: true}
}

func timePtrFromNullTime(n pgtype.Timestamptz) *time.Time {
	if !n.Valid {
		return nil
	}
	t := n.Time.UTC()
	return &t
}
