// Code generated by go run ./internal/cmd/gentoolschema; DO NOT EDIT.

package domaintools

import (
	"context"
	"fmt"
)

func SchedulerInputSchema() map[string]any {
	return mustDomainToolInputSchema(SchedulerInputSchemaJSON)
}

const SchedulerInputSchemaJSON = `{
  "oneOf": [
    {
      "properties": {
        "action": {
          "const": "create",
          "type": "string"
        },
        "allow_replan": {
          "description": "Allow scheduling a partially frozen workflow.",
          "type": "boolean"
        },
        "at": {
          "type": "string"
        },
        "cron": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "dispatch_kind": {
          "enum": [
            "chat",
            "workflow"
          ],
          "type": "string"
        },
        "enabled": {
          "type": "boolean"
        },
        "every": {
          "type": "string"
        },
        "idempotency_key": {
          "description": "Optional key; repeated creates by the same user with the same key return the existing job.",
          "type": "string"
        },
        "inputs": {
          "additionalProperties": {
            "type": "string"
          },
          "description": "Workflow input values.",
          "type": "object"
        },
        "message": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "session_mode": {
          "type": "string"
        },
        "template_key": {
          "description": "Optional. When set, create a subscription instance for this template. name/message are filled from the template; schedule fields may override defaults.",
          "type": "string"
        },
        "workflow_id": {
          "description": "Exact workflow version row to instantiate when dispatch_kind is workflow.",
          "type": "string"
        }
      },
      "required": [
        "action"
      ],
      "type": "object"
    },
    {
      "properties": {
        "action": {
          "const": "delete",
          "type": "string"
        },
        "id": {
          "type": "string"
        }
      },
      "required": [
        "action",
        "id"
      ],
      "type": "object"
    },
    {
      "properties": {
        "action": {
          "const": "get",
          "type": "string"
        },
        "id": {
          "type": "string"
        }
      },
      "required": [
        "action",
        "id"
      ],
      "type": "object"
    },
    {
      "properties": {
        "action": {
          "const": "list",
          "type": "string"
        }
      },
      "required": [
        "action"
      ],
      "type": "object"
    },
    {
      "properties": {
        "action": {
          "const": "pause",
          "type": "string"
        },
        "id": {
          "type": "string"
        }
      },
      "required": [
        "action",
        "id"
      ],
      "type": "object"
    },
    {
      "properties": {
        "action": {
          "const": "resume",
          "type": "string"
        },
        "id": {
          "type": "string"
        }
      },
      "required": [
        "action",
        "id"
      ],
      "type": "object"
    },
    {
      "properties": {
        "action": {
          "const": "update",
          "type": "string"
        },
        "allow_replan": {
          "description": "Allow scheduling a partially frozen workflow.",
          "type": "boolean"
        },
        "at": {
          "type": "string"
        },
        "cron": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "dispatch_kind": {
          "enum": [
            "chat",
            "workflow"
          ],
          "type": "string"
        },
        "enabled": {
          "type": "boolean"
        },
        "every": {
          "type": "string"
        },
        "id": {
          "type": "string"
        },
        "idempotency_key": {
          "description": "Optional key; repeated creates by the same user with the same key return the existing job.",
          "type": "string"
        },
        "inputs": {
          "additionalProperties": {
            "type": "string"
          },
          "description": "Workflow input values.",
          "type": "object"
        },
        "message": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "session_mode": {
          "type": "string"
        },
        "template_key": {
          "description": "Optional. When set, create a subscription instance for this template. name/message are filled from the template; schedule fields may override defaults.",
          "type": "string"
        },
        "workflow_id": {
          "description": "Exact workflow version row to instantiate when dispatch_kind is workflow.",
          "type": "string"
        }
      },
      "required": [
        "action",
        "id"
      ],
      "type": "object"
    }
  ],
  "properties": {
    "action": {
      "enum": [
        "create",
        "delete",
        "get",
        "list",
        "pause",
        "resume",
        "update"
      ],
      "type": "string"
    }
  },
  "required": [
    "action"
  ],
  "type": "object"
}`

type SchedulerHandler interface {
	Create(context.Context, SchedulerCreateInput) (any, error)
	Delete(context.Context, SchedulerDeleteInput) (any, error)
	Get(context.Context, SchedulerGetInput) (any, error)
	List(context.Context, SchedulerListInput) (any, error)
	Pause(context.Context, SchedulerPauseInput) (any, error)
	Resume(context.Context, SchedulerResumeInput) (any, error)
	Update(context.Context, SchedulerUpdateInput) (any, error)
}

type SchedulerCreateInput struct {
	AllowReplan    *bool          `json:"allow_replan,omitempty"`
	At             string         `json:"at,omitempty"`
	Cron           string         `json:"cron,omitempty"`
	Description    string         `json:"description,omitempty"`
	DispatchKind   string         `json:"dispatch_kind,omitempty"`
	Enabled        *bool          `json:"enabled,omitempty"`
	Every          string         `json:"every,omitempty"`
	IdempotencyKey string         `json:"idempotency_key,omitempty"`
	Inputs         map[string]any `json:"inputs,omitempty"`
	Message        string         `json:"message,omitempty"`
	Name           string         `json:"name,omitempty"`
	SessionMode    string         `json:"session_mode,omitempty"`
	TemplateKey    string         `json:"template_key,omitempty"`
	WorkflowId     string         `json:"workflow_id,omitempty"`
}

type SchedulerDeleteInput struct {
	Id string `json:"id,omitempty"`
}

type SchedulerGetInput struct {
	Id string `json:"id,omitempty"`
}

type SchedulerListInput struct {
}

type SchedulerPauseInput struct {
	Id string `json:"id,omitempty"`
}

type SchedulerResumeInput struct {
	Id string `json:"id,omitempty"`
}

type SchedulerUpdateInput struct {
	AllowReplan    *bool          `json:"allow_replan,omitempty"`
	At             string         `json:"at,omitempty"`
	Cron           string         `json:"cron,omitempty"`
	Description    string         `json:"description,omitempty"`
	DispatchKind   string         `json:"dispatch_kind,omitempty"`
	Enabled        *bool          `json:"enabled,omitempty"`
	Every          string         `json:"every,omitempty"`
	Id             string         `json:"id,omitempty"`
	IdempotencyKey string         `json:"idempotency_key,omitempty"`
	Inputs         map[string]any `json:"inputs,omitempty"`
	Message        string         `json:"message,omitempty"`
	Name           string         `json:"name,omitempty"`
	SessionMode    string         `json:"session_mode,omitempty"`
	TemplateKey    string         `json:"template_key,omitempty"`
	WorkflowId     string         `json:"workflow_id,omitempty"`
}

func DispatchScheduler(ctx context.Context, h SchedulerHandler, action string, args map[string]any) (any, error) {
	switch action {
	case "create":
		var in SchedulerCreateInput
		if err := decodeDomainToolInput(args, &in, []string(nil)); err != nil {
			return nil, err
		}
		return h.Create(ctx, in)
	case "delete":
		var in SchedulerDeleteInput
		if err := decodeDomainToolInput(args, &in, []string{"id"}); err != nil {
			return nil, err
		}
		return h.Delete(ctx, in)
	case "get":
		var in SchedulerGetInput
		if err := decodeDomainToolInput(args, &in, []string{"id"}); err != nil {
			return nil, err
		}
		return h.Get(ctx, in)
	case "list":
		var in SchedulerListInput
		if err := decodeDomainToolInput(args, &in, []string(nil)); err != nil {
			return nil, err
		}
		return h.List(ctx, in)
	case "pause":
		var in SchedulerPauseInput
		if err := decodeDomainToolInput(args, &in, []string{"id"}); err != nil {
			return nil, err
		}
		return h.Pause(ctx, in)
	case "resume":
		var in SchedulerResumeInput
		if err := decodeDomainToolInput(args, &in, []string{"id"}); err != nil {
			return nil, err
		}
		return h.Resume(ctx, in)
	case "update":
		var in SchedulerUpdateInput
		if err := decodeDomainToolInput(args, &in, []string{"id"}); err != nil {
			return nil, err
		}
		return h.Update(ctx, in)
	default:
		return nil, fmt.Errorf("unknown scheduler action %q", action)
	}
}
